// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc.proto

package lightpay.lnd.grpc;

/**
 * Protobuf type {@code lnrpc.AddInvoiceResponse}
 */
public  final class AddInvoiceResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:lnrpc.AddInvoiceResponse)
    AddInvoiceResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use AddInvoiceResponse.newBuilder() to construct.
  private AddInvoiceResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AddInvoiceResponse() {
    rHash_ = com.google.protobuf.ByteString.EMPTY;
    paymentRequest_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private AddInvoiceResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {

            rHash_ = input.readBytes();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            paymentRequest_ = s;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return lightpay.lnd.grpc.Rpc.internal_static_lnrpc_AddInvoiceResponse_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return lightpay.lnd.grpc.Rpc.internal_static_lnrpc_AddInvoiceResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            lightpay.lnd.grpc.AddInvoiceResponse.class, lightpay.lnd.grpc.AddInvoiceResponse.Builder.class);
  }

  public static final int R_HASH_FIELD_NUMBER = 1;
  private com.google.protobuf.ByteString rHash_;
  /**
   * <code>bytes r_hash = 1[json_name = "r_hash"];</code>
   */
  public com.google.protobuf.ByteString getRHash() {
    return rHash_;
  }

  public static final int PAYMENT_REQUEST_FIELD_NUMBER = 2;
  private volatile java.lang.Object paymentRequest_;
  /**
   * <pre>
   **
   *A bare-bones invoice for a payment within the Lightning Network.  With the
   *details of the invoice, the sender has all the data necessary to send a
   *payment to the recipient.
   * </pre>
   *
   * <code>string payment_request = 2[json_name = "payment_request"];</code>
   */
  public java.lang.String getPaymentRequest() {
    java.lang.Object ref = paymentRequest_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      paymentRequest_ = s;
      return s;
    }
  }
  /**
   * <pre>
   **
   *A bare-bones invoice for a payment within the Lightning Network.  With the
   *details of the invoice, the sender has all the data necessary to send a
   *payment to the recipient.
   * </pre>
   *
   * <code>string payment_request = 2[json_name = "payment_request"];</code>
   */
  public com.google.protobuf.ByteString
      getPaymentRequestBytes() {
    java.lang.Object ref = paymentRequest_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      paymentRequest_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!rHash_.isEmpty()) {
      output.writeBytes(1, rHash_);
    }
    if (!getPaymentRequestBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, paymentRequest_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!rHash_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(1, rHash_);
    }
    if (!getPaymentRequestBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, paymentRequest_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof lightpay.lnd.grpc.AddInvoiceResponse)) {
      return super.equals(obj);
    }
    lightpay.lnd.grpc.AddInvoiceResponse other = (lightpay.lnd.grpc.AddInvoiceResponse) obj;

    boolean result = true;
    result = result && getRHash()
        .equals(other.getRHash());
    result = result && getPaymentRequest()
        .equals(other.getPaymentRequest());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + R_HASH_FIELD_NUMBER;
    hash = (53 * hash) + getRHash().hashCode();
    hash = (37 * hash) + PAYMENT_REQUEST_FIELD_NUMBER;
    hash = (53 * hash) + getPaymentRequest().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static lightpay.lnd.grpc.AddInvoiceResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static lightpay.lnd.grpc.AddInvoiceResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static lightpay.lnd.grpc.AddInvoiceResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static lightpay.lnd.grpc.AddInvoiceResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static lightpay.lnd.grpc.AddInvoiceResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static lightpay.lnd.grpc.AddInvoiceResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static lightpay.lnd.grpc.AddInvoiceResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static lightpay.lnd.grpc.AddInvoiceResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static lightpay.lnd.grpc.AddInvoiceResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static lightpay.lnd.grpc.AddInvoiceResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static lightpay.lnd.grpc.AddInvoiceResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static lightpay.lnd.grpc.AddInvoiceResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(lightpay.lnd.grpc.AddInvoiceResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code lnrpc.AddInvoiceResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:lnrpc.AddInvoiceResponse)
      lightpay.lnd.grpc.AddInvoiceResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return lightpay.lnd.grpc.Rpc.internal_static_lnrpc_AddInvoiceResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return lightpay.lnd.grpc.Rpc.internal_static_lnrpc_AddInvoiceResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              lightpay.lnd.grpc.AddInvoiceResponse.class, lightpay.lnd.grpc.AddInvoiceResponse.Builder.class);
    }

    // Construct using lightpay.lnd.grpc.AddInvoiceResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      rHash_ = com.google.protobuf.ByteString.EMPTY;

      paymentRequest_ = "";

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return lightpay.lnd.grpc.Rpc.internal_static_lnrpc_AddInvoiceResponse_descriptor;
    }

    public lightpay.lnd.grpc.AddInvoiceResponse getDefaultInstanceForType() {
      return lightpay.lnd.grpc.AddInvoiceResponse.getDefaultInstance();
    }

    public lightpay.lnd.grpc.AddInvoiceResponse build() {
      lightpay.lnd.grpc.AddInvoiceResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public lightpay.lnd.grpc.AddInvoiceResponse buildPartial() {
      lightpay.lnd.grpc.AddInvoiceResponse result = new lightpay.lnd.grpc.AddInvoiceResponse(this);
      result.rHash_ = rHash_;
      result.paymentRequest_ = paymentRequest_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof lightpay.lnd.grpc.AddInvoiceResponse) {
        return mergeFrom((lightpay.lnd.grpc.AddInvoiceResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(lightpay.lnd.grpc.AddInvoiceResponse other) {
      if (other == lightpay.lnd.grpc.AddInvoiceResponse.getDefaultInstance()) return this;
      if (other.getRHash() != com.google.protobuf.ByteString.EMPTY) {
        setRHash(other.getRHash());
      }
      if (!other.getPaymentRequest().isEmpty()) {
        paymentRequest_ = other.paymentRequest_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      lightpay.lnd.grpc.AddInvoiceResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (lightpay.lnd.grpc.AddInvoiceResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.google.protobuf.ByteString rHash_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes r_hash = 1[json_name = "r_hash"];</code>
     */
    public com.google.protobuf.ByteString getRHash() {
      return rHash_;
    }
    /**
     * <code>bytes r_hash = 1[json_name = "r_hash"];</code>
     */
    public Builder setRHash(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      rHash_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bytes r_hash = 1[json_name = "r_hash"];</code>
     */
    public Builder clearRHash() {
      
      rHash_ = getDefaultInstance().getRHash();
      onChanged();
      return this;
    }

    private java.lang.Object paymentRequest_ = "";
    /**
     * <pre>
     **
     *A bare-bones invoice for a payment within the Lightning Network.  With the
     *details of the invoice, the sender has all the data necessary to send a
     *payment to the recipient.
     * </pre>
     *
     * <code>string payment_request = 2[json_name = "payment_request"];</code>
     */
    public java.lang.String getPaymentRequest() {
      java.lang.Object ref = paymentRequest_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        paymentRequest_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     **
     *A bare-bones invoice for a payment within the Lightning Network.  With the
     *details of the invoice, the sender has all the data necessary to send a
     *payment to the recipient.
     * </pre>
     *
     * <code>string payment_request = 2[json_name = "payment_request"];</code>
     */
    public com.google.protobuf.ByteString
        getPaymentRequestBytes() {
      java.lang.Object ref = paymentRequest_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        paymentRequest_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     **
     *A bare-bones invoice for a payment within the Lightning Network.  With the
     *details of the invoice, the sender has all the data necessary to send a
     *payment to the recipient.
     * </pre>
     *
     * <code>string payment_request = 2[json_name = "payment_request"];</code>
     */
    public Builder setPaymentRequest(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      paymentRequest_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     **
     *A bare-bones invoice for a payment within the Lightning Network.  With the
     *details of the invoice, the sender has all the data necessary to send a
     *payment to the recipient.
     * </pre>
     *
     * <code>string payment_request = 2[json_name = "payment_request"];</code>
     */
    public Builder clearPaymentRequest() {
      
      paymentRequest_ = getDefaultInstance().getPaymentRequest();
      onChanged();
      return this;
    }
    /**
     * <pre>
     **
     *A bare-bones invoice for a payment within the Lightning Network.  With the
     *details of the invoice, the sender has all the data necessary to send a
     *payment to the recipient.
     * </pre>
     *
     * <code>string payment_request = 2[json_name = "payment_request"];</code>
     */
    public Builder setPaymentRequestBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      paymentRequest_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:lnrpc.AddInvoiceResponse)
  }

  // @@protoc_insertion_point(class_scope:lnrpc.AddInvoiceResponse)
  private static final lightpay.lnd.grpc.AddInvoiceResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new lightpay.lnd.grpc.AddInvoiceResponse();
  }

  public static lightpay.lnd.grpc.AddInvoiceResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AddInvoiceResponse>
      PARSER = new com.google.protobuf.AbstractParser<AddInvoiceResponse>() {
    public AddInvoiceResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new AddInvoiceResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<AddInvoiceResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AddInvoiceResponse> getParserForType() {
    return PARSER;
  }

  public lightpay.lnd.grpc.AddInvoiceResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

