// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc.proto

package lightpay.lnd.grpc;

/**
 * Protobuf type {@code lnrpc.ChannelOpenUpdate}
 */
public  final class ChannelOpenUpdate extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:lnrpc.ChannelOpenUpdate)
    ChannelOpenUpdateOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ChannelOpenUpdate.newBuilder() to construct.
  private ChannelOpenUpdate(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ChannelOpenUpdate() {
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ChannelOpenUpdate(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            lightpay.lnd.grpc.ChannelPoint.Builder subBuilder = null;
            if (channelPoint_ != null) {
              subBuilder = channelPoint_.toBuilder();
            }
            channelPoint_ = input.readMessage(lightpay.lnd.grpc.ChannelPoint.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(channelPoint_);
              channelPoint_ = subBuilder.buildPartial();
            }

            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return lightpay.lnd.grpc.Rpc.internal_static_lnrpc_ChannelOpenUpdate_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return lightpay.lnd.grpc.Rpc.internal_static_lnrpc_ChannelOpenUpdate_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            lightpay.lnd.grpc.ChannelOpenUpdate.class, lightpay.lnd.grpc.ChannelOpenUpdate.Builder.class);
  }

  public static final int CHANNEL_POINT_FIELD_NUMBER = 1;
  private lightpay.lnd.grpc.ChannelPoint channelPoint_;
  /**
   * <code>.lnrpc.ChannelPoint channel_point = 1[json_name = "channel_point"];</code>
   */
  public boolean hasChannelPoint() {
    return channelPoint_ != null;
  }
  /**
   * <code>.lnrpc.ChannelPoint channel_point = 1[json_name = "channel_point"];</code>
   */
  public lightpay.lnd.grpc.ChannelPoint getChannelPoint() {
    return channelPoint_ == null ? lightpay.lnd.grpc.ChannelPoint.getDefaultInstance() : channelPoint_;
  }
  /**
   * <code>.lnrpc.ChannelPoint channel_point = 1[json_name = "channel_point"];</code>
   */
  public lightpay.lnd.grpc.ChannelPointOrBuilder getChannelPointOrBuilder() {
    return getChannelPoint();
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (channelPoint_ != null) {
      output.writeMessage(1, getChannelPoint());
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (channelPoint_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getChannelPoint());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof lightpay.lnd.grpc.ChannelOpenUpdate)) {
      return super.equals(obj);
    }
    lightpay.lnd.grpc.ChannelOpenUpdate other = (lightpay.lnd.grpc.ChannelOpenUpdate) obj;

    boolean result = true;
    result = result && (hasChannelPoint() == other.hasChannelPoint());
    if (hasChannelPoint()) {
      result = result && getChannelPoint()
          .equals(other.getChannelPoint());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasChannelPoint()) {
      hash = (37 * hash) + CHANNEL_POINT_FIELD_NUMBER;
      hash = (53 * hash) + getChannelPoint().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static lightpay.lnd.grpc.ChannelOpenUpdate parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static lightpay.lnd.grpc.ChannelOpenUpdate parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static lightpay.lnd.grpc.ChannelOpenUpdate parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static lightpay.lnd.grpc.ChannelOpenUpdate parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static lightpay.lnd.grpc.ChannelOpenUpdate parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static lightpay.lnd.grpc.ChannelOpenUpdate parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static lightpay.lnd.grpc.ChannelOpenUpdate parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static lightpay.lnd.grpc.ChannelOpenUpdate parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static lightpay.lnd.grpc.ChannelOpenUpdate parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static lightpay.lnd.grpc.ChannelOpenUpdate parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static lightpay.lnd.grpc.ChannelOpenUpdate parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static lightpay.lnd.grpc.ChannelOpenUpdate parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(lightpay.lnd.grpc.ChannelOpenUpdate prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code lnrpc.ChannelOpenUpdate}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:lnrpc.ChannelOpenUpdate)
      lightpay.lnd.grpc.ChannelOpenUpdateOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return lightpay.lnd.grpc.Rpc.internal_static_lnrpc_ChannelOpenUpdate_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return lightpay.lnd.grpc.Rpc.internal_static_lnrpc_ChannelOpenUpdate_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              lightpay.lnd.grpc.ChannelOpenUpdate.class, lightpay.lnd.grpc.ChannelOpenUpdate.Builder.class);
    }

    // Construct using lightpay.lnd.grpc.ChannelOpenUpdate.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      if (channelPointBuilder_ == null) {
        channelPoint_ = null;
      } else {
        channelPoint_ = null;
        channelPointBuilder_ = null;
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return lightpay.lnd.grpc.Rpc.internal_static_lnrpc_ChannelOpenUpdate_descriptor;
    }

    public lightpay.lnd.grpc.ChannelOpenUpdate getDefaultInstanceForType() {
      return lightpay.lnd.grpc.ChannelOpenUpdate.getDefaultInstance();
    }

    public lightpay.lnd.grpc.ChannelOpenUpdate build() {
      lightpay.lnd.grpc.ChannelOpenUpdate result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public lightpay.lnd.grpc.ChannelOpenUpdate buildPartial() {
      lightpay.lnd.grpc.ChannelOpenUpdate result = new lightpay.lnd.grpc.ChannelOpenUpdate(this);
      if (channelPointBuilder_ == null) {
        result.channelPoint_ = channelPoint_;
      } else {
        result.channelPoint_ = channelPointBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof lightpay.lnd.grpc.ChannelOpenUpdate) {
        return mergeFrom((lightpay.lnd.grpc.ChannelOpenUpdate)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(lightpay.lnd.grpc.ChannelOpenUpdate other) {
      if (other == lightpay.lnd.grpc.ChannelOpenUpdate.getDefaultInstance()) return this;
      if (other.hasChannelPoint()) {
        mergeChannelPoint(other.getChannelPoint());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      lightpay.lnd.grpc.ChannelOpenUpdate parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (lightpay.lnd.grpc.ChannelOpenUpdate) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private lightpay.lnd.grpc.ChannelPoint channelPoint_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        lightpay.lnd.grpc.ChannelPoint, lightpay.lnd.grpc.ChannelPoint.Builder, lightpay.lnd.grpc.ChannelPointOrBuilder> channelPointBuilder_;
    /**
     * <code>.lnrpc.ChannelPoint channel_point = 1[json_name = "channel_point"];</code>
     */
    public boolean hasChannelPoint() {
      return channelPointBuilder_ != null || channelPoint_ != null;
    }
    /**
     * <code>.lnrpc.ChannelPoint channel_point = 1[json_name = "channel_point"];</code>
     */
    public lightpay.lnd.grpc.ChannelPoint getChannelPoint() {
      if (channelPointBuilder_ == null) {
        return channelPoint_ == null ? lightpay.lnd.grpc.ChannelPoint.getDefaultInstance() : channelPoint_;
      } else {
        return channelPointBuilder_.getMessage();
      }
    }
    /**
     * <code>.lnrpc.ChannelPoint channel_point = 1[json_name = "channel_point"];</code>
     */
    public Builder setChannelPoint(lightpay.lnd.grpc.ChannelPoint value) {
      if (channelPointBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        channelPoint_ = value;
        onChanged();
      } else {
        channelPointBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.lnrpc.ChannelPoint channel_point = 1[json_name = "channel_point"];</code>
     */
    public Builder setChannelPoint(
        lightpay.lnd.grpc.ChannelPoint.Builder builderForValue) {
      if (channelPointBuilder_ == null) {
        channelPoint_ = builderForValue.build();
        onChanged();
      } else {
        channelPointBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.lnrpc.ChannelPoint channel_point = 1[json_name = "channel_point"];</code>
     */
    public Builder mergeChannelPoint(lightpay.lnd.grpc.ChannelPoint value) {
      if (channelPointBuilder_ == null) {
        if (channelPoint_ != null) {
          channelPoint_ =
            lightpay.lnd.grpc.ChannelPoint.newBuilder(channelPoint_).mergeFrom(value).buildPartial();
        } else {
          channelPoint_ = value;
        }
        onChanged();
      } else {
        channelPointBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.lnrpc.ChannelPoint channel_point = 1[json_name = "channel_point"];</code>
     */
    public Builder clearChannelPoint() {
      if (channelPointBuilder_ == null) {
        channelPoint_ = null;
        onChanged();
      } else {
        channelPoint_ = null;
        channelPointBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.lnrpc.ChannelPoint channel_point = 1[json_name = "channel_point"];</code>
     */
    public lightpay.lnd.grpc.ChannelPoint.Builder getChannelPointBuilder() {
      
      onChanged();
      return getChannelPointFieldBuilder().getBuilder();
    }
    /**
     * <code>.lnrpc.ChannelPoint channel_point = 1[json_name = "channel_point"];</code>
     */
    public lightpay.lnd.grpc.ChannelPointOrBuilder getChannelPointOrBuilder() {
      if (channelPointBuilder_ != null) {
        return channelPointBuilder_.getMessageOrBuilder();
      } else {
        return channelPoint_ == null ?
            lightpay.lnd.grpc.ChannelPoint.getDefaultInstance() : channelPoint_;
      }
    }
    /**
     * <code>.lnrpc.ChannelPoint channel_point = 1[json_name = "channel_point"];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        lightpay.lnd.grpc.ChannelPoint, lightpay.lnd.grpc.ChannelPoint.Builder, lightpay.lnd.grpc.ChannelPointOrBuilder> 
        getChannelPointFieldBuilder() {
      if (channelPointBuilder_ == null) {
        channelPointBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            lightpay.lnd.grpc.ChannelPoint, lightpay.lnd.grpc.ChannelPoint.Builder, lightpay.lnd.grpc.ChannelPointOrBuilder>(
                getChannelPoint(),
                getParentForChildren(),
                isClean());
        channelPoint_ = null;
      }
      return channelPointBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:lnrpc.ChannelOpenUpdate)
  }

  // @@protoc_insertion_point(class_scope:lnrpc.ChannelOpenUpdate)
  private static final lightpay.lnd.grpc.ChannelOpenUpdate DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new lightpay.lnd.grpc.ChannelOpenUpdate();
  }

  public static lightpay.lnd.grpc.ChannelOpenUpdate getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ChannelOpenUpdate>
      PARSER = new com.google.protobuf.AbstractParser<ChannelOpenUpdate>() {
    public ChannelOpenUpdate parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ChannelOpenUpdate(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ChannelOpenUpdate> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ChannelOpenUpdate> getParserForType() {
    return PARSER;
  }

  public lightpay.lnd.grpc.ChannelOpenUpdate getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

