// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc.proto

package lightpay.lnd.grpc;

public interface DebugLevelRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:lnrpc.DebugLevelRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool show = 1;</code>
   */
  boolean getShow();

  /**
   * <code>string level_spec = 2;</code>
   */
  java.lang.String getLevelSpec();
  /**
   * <code>string level_spec = 2;</code>
   */
  com.google.protobuf.ByteString
      getLevelSpecBytes();
}
