// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc.proto

package lightpay.lnd.grpc;

public interface DeleteAllPaymentsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:lnrpc.DeleteAllPaymentsResponse)
    com.google.protobuf.MessageOrBuilder {
}
