// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc.proto

package lightpay.lnd.grpc;

public interface DisconnectPeerResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:lnrpc.DisconnectPeerResponse)
    com.google.protobuf.MessageOrBuilder {
}
