// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc.proto

package lightpay.lnd.grpc;

public interface FeeReportResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:lnrpc.FeeReportResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *&#47; An array of channel fee reports which describes the current fee schedule for each channel.
   * </pre>
   *
   * <code>repeated .lnrpc.ChannelFeeReport channel_fees = 1[json_name = "channel_fees"];</code>
   */
  java.util.List<lightpay.lnd.grpc.ChannelFeeReport> 
      getChannelFeesList();
  /**
   * <pre>
   *&#47; An array of channel fee reports which describes the current fee schedule for each channel.
   * </pre>
   *
   * <code>repeated .lnrpc.ChannelFeeReport channel_fees = 1[json_name = "channel_fees"];</code>
   */
  lightpay.lnd.grpc.ChannelFeeReport getChannelFees(int index);
  /**
   * <pre>
   *&#47; An array of channel fee reports which describes the current fee schedule for each channel.
   * </pre>
   *
   * <code>repeated .lnrpc.ChannelFeeReport channel_fees = 1[json_name = "channel_fees"];</code>
   */
  int getChannelFeesCount();
  /**
   * <pre>
   *&#47; An array of channel fee reports which describes the current fee schedule for each channel.
   * </pre>
   *
   * <code>repeated .lnrpc.ChannelFeeReport channel_fees = 1[json_name = "channel_fees"];</code>
   */
  java.util.List<? extends lightpay.lnd.grpc.ChannelFeeReportOrBuilder> 
      getChannelFeesOrBuilderList();
  /**
   * <pre>
   *&#47; An array of channel fee reports which describes the current fee schedule for each channel.
   * </pre>
   *
   * <code>repeated .lnrpc.ChannelFeeReport channel_fees = 1[json_name = "channel_fees"];</code>
   */
  lightpay.lnd.grpc.ChannelFeeReportOrBuilder getChannelFeesOrBuilder(
      int index);
}
