// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc.proto

package lightpay.lnd.grpc;

public interface GraphTopologySubscriptionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:lnrpc.GraphTopologySubscription)
    com.google.protobuf.MessageOrBuilder {
}
