// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc.proto

package lightpay.lnd.grpc;

public interface HopOrBuilder extends
    // @@protoc_insertion_point(interface_extends:lnrpc.Hop)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   **
   *The unique channel ID for the channel. The first 3 bytes are the block
   *height, the next 3 the index within the block, and the last 2 bytes are the
   *output index for the channel.
   * </pre>
   *
   * <code>uint64 chan_id = 1[json_name = "chan_id"];</code>
   */
  long getChanId();

  /**
   * <code>int64 chan_capacity = 2[json_name = "chan_capacity"];</code>
   */
  long getChanCapacity();

  /**
   * <code>int64 amt_to_forward = 3[json_name = "amt_to_forward"];</code>
   */
  long getAmtToForward();

  /**
   * <code>int64 fee = 4[json_name = "fee"];</code>
   */
  long getFee();

  /**
   * <code>uint32 expiry = 5[json_name = "expiry"];</code>
   */
  int getExpiry();
}
