// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc.proto

package lightpay.lnd.grpc;

public interface HTLCOrBuilder extends
    // @@protoc_insertion_point(interface_extends:lnrpc.HTLC)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool incoming = 1[json_name = "incoming"];</code>
   */
  boolean getIncoming();

  /**
   * <code>int64 amount = 2[json_name = "amount"];</code>
   */
  long getAmount();

  /**
   * <code>bytes hash_lock = 3[json_name = "hash_lock"];</code>
   */
  com.google.protobuf.ByteString getHashLock();

  /**
   * <code>uint32 expiration_height = 4[json_name = "expiration_height"];</code>
   */
  int getExpirationHeight();
}
