// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc.proto

package lightpay.lnd.grpc;

/**
 * Protobuf type {@code lnrpc.ListPeersResponse}
 */
public  final class ListPeersResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:lnrpc.ListPeersResponse)
    ListPeersResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ListPeersResponse.newBuilder() to construct.
  private ListPeersResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ListPeersResponse() {
    peers_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ListPeersResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              peers_ = new java.util.ArrayList<lightpay.lnd.grpc.Peer>();
              mutable_bitField0_ |= 0x00000001;
            }
            peers_.add(
                input.readMessage(lightpay.lnd.grpc.Peer.parser(), extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        peers_ = java.util.Collections.unmodifiableList(peers_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return lightpay.lnd.grpc.Rpc.internal_static_lnrpc_ListPeersResponse_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return lightpay.lnd.grpc.Rpc.internal_static_lnrpc_ListPeersResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            lightpay.lnd.grpc.ListPeersResponse.class, lightpay.lnd.grpc.ListPeersResponse.Builder.class);
  }

  public static final int PEERS_FIELD_NUMBER = 1;
  private java.util.List<lightpay.lnd.grpc.Peer> peers_;
  /**
   * <pre>
   *&#47; The list of currently connected peers
   * </pre>
   *
   * <code>repeated .lnrpc.Peer peers = 1[json_name = "peers"];</code>
   */
  public java.util.List<lightpay.lnd.grpc.Peer> getPeersList() {
    return peers_;
  }
  /**
   * <pre>
   *&#47; The list of currently connected peers
   * </pre>
   *
   * <code>repeated .lnrpc.Peer peers = 1[json_name = "peers"];</code>
   */
  public java.util.List<? extends lightpay.lnd.grpc.PeerOrBuilder> 
      getPeersOrBuilderList() {
    return peers_;
  }
  /**
   * <pre>
   *&#47; The list of currently connected peers
   * </pre>
   *
   * <code>repeated .lnrpc.Peer peers = 1[json_name = "peers"];</code>
   */
  public int getPeersCount() {
    return peers_.size();
  }
  /**
   * <pre>
   *&#47; The list of currently connected peers
   * </pre>
   *
   * <code>repeated .lnrpc.Peer peers = 1[json_name = "peers"];</code>
   */
  public lightpay.lnd.grpc.Peer getPeers(int index) {
    return peers_.get(index);
  }
  /**
   * <pre>
   *&#47; The list of currently connected peers
   * </pre>
   *
   * <code>repeated .lnrpc.Peer peers = 1[json_name = "peers"];</code>
   */
  public lightpay.lnd.grpc.PeerOrBuilder getPeersOrBuilder(
      int index) {
    return peers_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < peers_.size(); i++) {
      output.writeMessage(1, peers_.get(i));
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < peers_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, peers_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof lightpay.lnd.grpc.ListPeersResponse)) {
      return super.equals(obj);
    }
    lightpay.lnd.grpc.ListPeersResponse other = (lightpay.lnd.grpc.ListPeersResponse) obj;

    boolean result = true;
    result = result && getPeersList()
        .equals(other.getPeersList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getPeersCount() > 0) {
      hash = (37 * hash) + PEERS_FIELD_NUMBER;
      hash = (53 * hash) + getPeersList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static lightpay.lnd.grpc.ListPeersResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static lightpay.lnd.grpc.ListPeersResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static lightpay.lnd.grpc.ListPeersResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static lightpay.lnd.grpc.ListPeersResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static lightpay.lnd.grpc.ListPeersResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static lightpay.lnd.grpc.ListPeersResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static lightpay.lnd.grpc.ListPeersResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static lightpay.lnd.grpc.ListPeersResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static lightpay.lnd.grpc.ListPeersResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static lightpay.lnd.grpc.ListPeersResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static lightpay.lnd.grpc.ListPeersResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static lightpay.lnd.grpc.ListPeersResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(lightpay.lnd.grpc.ListPeersResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code lnrpc.ListPeersResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:lnrpc.ListPeersResponse)
      lightpay.lnd.grpc.ListPeersResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return lightpay.lnd.grpc.Rpc.internal_static_lnrpc_ListPeersResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return lightpay.lnd.grpc.Rpc.internal_static_lnrpc_ListPeersResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              lightpay.lnd.grpc.ListPeersResponse.class, lightpay.lnd.grpc.ListPeersResponse.Builder.class);
    }

    // Construct using lightpay.lnd.grpc.ListPeersResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getPeersFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      if (peersBuilder_ == null) {
        peers_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        peersBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return lightpay.lnd.grpc.Rpc.internal_static_lnrpc_ListPeersResponse_descriptor;
    }

    public lightpay.lnd.grpc.ListPeersResponse getDefaultInstanceForType() {
      return lightpay.lnd.grpc.ListPeersResponse.getDefaultInstance();
    }

    public lightpay.lnd.grpc.ListPeersResponse build() {
      lightpay.lnd.grpc.ListPeersResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public lightpay.lnd.grpc.ListPeersResponse buildPartial() {
      lightpay.lnd.grpc.ListPeersResponse result = new lightpay.lnd.grpc.ListPeersResponse(this);
      int from_bitField0_ = bitField0_;
      if (peersBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          peers_ = java.util.Collections.unmodifiableList(peers_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.peers_ = peers_;
      } else {
        result.peers_ = peersBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof lightpay.lnd.grpc.ListPeersResponse) {
        return mergeFrom((lightpay.lnd.grpc.ListPeersResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(lightpay.lnd.grpc.ListPeersResponse other) {
      if (other == lightpay.lnd.grpc.ListPeersResponse.getDefaultInstance()) return this;
      if (peersBuilder_ == null) {
        if (!other.peers_.isEmpty()) {
          if (peers_.isEmpty()) {
            peers_ = other.peers_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensurePeersIsMutable();
            peers_.addAll(other.peers_);
          }
          onChanged();
        }
      } else {
        if (!other.peers_.isEmpty()) {
          if (peersBuilder_.isEmpty()) {
            peersBuilder_.dispose();
            peersBuilder_ = null;
            peers_ = other.peers_;
            bitField0_ = (bitField0_ & ~0x00000001);
            peersBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getPeersFieldBuilder() : null;
          } else {
            peersBuilder_.addAllMessages(other.peers_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      lightpay.lnd.grpc.ListPeersResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (lightpay.lnd.grpc.ListPeersResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<lightpay.lnd.grpc.Peer> peers_ =
      java.util.Collections.emptyList();
    private void ensurePeersIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        peers_ = new java.util.ArrayList<lightpay.lnd.grpc.Peer>(peers_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        lightpay.lnd.grpc.Peer, lightpay.lnd.grpc.Peer.Builder, lightpay.lnd.grpc.PeerOrBuilder> peersBuilder_;

    /**
     * <pre>
     *&#47; The list of currently connected peers
     * </pre>
     *
     * <code>repeated .lnrpc.Peer peers = 1[json_name = "peers"];</code>
     */
    public java.util.List<lightpay.lnd.grpc.Peer> getPeersList() {
      if (peersBuilder_ == null) {
        return java.util.Collections.unmodifiableList(peers_);
      } else {
        return peersBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     *&#47; The list of currently connected peers
     * </pre>
     *
     * <code>repeated .lnrpc.Peer peers = 1[json_name = "peers"];</code>
     */
    public int getPeersCount() {
      if (peersBuilder_ == null) {
        return peers_.size();
      } else {
        return peersBuilder_.getCount();
      }
    }
    /**
     * <pre>
     *&#47; The list of currently connected peers
     * </pre>
     *
     * <code>repeated .lnrpc.Peer peers = 1[json_name = "peers"];</code>
     */
    public lightpay.lnd.grpc.Peer getPeers(int index) {
      if (peersBuilder_ == null) {
        return peers_.get(index);
      } else {
        return peersBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     *&#47; The list of currently connected peers
     * </pre>
     *
     * <code>repeated .lnrpc.Peer peers = 1[json_name = "peers"];</code>
     */
    public Builder setPeers(
        int index, lightpay.lnd.grpc.Peer value) {
      if (peersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePeersIsMutable();
        peers_.set(index, value);
        onChanged();
      } else {
        peersBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     *&#47; The list of currently connected peers
     * </pre>
     *
     * <code>repeated .lnrpc.Peer peers = 1[json_name = "peers"];</code>
     */
    public Builder setPeers(
        int index, lightpay.lnd.grpc.Peer.Builder builderForValue) {
      if (peersBuilder_ == null) {
        ensurePeersIsMutable();
        peers_.set(index, builderForValue.build());
        onChanged();
      } else {
        peersBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     *&#47; The list of currently connected peers
     * </pre>
     *
     * <code>repeated .lnrpc.Peer peers = 1[json_name = "peers"];</code>
     */
    public Builder addPeers(lightpay.lnd.grpc.Peer value) {
      if (peersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePeersIsMutable();
        peers_.add(value);
        onChanged();
      } else {
        peersBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     *&#47; The list of currently connected peers
     * </pre>
     *
     * <code>repeated .lnrpc.Peer peers = 1[json_name = "peers"];</code>
     */
    public Builder addPeers(
        int index, lightpay.lnd.grpc.Peer value) {
      if (peersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePeersIsMutable();
        peers_.add(index, value);
        onChanged();
      } else {
        peersBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     *&#47; The list of currently connected peers
     * </pre>
     *
     * <code>repeated .lnrpc.Peer peers = 1[json_name = "peers"];</code>
     */
    public Builder addPeers(
        lightpay.lnd.grpc.Peer.Builder builderForValue) {
      if (peersBuilder_ == null) {
        ensurePeersIsMutable();
        peers_.add(builderForValue.build());
        onChanged();
      } else {
        peersBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     *&#47; The list of currently connected peers
     * </pre>
     *
     * <code>repeated .lnrpc.Peer peers = 1[json_name = "peers"];</code>
     */
    public Builder addPeers(
        int index, lightpay.lnd.grpc.Peer.Builder builderForValue) {
      if (peersBuilder_ == null) {
        ensurePeersIsMutable();
        peers_.add(index, builderForValue.build());
        onChanged();
      } else {
        peersBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     *&#47; The list of currently connected peers
     * </pre>
     *
     * <code>repeated .lnrpc.Peer peers = 1[json_name = "peers"];</code>
     */
    public Builder addAllPeers(
        java.lang.Iterable<? extends lightpay.lnd.grpc.Peer> values) {
      if (peersBuilder_ == null) {
        ensurePeersIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, peers_);
        onChanged();
      } else {
        peersBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     *&#47; The list of currently connected peers
     * </pre>
     *
     * <code>repeated .lnrpc.Peer peers = 1[json_name = "peers"];</code>
     */
    public Builder clearPeers() {
      if (peersBuilder_ == null) {
        peers_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        peersBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     *&#47; The list of currently connected peers
     * </pre>
     *
     * <code>repeated .lnrpc.Peer peers = 1[json_name = "peers"];</code>
     */
    public Builder removePeers(int index) {
      if (peersBuilder_ == null) {
        ensurePeersIsMutable();
        peers_.remove(index);
        onChanged();
      } else {
        peersBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     *&#47; The list of currently connected peers
     * </pre>
     *
     * <code>repeated .lnrpc.Peer peers = 1[json_name = "peers"];</code>
     */
    public lightpay.lnd.grpc.Peer.Builder getPeersBuilder(
        int index) {
      return getPeersFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     *&#47; The list of currently connected peers
     * </pre>
     *
     * <code>repeated .lnrpc.Peer peers = 1[json_name = "peers"];</code>
     */
    public lightpay.lnd.grpc.PeerOrBuilder getPeersOrBuilder(
        int index) {
      if (peersBuilder_ == null) {
        return peers_.get(index);  } else {
        return peersBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     *&#47; The list of currently connected peers
     * </pre>
     *
     * <code>repeated .lnrpc.Peer peers = 1[json_name = "peers"];</code>
     */
    public java.util.List<? extends lightpay.lnd.grpc.PeerOrBuilder> 
         getPeersOrBuilderList() {
      if (peersBuilder_ != null) {
        return peersBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(peers_);
      }
    }
    /**
     * <pre>
     *&#47; The list of currently connected peers
     * </pre>
     *
     * <code>repeated .lnrpc.Peer peers = 1[json_name = "peers"];</code>
     */
    public lightpay.lnd.grpc.Peer.Builder addPeersBuilder() {
      return getPeersFieldBuilder().addBuilder(
          lightpay.lnd.grpc.Peer.getDefaultInstance());
    }
    /**
     * <pre>
     *&#47; The list of currently connected peers
     * </pre>
     *
     * <code>repeated .lnrpc.Peer peers = 1[json_name = "peers"];</code>
     */
    public lightpay.lnd.grpc.Peer.Builder addPeersBuilder(
        int index) {
      return getPeersFieldBuilder().addBuilder(
          index, lightpay.lnd.grpc.Peer.getDefaultInstance());
    }
    /**
     * <pre>
     *&#47; The list of currently connected peers
     * </pre>
     *
     * <code>repeated .lnrpc.Peer peers = 1[json_name = "peers"];</code>
     */
    public java.util.List<lightpay.lnd.grpc.Peer.Builder> 
         getPeersBuilderList() {
      return getPeersFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        lightpay.lnd.grpc.Peer, lightpay.lnd.grpc.Peer.Builder, lightpay.lnd.grpc.PeerOrBuilder> 
        getPeersFieldBuilder() {
      if (peersBuilder_ == null) {
        peersBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            lightpay.lnd.grpc.Peer, lightpay.lnd.grpc.Peer.Builder, lightpay.lnd.grpc.PeerOrBuilder>(
                peers_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        peers_ = null;
      }
      return peersBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:lnrpc.ListPeersResponse)
  }

  // @@protoc_insertion_point(class_scope:lnrpc.ListPeersResponse)
  private static final lightpay.lnd.grpc.ListPeersResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new lightpay.lnd.grpc.ListPeersResponse();
  }

  public static lightpay.lnd.grpc.ListPeersResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ListPeersResponse>
      PARSER = new com.google.protobuf.AbstractParser<ListPeersResponse>() {
    public ListPeersResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ListPeersResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ListPeersResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ListPeersResponse> getParserForType() {
    return PARSER;
  }

  public lightpay.lnd.grpc.ListPeersResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

