// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc.proto

package lightpay.lnd.grpc;

/**
 * Protobuf type {@code lnrpc.NetworkInfo}
 */
public  final class NetworkInfo extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:lnrpc.NetworkInfo)
    NetworkInfoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use NetworkInfo.newBuilder() to construct.
  private NetworkInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private NetworkInfo() {
    graphDiameter_ = 0;
    avgOutDegree_ = 0D;
    maxOutDegree_ = 0;
    numNodes_ = 0;
    numChannels_ = 0;
    totalNetworkCapacity_ = 0L;
    avgChannelSize_ = 0D;
    minChannelSize_ = 0L;
    maxChannelSize_ = 0L;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private NetworkInfo(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            graphDiameter_ = input.readUInt32();
            break;
          }
          case 17: {

            avgOutDegree_ = input.readDouble();
            break;
          }
          case 24: {

            maxOutDegree_ = input.readUInt32();
            break;
          }
          case 32: {

            numNodes_ = input.readUInt32();
            break;
          }
          case 40: {

            numChannels_ = input.readUInt32();
            break;
          }
          case 48: {

            totalNetworkCapacity_ = input.readInt64();
            break;
          }
          case 57: {

            avgChannelSize_ = input.readDouble();
            break;
          }
          case 64: {

            minChannelSize_ = input.readInt64();
            break;
          }
          case 72: {

            maxChannelSize_ = input.readInt64();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return lightpay.lnd.grpc.Rpc.internal_static_lnrpc_NetworkInfo_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return lightpay.lnd.grpc.Rpc.internal_static_lnrpc_NetworkInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            lightpay.lnd.grpc.NetworkInfo.class, lightpay.lnd.grpc.NetworkInfo.Builder.class);
  }

  public static final int GRAPH_DIAMETER_FIELD_NUMBER = 1;
  private int graphDiameter_;
  /**
   * <code>uint32 graph_diameter = 1[json_name = "graph_diameter"];</code>
   */
  public int getGraphDiameter() {
    return graphDiameter_;
  }

  public static final int AVG_OUT_DEGREE_FIELD_NUMBER = 2;
  private double avgOutDegree_;
  /**
   * <code>double avg_out_degree = 2[json_name = "avg_out_degree"];</code>
   */
  public double getAvgOutDegree() {
    return avgOutDegree_;
  }

  public static final int MAX_OUT_DEGREE_FIELD_NUMBER = 3;
  private int maxOutDegree_;
  /**
   * <code>uint32 max_out_degree = 3[json_name = "max_out_degree"];</code>
   */
  public int getMaxOutDegree() {
    return maxOutDegree_;
  }

  public static final int NUM_NODES_FIELD_NUMBER = 4;
  private int numNodes_;
  /**
   * <code>uint32 num_nodes = 4[json_name = "num_nodes"];</code>
   */
  public int getNumNodes() {
    return numNodes_;
  }

  public static final int NUM_CHANNELS_FIELD_NUMBER = 5;
  private int numChannels_;
  /**
   * <code>uint32 num_channels = 5[json_name = "num_channels"];</code>
   */
  public int getNumChannels() {
    return numChannels_;
  }

  public static final int TOTAL_NETWORK_CAPACITY_FIELD_NUMBER = 6;
  private long totalNetworkCapacity_;
  /**
   * <code>int64 total_network_capacity = 6[json_name = "total_network_capacity"];</code>
   */
  public long getTotalNetworkCapacity() {
    return totalNetworkCapacity_;
  }

  public static final int AVG_CHANNEL_SIZE_FIELD_NUMBER = 7;
  private double avgChannelSize_;
  /**
   * <code>double avg_channel_size = 7[json_name = "avg_channel_size"];</code>
   */
  public double getAvgChannelSize() {
    return avgChannelSize_;
  }

  public static final int MIN_CHANNEL_SIZE_FIELD_NUMBER = 8;
  private long minChannelSize_;
  /**
   * <code>int64 min_channel_size = 8[json_name = "min_channel_size"];</code>
   */
  public long getMinChannelSize() {
    return minChannelSize_;
  }

  public static final int MAX_CHANNEL_SIZE_FIELD_NUMBER = 9;
  private long maxChannelSize_;
  /**
   * <code>int64 max_channel_size = 9[json_name = "max_channel_size"];</code>
   */
  public long getMaxChannelSize() {
    return maxChannelSize_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (graphDiameter_ != 0) {
      output.writeUInt32(1, graphDiameter_);
    }
    if (avgOutDegree_ != 0D) {
      output.writeDouble(2, avgOutDegree_);
    }
    if (maxOutDegree_ != 0) {
      output.writeUInt32(3, maxOutDegree_);
    }
    if (numNodes_ != 0) {
      output.writeUInt32(4, numNodes_);
    }
    if (numChannels_ != 0) {
      output.writeUInt32(5, numChannels_);
    }
    if (totalNetworkCapacity_ != 0L) {
      output.writeInt64(6, totalNetworkCapacity_);
    }
    if (avgChannelSize_ != 0D) {
      output.writeDouble(7, avgChannelSize_);
    }
    if (minChannelSize_ != 0L) {
      output.writeInt64(8, minChannelSize_);
    }
    if (maxChannelSize_ != 0L) {
      output.writeInt64(9, maxChannelSize_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (graphDiameter_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(1, graphDiameter_);
    }
    if (avgOutDegree_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(2, avgOutDegree_);
    }
    if (maxOutDegree_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(3, maxOutDegree_);
    }
    if (numNodes_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(4, numNodes_);
    }
    if (numChannels_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(5, numChannels_);
    }
    if (totalNetworkCapacity_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(6, totalNetworkCapacity_);
    }
    if (avgChannelSize_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(7, avgChannelSize_);
    }
    if (minChannelSize_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(8, minChannelSize_);
    }
    if (maxChannelSize_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(9, maxChannelSize_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof lightpay.lnd.grpc.NetworkInfo)) {
      return super.equals(obj);
    }
    lightpay.lnd.grpc.NetworkInfo other = (lightpay.lnd.grpc.NetworkInfo) obj;

    boolean result = true;
    result = result && (getGraphDiameter()
        == other.getGraphDiameter());
    result = result && (
        java.lang.Double.doubleToLongBits(getAvgOutDegree())
        == java.lang.Double.doubleToLongBits(
            other.getAvgOutDegree()));
    result = result && (getMaxOutDegree()
        == other.getMaxOutDegree());
    result = result && (getNumNodes()
        == other.getNumNodes());
    result = result && (getNumChannels()
        == other.getNumChannels());
    result = result && (getTotalNetworkCapacity()
        == other.getTotalNetworkCapacity());
    result = result && (
        java.lang.Double.doubleToLongBits(getAvgChannelSize())
        == java.lang.Double.doubleToLongBits(
            other.getAvgChannelSize()));
    result = result && (getMinChannelSize()
        == other.getMinChannelSize());
    result = result && (getMaxChannelSize()
        == other.getMaxChannelSize());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + GRAPH_DIAMETER_FIELD_NUMBER;
    hash = (53 * hash) + getGraphDiameter();
    hash = (37 * hash) + AVG_OUT_DEGREE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getAvgOutDegree()));
    hash = (37 * hash) + MAX_OUT_DEGREE_FIELD_NUMBER;
    hash = (53 * hash) + getMaxOutDegree();
    hash = (37 * hash) + NUM_NODES_FIELD_NUMBER;
    hash = (53 * hash) + getNumNodes();
    hash = (37 * hash) + NUM_CHANNELS_FIELD_NUMBER;
    hash = (53 * hash) + getNumChannels();
    hash = (37 * hash) + TOTAL_NETWORK_CAPACITY_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTotalNetworkCapacity());
    hash = (37 * hash) + AVG_CHANNEL_SIZE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getAvgChannelSize()));
    hash = (37 * hash) + MIN_CHANNEL_SIZE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getMinChannelSize());
    hash = (37 * hash) + MAX_CHANNEL_SIZE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getMaxChannelSize());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static lightpay.lnd.grpc.NetworkInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static lightpay.lnd.grpc.NetworkInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static lightpay.lnd.grpc.NetworkInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static lightpay.lnd.grpc.NetworkInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static lightpay.lnd.grpc.NetworkInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static lightpay.lnd.grpc.NetworkInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static lightpay.lnd.grpc.NetworkInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static lightpay.lnd.grpc.NetworkInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static lightpay.lnd.grpc.NetworkInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static lightpay.lnd.grpc.NetworkInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static lightpay.lnd.grpc.NetworkInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static lightpay.lnd.grpc.NetworkInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(lightpay.lnd.grpc.NetworkInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code lnrpc.NetworkInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:lnrpc.NetworkInfo)
      lightpay.lnd.grpc.NetworkInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return lightpay.lnd.grpc.Rpc.internal_static_lnrpc_NetworkInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return lightpay.lnd.grpc.Rpc.internal_static_lnrpc_NetworkInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              lightpay.lnd.grpc.NetworkInfo.class, lightpay.lnd.grpc.NetworkInfo.Builder.class);
    }

    // Construct using lightpay.lnd.grpc.NetworkInfo.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      graphDiameter_ = 0;

      avgOutDegree_ = 0D;

      maxOutDegree_ = 0;

      numNodes_ = 0;

      numChannels_ = 0;

      totalNetworkCapacity_ = 0L;

      avgChannelSize_ = 0D;

      minChannelSize_ = 0L;

      maxChannelSize_ = 0L;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return lightpay.lnd.grpc.Rpc.internal_static_lnrpc_NetworkInfo_descriptor;
    }

    public lightpay.lnd.grpc.NetworkInfo getDefaultInstanceForType() {
      return lightpay.lnd.grpc.NetworkInfo.getDefaultInstance();
    }

    public lightpay.lnd.grpc.NetworkInfo build() {
      lightpay.lnd.grpc.NetworkInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public lightpay.lnd.grpc.NetworkInfo buildPartial() {
      lightpay.lnd.grpc.NetworkInfo result = new lightpay.lnd.grpc.NetworkInfo(this);
      result.graphDiameter_ = graphDiameter_;
      result.avgOutDegree_ = avgOutDegree_;
      result.maxOutDegree_ = maxOutDegree_;
      result.numNodes_ = numNodes_;
      result.numChannels_ = numChannels_;
      result.totalNetworkCapacity_ = totalNetworkCapacity_;
      result.avgChannelSize_ = avgChannelSize_;
      result.minChannelSize_ = minChannelSize_;
      result.maxChannelSize_ = maxChannelSize_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof lightpay.lnd.grpc.NetworkInfo) {
        return mergeFrom((lightpay.lnd.grpc.NetworkInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(lightpay.lnd.grpc.NetworkInfo other) {
      if (other == lightpay.lnd.grpc.NetworkInfo.getDefaultInstance()) return this;
      if (other.getGraphDiameter() != 0) {
        setGraphDiameter(other.getGraphDiameter());
      }
      if (other.getAvgOutDegree() != 0D) {
        setAvgOutDegree(other.getAvgOutDegree());
      }
      if (other.getMaxOutDegree() != 0) {
        setMaxOutDegree(other.getMaxOutDegree());
      }
      if (other.getNumNodes() != 0) {
        setNumNodes(other.getNumNodes());
      }
      if (other.getNumChannels() != 0) {
        setNumChannels(other.getNumChannels());
      }
      if (other.getTotalNetworkCapacity() != 0L) {
        setTotalNetworkCapacity(other.getTotalNetworkCapacity());
      }
      if (other.getAvgChannelSize() != 0D) {
        setAvgChannelSize(other.getAvgChannelSize());
      }
      if (other.getMinChannelSize() != 0L) {
        setMinChannelSize(other.getMinChannelSize());
      }
      if (other.getMaxChannelSize() != 0L) {
        setMaxChannelSize(other.getMaxChannelSize());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      lightpay.lnd.grpc.NetworkInfo parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (lightpay.lnd.grpc.NetworkInfo) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int graphDiameter_ ;
    /**
     * <code>uint32 graph_diameter = 1[json_name = "graph_diameter"];</code>
     */
    public int getGraphDiameter() {
      return graphDiameter_;
    }
    /**
     * <code>uint32 graph_diameter = 1[json_name = "graph_diameter"];</code>
     */
    public Builder setGraphDiameter(int value) {
      
      graphDiameter_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 graph_diameter = 1[json_name = "graph_diameter"];</code>
     */
    public Builder clearGraphDiameter() {
      
      graphDiameter_ = 0;
      onChanged();
      return this;
    }

    private double avgOutDegree_ ;
    /**
     * <code>double avg_out_degree = 2[json_name = "avg_out_degree"];</code>
     */
    public double getAvgOutDegree() {
      return avgOutDegree_;
    }
    /**
     * <code>double avg_out_degree = 2[json_name = "avg_out_degree"];</code>
     */
    public Builder setAvgOutDegree(double value) {
      
      avgOutDegree_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double avg_out_degree = 2[json_name = "avg_out_degree"];</code>
     */
    public Builder clearAvgOutDegree() {
      
      avgOutDegree_ = 0D;
      onChanged();
      return this;
    }

    private int maxOutDegree_ ;
    /**
     * <code>uint32 max_out_degree = 3[json_name = "max_out_degree"];</code>
     */
    public int getMaxOutDegree() {
      return maxOutDegree_;
    }
    /**
     * <code>uint32 max_out_degree = 3[json_name = "max_out_degree"];</code>
     */
    public Builder setMaxOutDegree(int value) {
      
      maxOutDegree_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 max_out_degree = 3[json_name = "max_out_degree"];</code>
     */
    public Builder clearMaxOutDegree() {
      
      maxOutDegree_ = 0;
      onChanged();
      return this;
    }

    private int numNodes_ ;
    /**
     * <code>uint32 num_nodes = 4[json_name = "num_nodes"];</code>
     */
    public int getNumNodes() {
      return numNodes_;
    }
    /**
     * <code>uint32 num_nodes = 4[json_name = "num_nodes"];</code>
     */
    public Builder setNumNodes(int value) {
      
      numNodes_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 num_nodes = 4[json_name = "num_nodes"];</code>
     */
    public Builder clearNumNodes() {
      
      numNodes_ = 0;
      onChanged();
      return this;
    }

    private int numChannels_ ;
    /**
     * <code>uint32 num_channels = 5[json_name = "num_channels"];</code>
     */
    public int getNumChannels() {
      return numChannels_;
    }
    /**
     * <code>uint32 num_channels = 5[json_name = "num_channels"];</code>
     */
    public Builder setNumChannels(int value) {
      
      numChannels_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 num_channels = 5[json_name = "num_channels"];</code>
     */
    public Builder clearNumChannels() {
      
      numChannels_ = 0;
      onChanged();
      return this;
    }

    private long totalNetworkCapacity_ ;
    /**
     * <code>int64 total_network_capacity = 6[json_name = "total_network_capacity"];</code>
     */
    public long getTotalNetworkCapacity() {
      return totalNetworkCapacity_;
    }
    /**
     * <code>int64 total_network_capacity = 6[json_name = "total_network_capacity"];</code>
     */
    public Builder setTotalNetworkCapacity(long value) {
      
      totalNetworkCapacity_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 total_network_capacity = 6[json_name = "total_network_capacity"];</code>
     */
    public Builder clearTotalNetworkCapacity() {
      
      totalNetworkCapacity_ = 0L;
      onChanged();
      return this;
    }

    private double avgChannelSize_ ;
    /**
     * <code>double avg_channel_size = 7[json_name = "avg_channel_size"];</code>
     */
    public double getAvgChannelSize() {
      return avgChannelSize_;
    }
    /**
     * <code>double avg_channel_size = 7[json_name = "avg_channel_size"];</code>
     */
    public Builder setAvgChannelSize(double value) {
      
      avgChannelSize_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double avg_channel_size = 7[json_name = "avg_channel_size"];</code>
     */
    public Builder clearAvgChannelSize() {
      
      avgChannelSize_ = 0D;
      onChanged();
      return this;
    }

    private long minChannelSize_ ;
    /**
     * <code>int64 min_channel_size = 8[json_name = "min_channel_size"];</code>
     */
    public long getMinChannelSize() {
      return minChannelSize_;
    }
    /**
     * <code>int64 min_channel_size = 8[json_name = "min_channel_size"];</code>
     */
    public Builder setMinChannelSize(long value) {
      
      minChannelSize_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 min_channel_size = 8[json_name = "min_channel_size"];</code>
     */
    public Builder clearMinChannelSize() {
      
      minChannelSize_ = 0L;
      onChanged();
      return this;
    }

    private long maxChannelSize_ ;
    /**
     * <code>int64 max_channel_size = 9[json_name = "max_channel_size"];</code>
     */
    public long getMaxChannelSize() {
      return maxChannelSize_;
    }
    /**
     * <code>int64 max_channel_size = 9[json_name = "max_channel_size"];</code>
     */
    public Builder setMaxChannelSize(long value) {
      
      maxChannelSize_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 max_channel_size = 9[json_name = "max_channel_size"];</code>
     */
    public Builder clearMaxChannelSize() {
      
      maxChannelSize_ = 0L;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:lnrpc.NetworkInfo)
  }

  // @@protoc_insertion_point(class_scope:lnrpc.NetworkInfo)
  private static final lightpay.lnd.grpc.NetworkInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new lightpay.lnd.grpc.NetworkInfo();
  }

  public static lightpay.lnd.grpc.NetworkInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<NetworkInfo>
      PARSER = new com.google.protobuf.AbstractParser<NetworkInfo>() {
    public NetworkInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new NetworkInfo(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<NetworkInfo> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<NetworkInfo> getParserForType() {
    return PARSER;
  }

  public lightpay.lnd.grpc.NetworkInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

