// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc.proto

package lightpay.lnd.grpc;

public interface NewAddressResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:lnrpc.NewAddressResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *&#47; The newly generated wallet address
   * </pre>
   *
   * <code>string address = 1[json_name = "address"];</code>
   */
  java.lang.String getAddress();
  /**
   * <pre>
   *&#47; The newly generated wallet address
   * </pre>
   *
   * <code>string address = 1[json_name = "address"];</code>
   */
  com.google.protobuf.ByteString
      getAddressBytes();
}
