// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc.proto

package lightpay.lnd.grpc;

/**
 * Protobuf type {@code lnrpc.PaymentHash}
 */
public  final class PaymentHash extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:lnrpc.PaymentHash)
    PaymentHashOrBuilder {
private static final long serialVersionUID = 0L;
  // Use PaymentHash.newBuilder() to construct.
  private PaymentHash(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private PaymentHash() {
    rHashStr_ = "";
    rHash_ = com.google.protobuf.ByteString.EMPTY;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private PaymentHash(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            rHashStr_ = s;
            break;
          }
          case 18: {

            rHash_ = input.readBytes();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return lightpay.lnd.grpc.Rpc.internal_static_lnrpc_PaymentHash_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return lightpay.lnd.grpc.Rpc.internal_static_lnrpc_PaymentHash_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            lightpay.lnd.grpc.PaymentHash.class, lightpay.lnd.grpc.PaymentHash.Builder.class);
  }

  public static final int R_HASH_STR_FIELD_NUMBER = 1;
  private volatile java.lang.Object rHashStr_;
  /**
   * <pre>
   **
   *The hex-encoded payment hash of the invoice to be looked up. The passed
   *payment hash must be exactly 32 bytes, otherwise an error is returned.
   * </pre>
   *
   * <code>string r_hash_str = 1[json_name = "r_hash_str"];</code>
   */
  public java.lang.String getRHashStr() {
    java.lang.Object ref = rHashStr_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      rHashStr_ = s;
      return s;
    }
  }
  /**
   * <pre>
   **
   *The hex-encoded payment hash of the invoice to be looked up. The passed
   *payment hash must be exactly 32 bytes, otherwise an error is returned.
   * </pre>
   *
   * <code>string r_hash_str = 1[json_name = "r_hash_str"];</code>
   */
  public com.google.protobuf.ByteString
      getRHashStrBytes() {
    java.lang.Object ref = rHashStr_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      rHashStr_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int R_HASH_FIELD_NUMBER = 2;
  private com.google.protobuf.ByteString rHash_;
  /**
   * <pre>
   *&#47; The payment hash of the invoice to be looked up.
   * </pre>
   *
   * <code>bytes r_hash = 2[json_name = "r_hash"];</code>
   */
  public com.google.protobuf.ByteString getRHash() {
    return rHash_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getRHashStrBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, rHashStr_);
    }
    if (!rHash_.isEmpty()) {
      output.writeBytes(2, rHash_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getRHashStrBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, rHashStr_);
    }
    if (!rHash_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(2, rHash_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof lightpay.lnd.grpc.PaymentHash)) {
      return super.equals(obj);
    }
    lightpay.lnd.grpc.PaymentHash other = (lightpay.lnd.grpc.PaymentHash) obj;

    boolean result = true;
    result = result && getRHashStr()
        .equals(other.getRHashStr());
    result = result && getRHash()
        .equals(other.getRHash());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + R_HASH_STR_FIELD_NUMBER;
    hash = (53 * hash) + getRHashStr().hashCode();
    hash = (37 * hash) + R_HASH_FIELD_NUMBER;
    hash = (53 * hash) + getRHash().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static lightpay.lnd.grpc.PaymentHash parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static lightpay.lnd.grpc.PaymentHash parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static lightpay.lnd.grpc.PaymentHash parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static lightpay.lnd.grpc.PaymentHash parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static lightpay.lnd.grpc.PaymentHash parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static lightpay.lnd.grpc.PaymentHash parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static lightpay.lnd.grpc.PaymentHash parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static lightpay.lnd.grpc.PaymentHash parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static lightpay.lnd.grpc.PaymentHash parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static lightpay.lnd.grpc.PaymentHash parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static lightpay.lnd.grpc.PaymentHash parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static lightpay.lnd.grpc.PaymentHash parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(lightpay.lnd.grpc.PaymentHash prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code lnrpc.PaymentHash}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:lnrpc.PaymentHash)
      lightpay.lnd.grpc.PaymentHashOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return lightpay.lnd.grpc.Rpc.internal_static_lnrpc_PaymentHash_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return lightpay.lnd.grpc.Rpc.internal_static_lnrpc_PaymentHash_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              lightpay.lnd.grpc.PaymentHash.class, lightpay.lnd.grpc.PaymentHash.Builder.class);
    }

    // Construct using lightpay.lnd.grpc.PaymentHash.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      rHashStr_ = "";

      rHash_ = com.google.protobuf.ByteString.EMPTY;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return lightpay.lnd.grpc.Rpc.internal_static_lnrpc_PaymentHash_descriptor;
    }

    public lightpay.lnd.grpc.PaymentHash getDefaultInstanceForType() {
      return lightpay.lnd.grpc.PaymentHash.getDefaultInstance();
    }

    public lightpay.lnd.grpc.PaymentHash build() {
      lightpay.lnd.grpc.PaymentHash result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public lightpay.lnd.grpc.PaymentHash buildPartial() {
      lightpay.lnd.grpc.PaymentHash result = new lightpay.lnd.grpc.PaymentHash(this);
      result.rHashStr_ = rHashStr_;
      result.rHash_ = rHash_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof lightpay.lnd.grpc.PaymentHash) {
        return mergeFrom((lightpay.lnd.grpc.PaymentHash)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(lightpay.lnd.grpc.PaymentHash other) {
      if (other == lightpay.lnd.grpc.PaymentHash.getDefaultInstance()) return this;
      if (!other.getRHashStr().isEmpty()) {
        rHashStr_ = other.rHashStr_;
        onChanged();
      }
      if (other.getRHash() != com.google.protobuf.ByteString.EMPTY) {
        setRHash(other.getRHash());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      lightpay.lnd.grpc.PaymentHash parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (lightpay.lnd.grpc.PaymentHash) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object rHashStr_ = "";
    /**
     * <pre>
     **
     *The hex-encoded payment hash of the invoice to be looked up. The passed
     *payment hash must be exactly 32 bytes, otherwise an error is returned.
     * </pre>
     *
     * <code>string r_hash_str = 1[json_name = "r_hash_str"];</code>
     */
    public java.lang.String getRHashStr() {
      java.lang.Object ref = rHashStr_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        rHashStr_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     **
     *The hex-encoded payment hash of the invoice to be looked up. The passed
     *payment hash must be exactly 32 bytes, otherwise an error is returned.
     * </pre>
     *
     * <code>string r_hash_str = 1[json_name = "r_hash_str"];</code>
     */
    public com.google.protobuf.ByteString
        getRHashStrBytes() {
      java.lang.Object ref = rHashStr_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        rHashStr_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     **
     *The hex-encoded payment hash of the invoice to be looked up. The passed
     *payment hash must be exactly 32 bytes, otherwise an error is returned.
     * </pre>
     *
     * <code>string r_hash_str = 1[json_name = "r_hash_str"];</code>
     */
    public Builder setRHashStr(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      rHashStr_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     **
     *The hex-encoded payment hash of the invoice to be looked up. The passed
     *payment hash must be exactly 32 bytes, otherwise an error is returned.
     * </pre>
     *
     * <code>string r_hash_str = 1[json_name = "r_hash_str"];</code>
     */
    public Builder clearRHashStr() {
      
      rHashStr_ = getDefaultInstance().getRHashStr();
      onChanged();
      return this;
    }
    /**
     * <pre>
     **
     *The hex-encoded payment hash of the invoice to be looked up. The passed
     *payment hash must be exactly 32 bytes, otherwise an error is returned.
     * </pre>
     *
     * <code>string r_hash_str = 1[json_name = "r_hash_str"];</code>
     */
    public Builder setRHashStrBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      rHashStr_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString rHash_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     *&#47; The payment hash of the invoice to be looked up.
     * </pre>
     *
     * <code>bytes r_hash = 2[json_name = "r_hash"];</code>
     */
    public com.google.protobuf.ByteString getRHash() {
      return rHash_;
    }
    /**
     * <pre>
     *&#47; The payment hash of the invoice to be looked up.
     * </pre>
     *
     * <code>bytes r_hash = 2[json_name = "r_hash"];</code>
     */
    public Builder setRHash(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      rHash_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *&#47; The payment hash of the invoice to be looked up.
     * </pre>
     *
     * <code>bytes r_hash = 2[json_name = "r_hash"];</code>
     */
    public Builder clearRHash() {
      
      rHash_ = getDefaultInstance().getRHash();
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:lnrpc.PaymentHash)
  }

  // @@protoc_insertion_point(class_scope:lnrpc.PaymentHash)
  private static final lightpay.lnd.grpc.PaymentHash DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new lightpay.lnd.grpc.PaymentHash();
  }

  public static lightpay.lnd.grpc.PaymentHash getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PaymentHash>
      PARSER = new com.google.protobuf.AbstractParser<PaymentHash>() {
    public PaymentHash parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new PaymentHash(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<PaymentHash> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PaymentHash> getParserForType() {
    return PARSER;
  }

  public lightpay.lnd.grpc.PaymentHash getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

