// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc.proto

package lightpay.lnd.grpc;

public final class Rpc {
  private Rpc() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_GenSeedRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_GenSeedRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_GenSeedResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_GenSeedResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_InitWalletRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_InitWalletRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_InitWalletResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_InitWalletResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_UnlockWalletRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_UnlockWalletRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_UnlockWalletResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_UnlockWalletResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_Transaction_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_Transaction_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_GetTransactionsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_GetTransactionsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_TransactionDetails_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_TransactionDetails_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_SendRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_SendRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_SendResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_SendResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_ChannelPoint_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_ChannelPoint_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_LightningAddress_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_LightningAddress_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_SendManyRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_SendManyRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_SendManyRequest_AddrToAmountEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_SendManyRequest_AddrToAmountEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_SendManyResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_SendManyResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_SendCoinsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_SendCoinsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_SendCoinsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_SendCoinsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_NewAddressRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_NewAddressRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_NewWitnessAddressRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_NewWitnessAddressRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_NewAddressResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_NewAddressResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_SignMessageRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_SignMessageRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_SignMessageResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_SignMessageResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_VerifyMessageRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_VerifyMessageRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_VerifyMessageResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_VerifyMessageResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_ConnectPeerRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_ConnectPeerRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_ConnectPeerResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_ConnectPeerResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_DisconnectPeerRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_DisconnectPeerRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_DisconnectPeerResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_DisconnectPeerResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_HTLC_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_HTLC_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_Channel_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_Channel_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_ListChannelsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_ListChannelsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_ListChannelsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_ListChannelsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_Peer_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_Peer_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_ListPeersRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_ListPeersRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_ListPeersResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_ListPeersResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_GetInfoRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_GetInfoRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_GetInfoResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_GetInfoResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_ConfirmationUpdate_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_ConfirmationUpdate_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_ChannelOpenUpdate_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_ChannelOpenUpdate_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_ChannelCloseUpdate_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_ChannelCloseUpdate_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_CloseChannelRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_CloseChannelRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_CloseStatusUpdate_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_CloseStatusUpdate_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_PendingUpdate_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_PendingUpdate_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_OpenChannelRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_OpenChannelRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_OpenStatusUpdate_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_OpenStatusUpdate_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_PendingHTLC_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_PendingHTLC_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_PendingChannelsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_PendingChannelsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_PendingChannelsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_PendingChannelsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_PendingChannelsResponse_PendingChannel_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_PendingChannelsResponse_PendingChannel_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_PendingChannelsResponse_PendingOpenChannel_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_PendingChannelsResponse_PendingOpenChannel_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_PendingChannelsResponse_ClosedChannel_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_PendingChannelsResponse_ClosedChannel_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_PendingChannelsResponse_ForceClosedChannel_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_PendingChannelsResponse_ForceClosedChannel_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_WalletBalanceRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_WalletBalanceRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_WalletBalanceResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_WalletBalanceResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_ChannelBalanceRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_ChannelBalanceRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_ChannelBalanceResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_ChannelBalanceResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_QueryRoutesRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_QueryRoutesRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_QueryRoutesResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_QueryRoutesResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_Hop_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_Hop_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_Route_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_Route_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_NodeInfoRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_NodeInfoRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_NodeInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_NodeInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_LightningNode_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_LightningNode_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_NodeAddress_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_NodeAddress_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_RoutingPolicy_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_RoutingPolicy_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_ChannelEdge_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_ChannelEdge_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_ChannelGraphRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_ChannelGraphRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_ChannelGraph_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_ChannelGraph_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_ChanInfoRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_ChanInfoRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_NetworkInfoRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_NetworkInfoRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_NetworkInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_NetworkInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_StopRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_StopRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_StopResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_StopResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_GraphTopologySubscription_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_GraphTopologySubscription_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_GraphTopologyUpdate_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_GraphTopologyUpdate_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_NodeUpdate_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_NodeUpdate_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_ChannelEdgeUpdate_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_ChannelEdgeUpdate_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_ClosedChannelUpdate_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_ClosedChannelUpdate_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_HopHint_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_HopHint_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_RouteHint_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_RouteHint_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_Invoice_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_Invoice_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_AddInvoiceResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_AddInvoiceResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_PaymentHash_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_PaymentHash_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_ListInvoiceRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_ListInvoiceRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_ListInvoiceResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_ListInvoiceResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_InvoiceSubscription_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_InvoiceSubscription_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_Payment_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_Payment_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_ListPaymentsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_ListPaymentsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_ListPaymentsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_ListPaymentsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_DeleteAllPaymentsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_DeleteAllPaymentsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_DeleteAllPaymentsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_DeleteAllPaymentsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_DebugLevelRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_DebugLevelRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_DebugLevelResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_DebugLevelResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_PayReqString_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_PayReqString_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_PayReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_PayReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_FeeReportRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_FeeReportRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_ChannelFeeReport_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_ChannelFeeReport_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_FeeReportResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_FeeReportResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_PolicyUpdateRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_PolicyUpdateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_PolicyUpdateResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_PolicyUpdateResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_ForwardingHistoryRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_ForwardingHistoryRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_ForwardingEvent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_ForwardingEvent_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_ForwardingHistoryResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_ForwardingHistoryResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\trpc.proto\022\005lnrpc\032\034google/api/annotatio" +
      "ns.proto\"A\n\016GenSeedRequest\022\031\n\021aezeed_pas" +
      "sphrase\030\001 \001(\014\022\024\n\014seed_entropy\030\002 \001(\014\"H\n\017G" +
      "enSeedResponse\022\034\n\024cipher_seed_mnemonic\030\001" +
      " \003(\t\022\027\n\017enciphered_seed\030\002 \001(\014\"e\n\021InitWal" +
      "letRequest\022\027\n\017wallet_password\030\001 \001(\014\022\034\n\024c" +
      "ipher_seed_mnemonic\030\002 \003(\t\022\031\n\021aezeed_pass" +
      "phrase\030\003 \001(\014\"\024\n\022InitWalletResponse\".\n\023Un" +
      "lockWalletRequest\022\027\n\017wallet_password\030\001 \001" +
      "(\014\"\026\n\024UnlockWalletResponse\"\231\002\n\013Transacti" +
      "on\022\030\n\007tx_hash\030\001 \001(\tR\007tx_hash\022\026\n\006amount\030\002" +
      " \001(\003R\006amount\022,\n\021num_confirmations\030\003 \001(\005R" +
      "\021num_confirmations\022\036\n\nblock_hash\030\004 \001(\tR\n" +
      "block_hash\022\"\n\014block_height\030\005 \001(\005R\014block_" +
      "height\022\036\n\ntime_stamp\030\006 \001(\003R\ntime_stamp\022\036" +
      "\n\ntotal_fees\030\007 \001(\003R\ntotal_fees\022&\n\016dest_a" +
      "ddresses\030\010 \003(\tR\016dest_addresses\"\030\n\026GetTra" +
      "nsactionsRequest\"L\n\022TransactionDetails\0226" +
      "\n\014transactions\030\001 \003(\0132\022.lnrpc.Transaction" +
      "R\014transactions\"\243\001\n\013SendRequest\022\014\n\004dest\030\001" +
      " \001(\014\022\023\n\013dest_string\030\002 \001(\t\022\013\n\003amt\030\003 \001(\003\022\024" +
      "\n\014payment_hash\030\004 \001(\014\022\033\n\023payment_hash_str" +
      "ing\030\005 \001(\t\022\027\n\017payment_request\030\006 \001(\t\022\030\n\020fi" +
      "nal_cltv_delta\030\007 \001(\005\"\224\001\n\014SendResponse\022$\n" +
      "\rpayment_error\030\001 \001(\tR\rpayment_error\022*\n\020p" +
      "ayment_preimage\030\002 \001(\014R\020payment_preimage\022" +
      "2\n\rpayment_route\030\003 \001(\0132\014.lnrpc.RouteR\rpa" +
      "yment_route\"\242\001\n\014ChannelPoint\0220\n\022funding_" +
      "txid_bytes\030\001 \001(\014H\000R\022funding_txid_bytes\022," +
      "\n\020funding_txid_str\030\002 \001(\tH\000R\020funding_txid" +
      "_str\022\"\n\014output_index\030\003 \001(\rR\014output_index" +
      "B\016\n\014funding_txid\">\n\020LightningAddress\022\026\n\006" +
      "pubkey\030\001 \001(\tR\006pubkey\022\022\n\004host\030\002 \001(\tR\004host" +
      "\"\261\001\n\017SendManyRequest\022>\n\014AddrToAmount\030\001 \003" +
      "(\0132(.lnrpc.SendManyRequest.AddrToAmountE" +
      "ntry\022\023\n\013target_conf\030\003 \001(\005\022\024\n\014sat_per_byt" +
      "e\030\005 \001(\003\0323\n\021AddrToAmountEntry\022\013\n\003key\030\001 \001(" +
      "\t\022\r\n\005value\030\002 \001(\003:\0028\001\"&\n\020SendManyResponse" +
      "\022\022\n\004txid\030\001 \001(\tR\004txid\"[\n\020SendCoinsRequest" +
      "\022\014\n\004addr\030\001 \001(\t\022\016\n\006amount\030\002 \001(\003\022\023\n\013target" +
      "_conf\030\003 \001(\005\022\024\n\014sat_per_byte\030\005 \001(\003\"\'\n\021Sen" +
      "dCoinsResponse\022\022\n\004txid\030\001 \001(\tR\004txid\"\207\001\n\021N" +
      "ewAddressRequest\0222\n\004type\030\001 \001(\0162$.lnrpc.N" +
      "ewAddressRequest.AddressType\">\n\013AddressT" +
      "ype\022\027\n\023WITNESS_PUBKEY_HASH\020\000\022\026\n\022NESTED_P" +
      "UBKEY_HASH\020\001\"\032\n\030NewWitnessAddressRequest" +
      "\".\n\022NewAddressResponse\022\030\n\007address\030\001 \001(\tR" +
      "\007address\"&\n\022SignMessageRequest\022\020\n\003msg\030\001 " +
      "\001(\014R\003msg\"3\n\023SignMessageResponse\022\034\n\tsigna" +
      "ture\030\001 \001(\tR\tsignature\"F\n\024VerifyMessageRe" +
      "quest\022\020\n\003msg\030\001 \001(\014R\003msg\022\034\n\tsignature\030\002 \001" +
      "(\tR\tsignature\"E\n\025VerifyMessageResponse\022\024" +
      "\n\005valid\030\001 \001(\010R\005valid\022\026\n\006pubkey\030\002 \001(\tR\006pu" +
      "bkey\"I\n\022ConnectPeerRequest\022%\n\004addr\030\001 \001(\013" +
      "2\027.lnrpc.LightningAddress\022\014\n\004perm\030\002 \001(\010\"" +
      "\025\n\023ConnectPeerResponse\"1\n\025DisconnectPeer" +
      "Request\022\030\n\007pub_key\030\001 \001(\tR\007pub_key\"\030\n\026Dis" +
      "connectPeerResponse\"\206\001\n\004HTLC\022\032\n\010incoming" +
      "\030\001 \001(\010R\010incoming\022\026\n\006amount\030\002 \001(\003R\006amount" +
      "\022\034\n\thash_lock\030\003 \001(\014R\thash_lock\022,\n\021expira" +
      "tion_height\030\004 \001(\rR\021expiration_height\"\376\004\n" +
      "\007Channel\022\026\n\006active\030\001 \001(\010R\006active\022$\n\rremo" +
      "te_pubkey\030\002 \001(\tR\rremote_pubkey\022$\n\rchanne" +
      "l_point\030\003 \001(\tR\rchannel_point\022\030\n\007chan_id\030" +
      "\004 \001(\004R\007chan_id\022\032\n\010capacity\030\005 \001(\003R\010capaci" +
      "ty\022$\n\rlocal_balance\030\006 \001(\003R\rlocal_balance" +
      "\022&\n\016remote_balance\030\007 \001(\003R\016remote_balance" +
      "\022\036\n\ncommit_fee\030\010 \001(\003R\ncommit_fee\022$\n\rcomm" +
      "it_weight\030\t \001(\003R\rcommit_weight\022\036\n\nfee_pe" +
      "r_kw\030\n \001(\003R\nfee_per_kw\022,\n\021unsettled_bala" +
      "nce\030\013 \001(\003R\021unsettled_balance\0220\n\023total_sa" +
      "toshis_sent\030\014 \001(\003R\023total_satoshis_sent\0228" +
      "\n\027total_satoshis_received\030\r \001(\003R\027total_s" +
      "atoshis_received\022 \n\013num_updates\030\016 \001(\004R\013n" +
      "um_updates\0221\n\rpending_htlcs\030\017 \003(\0132\013.lnrp" +
      "c.HTLCR\rpending_htlcs\022\034\n\tcsv_delay\030\020 \001(\r" +
      "R\tcsv_delay\022\030\n\007private\030\021 \001(\010R\007private\"l\n" +
      "\023ListChannelsRequest\022\023\n\013active_only\030\001 \001(" +
      "\010\022\025\n\rinactive_only\030\002 \001(\010\022\023\n\013public_only\030" +
      "\003 \001(\010\022\024\n\014private_only\030\004 \001(\010\"B\n\024ListChann" +
      "elsResponse\022*\n\010channels\030\013 \003(\0132\016.lnrpc.Ch" +
      "annelR\010channels\"\352\001\n\004Peer\022\030\n\007pub_key\030\001 \001(" +
      "\tR\007pub_key\022\030\n\007address\030\003 \001(\tR\007address\022\036\n\n" +
      "bytes_sent\030\004 \001(\004R\nbytes_sent\022\036\n\nbytes_re" +
      "cv\030\005 \001(\004R\nbytes_recv\022\032\n\010sat_sent\030\006 \001(\003R\010" +
      "sat_sent\022\032\n\010sat_recv\030\007 \001(\003R\010sat_recv\022\030\n\007" +
      "inbound\030\010 \001(\010R\007inbound\022\034\n\tping_time\030\t \001(" +
      "\003R\tping_time\"\022\n\020ListPeersRequest\"6\n\021List" +
      "PeersResponse\022!\n\005peers\030\001 \003(\0132\013.lnrpc.Pee" +
      "rR\005peers\"\020\n\016GetInfoRequest\"\331\003\n\017GetInfoRe" +
      "sponse\022(\n\017identity_pubkey\030\001 \001(\tR\017identit" +
      "y_pubkey\022\024\n\005alias\030\002 \001(\tR\005alias\0222\n\024num_pe" +
      "nding_channels\030\003 \001(\rR\024num_pending_channe" +
      "ls\0220\n\023num_active_channels\030\004 \001(\rR\023num_act" +
      "ive_channels\022\034\n\tnum_peers\030\005 \001(\rR\tnum_pee" +
      "rs\022\"\n\014block_height\030\006 \001(\rR\014block_height\022\036" +
      "\n\nblock_hash\030\010 \001(\tR\nblock_hash\022(\n\017synced" +
      "_to_chain\030\t \001(\010R\017synced_to_chain\022\030\n\007test" +
      "net\030\n \001(\010R\007testnet\022\026\n\006chains\030\013 \003(\tR\006chai" +
      "ns\022\022\n\004uris\030\014 \003(\tR\004uris\0224\n\025best_header_ti" +
      "mestamp\030\r \001(\003R\025best_header_timestamp\022\030\n\007" +
      "version\030\016 \001(\tR\007version\"U\n\022ConfirmationUp" +
      "date\022\021\n\tblock_sha\030\001 \001(\014\022\024\n\014block_height\030" +
      "\002 \001(\005\022\026\n\016num_confs_left\030\003 \001(\r\"N\n\021Channel" +
      "OpenUpdate\0229\n\rchannel_point\030\001 \001(\0132\023.lnrp" +
      "c.ChannelPointR\rchannel_point\"R\n\022Channel" +
      "CloseUpdate\022\"\n\014closing_txid\030\001 \001(\014R\014closi" +
      "ng_txid\022\030\n\007success\030\002 \001(\010R\007success\"{\n\023Clo" +
      "seChannelRequest\022*\n\rchannel_point\030\001 \001(\0132" +
      "\023.lnrpc.ChannelPoint\022\r\n\005force\030\002 \001(\010\022\023\n\013t" +
      "arget_conf\030\003 \001(\005\022\024\n\014sat_per_byte\030\004 \001(\003\"\331" +
      "\001\n\021CloseStatusUpdate\022<\n\rclose_pending\030\001 " +
      "\001(\0132\024.lnrpc.PendingUpdateH\000R\rclose_pendi" +
      "ng\022?\n\014confirmation\030\002 \001(\0132\031.lnrpc.Confirm" +
      "ationUpdateH\000R\014confirmation\022;\n\nchan_clos" +
      "e\030\003 \001(\0132\031.lnrpc.ChannelCloseUpdateH\000R\nch" +
      "an_closeB\010\n\006update\"G\n\rPendingUpdate\022\022\n\004t" +
      "xid\030\001 \001(\014R\004txid\022\"\n\014output_index\030\002 \001(\rR\014o" +
      "utput_index\"\315\002\n\022OpenChannelRequest\022 \n\013no" +
      "de_pubkey\030\002 \001(\014R\013node_pubkey\022.\n\022node_pub" +
      "key_string\030\003 \001(\tR\022node_pubkey_string\0222\n\024" +
      "local_funding_amount\030\004 \001(\003R\024local_fundin" +
      "g_amount\022\032\n\010push_sat\030\005 \001(\003R\010push_sat\022\023\n\013" +
      "target_conf\030\006 \001(\005\022\024\n\014sat_per_byte\030\007 \001(\003\022" +
      "\030\n\007private\030\010 \001(\010R\007private\022$\n\rmin_htlc_ms" +
      "at\030\t \001(\003R\rmin_htlc_msat\022*\n\020remote_csv_de" +
      "lay\030\n \001(\rR\020remote_csv_delay\"\323\001\n\020OpenStat" +
      "usUpdate\022:\n\014chan_pending\030\001 \001(\0132\024.lnrpc.P" +
      "endingUpdateH\000R\014chan_pending\022?\n\014confirma" +
      "tion\030\002 \001(\0132\031.lnrpc.ConfirmationUpdateH\000R" +
      "\014confirmation\0228\n\tchan_open\030\003 \001(\0132\030.lnrpc" +
      ".ChannelOpenUpdateH\000R\tchan_openB\010\n\006updat" +
      "e\"\317\001\n\013PendingHTLC\022\032\n\010incoming\030\001 \001(\010R\010inc" +
      "oming\022\026\n\006amount\030\002 \001(\003R\006amount\022\032\n\010outpoin" +
      "t\030\003 \001(\tR\010outpoint\022(\n\017maturity_height\030\004 \001" +
      "(\rR\017maturity_height\0220\n\023blocks_til_maturi" +
      "ty\030\005 \001(\005R\023blocks_til_maturity\022\024\n\005stage\030\006" +
      " \001(\rR\005stage\"\030\n\026PendingChannelsRequest\"\301\n" +
      "\n\027PendingChannelsResponse\0220\n\023total_limbo" +
      "_balance\030\001 \001(\003R\023total_limbo_balance\022g\n\025p" +
      "ending_open_channels\030\002 \003(\01321.lnrpc.Pendi" +
      "ngChannelsResponse.PendingOpenChannelR\025p" +
      "ending_open_channels\022h\n\030pending_closing_" +
      "channels\030\003 \003(\0132,.lnrpc.PendingChannelsRe" +
      "sponse.ClosedChannelR\030pending_closing_ch" +
      "annels\022y\n\036pending_force_closing_channels" +
      "\030\004 \003(\01321.lnrpc.PendingChannelsResponse.F" +
      "orceClosedChannelR\036pending_force_closing" +
      "_channels\032\312\001\n\016PendingChannel\022(\n\017remote_n" +
      "ode_pub\030\001 \001(\tR\017remote_node_pub\022$\n\rchanne" +
      "l_point\030\002 \001(\tR\rchannel_point\022\032\n\010capacity" +
      "\030\003 \001(\003R\010capacity\022$\n\rlocal_balance\030\004 \001(\003R" +
      "\rlocal_balance\022&\n\016remote_balance\030\005 \001(\003R\016" +
      "remote_balance\032\365\001\n\022PendingOpenChannel\022G\n" +
      "\007channel\030\001 \001(\0132-.lnrpc.PendingChannelsRe" +
      "sponse.PendingChannelR\007channel\0220\n\023confir" +
      "mation_height\030\002 \001(\rR\023confirmation_height" +
      "\022\036\n\ncommit_fee\030\004 \001(\003R\ncommit_fee\022$\n\rcomm" +
      "it_weight\030\005 \001(\003R\rcommit_weight\022\036\n\nfee_pe" +
      "r_kw\030\006 \001(\003R\nfee_per_kw\032s\n\rClosedChannel\022" +
      ">\n\007channel\030\001 \001(\0132-.lnrpc.PendingChannels" +
      "Response.PendingChannel\022\"\n\014closing_txid\030" +
      "\002 \001(\tR\014closing_txid\032\353\002\n\022ForceClosedChann" +
      "el\022G\n\007channel\030\001 \001(\0132-.lnrpc.PendingChann" +
      "elsResponse.PendingChannelR\007channel\022\"\n\014c" +
      "losing_txid\030\002 \001(\tR\014closing_txid\022$\n\rlimbo" +
      "_balance\030\003 \001(\003R\rlimbo_balance\022(\n\017maturit" +
      "y_height\030\004 \001(\rR\017maturity_height\0220\n\023block" +
      "s_til_maturity\030\005 \001(\005R\023blocks_til_maturit" +
      "y\022,\n\021recovered_balance\030\006 \001(\003R\021recovered_" +
      "balance\0228\n\rpending_htlcs\030\010 \003(\0132\022.lnrpc.P" +
      "endingHTLCR\rpending_htlcs\"\026\n\024WalletBalan" +
      "ceRequest\"\235\001\n\025WalletBalanceResponse\022$\n\rt" +
      "otal_balance\030\001 \001(\003R\rtotal_balance\022,\n\021con" +
      "firmed_balance\030\002 \001(\003R\021confirmed_balance\022" +
      "0\n\023unconfirmed_balance\030\003 \001(\003R\023unconfirme" +
      "d_balance\"\027\n\025ChannelBalanceRequest\"f\n\026Ch" +
      "annelBalanceResponse\022\030\n\007balance\030\001 \001(\003R\007b" +
      "alance\0222\n\024pending_open_balance\030\002 \001(\003R\024pe" +
      "nding_open_balance\"F\n\022QueryRoutesRequest" +
      "\022\017\n\007pub_key\030\001 \001(\t\022\013\n\003amt\030\002 \001(\003\022\022\n\nnum_ro" +
      "utes\030\003 \001(\005\";\n\023QueryRoutesResponse\022$\n\006rou" +
      "tes\030\001 \003(\0132\014.lnrpc.RouteR\006routes\"\355\001\n\003Hop\022" +
      "\030\n\007chan_id\030\001 \001(\004R\007chan_id\022$\n\rchan_capaci" +
      "ty\030\002 \001(\003R\rchan_capacity\022*\n\016amt_to_forwar" +
      "d\030\003 \001(\003B\002\030\001R\016amt_to_forward\022\024\n\003fee\030\004 \001(\003" +
      "B\002\030\001R\003fee\022\026\n\006expiry\030\005 \001(\rR\006expiry\0220\n\023amt" +
      "_to_forward_msat\030\006 \001(\003R\023amt_to_forward_m" +
      "sat\022\032\n\010fee_msat\030\007 \001(\003R\010fee_msat\"\351\001\n\005Rout" +
      "e\022(\n\017total_time_lock\030\001 \001(\rR\017total_time_l" +
      "ock\022\"\n\ntotal_fees\030\002 \001(\003B\002\030\001R\ntotal_fees\022" +
      " \n\ttotal_amt\030\003 \001(\003B\002\030\001R\ttotal_amt\022\036\n\004hop" +
      "s\030\004 \003(\0132\n.lnrpc.HopR\004hops\022(\n\017total_fees_" +
      "msat\030\005 \001(\003R\017total_fees_msat\022&\n\016total_amt" +
      "_msat\030\006 \001(\003R\016total_amt_msat\"\"\n\017NodeInfoR" +
      "equest\022\017\n\007pub_key\030\001 \001(\t\"\200\001\n\010NodeInfo\022(\n\004" +
      "node\030\001 \001(\0132\024.lnrpc.LightningNodeR\004node\022\"" +
      "\n\014num_channels\030\002 \001(\rR\014num_channels\022&\n\016to" +
      "tal_capacity\030\003 \001(\003R\016total_capacity\"\251\001\n\rL" +
      "ightningNode\022 \n\013last_update\030\001 \001(\rR\013last_" +
      "update\022\030\n\007pub_key\030\002 \001(\tR\007pub_key\022\024\n\005alia" +
      "s\030\003 \001(\tR\005alias\0220\n\taddresses\030\004 \003(\0132\022.lnrp" +
      "c.NodeAddressR\taddresses\022\024\n\005color\030\005 \001(\tR" +
      "\005color\";\n\013NodeAddress\022\030\n\007network\030\001 \001(\tR\007" +
      "network\022\022\n\004addr\030\002 \001(\tR\004addr\"\255\001\n\rRoutingP" +
      "olicy\022(\n\017time_lock_delta\030\001 \001(\rR\017time_loc" +
      "k_delta\022\032\n\010min_htlc\030\002 \001(\003R\010min_htlc\022$\n\rf" +
      "ee_base_msat\030\003 \001(\003R\rfee_base_msat\0220\n\023fee" +
      "_rate_milli_msat\030\004 \001(\003R\023fee_rate_milli_m" +
      "sat\"\273\002\n\013ChannelEdge\022\036\n\nchannel_id\030\001 \001(\004R" +
      "\nchannel_id\022\036\n\nchan_point\030\002 \001(\tR\nchan_po" +
      "int\022 \n\013last_update\030\003 \001(\rR\013last_update\022\034\n" +
      "\tnode1_pub\030\004 \001(\tR\tnode1_pub\022\034\n\tnode2_pub" +
      "\030\005 \001(\tR\tnode2_pub\022\032\n\010capacity\030\006 \001(\003R\010cap" +
      "acity\0228\n\014node1_policy\030\007 \001(\0132\024.lnrpc.Rout" +
      "ingPolicyR\014node1_policy\0228\n\014node2_policy\030" +
      "\010 \001(\0132\024.lnrpc.RoutingPolicyR\014node2_polic" +
      "y\"\025\n\023ChannelGraphRequest\"d\n\014ChannelGraph" +
      "\022*\n\005nodes\030\001 \003(\0132\024.lnrpc.LightningNodeR\005n" +
      "odes\022(\n\005edges\030\002 \003(\0132\022.lnrpc.ChannelEdgeR" +
      "\005edges\"\"\n\017ChanInfoRequest\022\017\n\007chan_id\030\001 \001" +
      "(\004\"\024\n\022NetworkInfoRequest\"\203\003\n\013NetworkInfo" +
      "\022&\n\016graph_diameter\030\001 \001(\rR\016graph_diameter" +
      "\022&\n\016avg_out_degree\030\002 \001(\001R\016avg_out_degree" +
      "\022&\n\016max_out_degree\030\003 \001(\rR\016max_out_degree" +
      "\022\034\n\tnum_nodes\030\004 \001(\rR\tnum_nodes\022\"\n\014num_ch" +
      "annels\030\005 \001(\rR\014num_channels\0226\n\026total_netw" +
      "ork_capacity\030\006 \001(\003R\026total_network_capaci" +
      "ty\022*\n\020avg_channel_size\030\007 \001(\001R\020avg_channe" +
      "l_size\022*\n\020min_channel_size\030\010 \001(\003R\020min_ch" +
      "annel_size\022*\n\020max_channel_size\030\t \001(\003R\020ma" +
      "x_channel_size\"\r\n\013StopRequest\"\016\n\014StopRes" +
      "ponse\"\033\n\031GraphTopologySubscription\"\243\001\n\023G" +
      "raphTopologyUpdate\022\'\n\014node_updates\030\001 \003(\013" +
      "2\021.lnrpc.NodeUpdate\0221\n\017channel_updates\030\002" +
      " \003(\0132\030.lnrpc.ChannelEdgeUpdate\0220\n\014closed" +
      "_chans\030\003 \003(\0132\032.lnrpc.ClosedChannelUpdate" +
      "\"]\n\nNodeUpdate\022\021\n\taddresses\030\001 \003(\t\022\024\n\014ide" +
      "ntity_key\030\002 \001(\t\022\027\n\017global_features\030\003 \001(\014" +
      "\022\r\n\005alias\030\004 \001(\t\"\300\001\n\021ChannelEdgeUpdate\022\017\n" +
      "\007chan_id\030\001 \001(\004\022\'\n\nchan_point\030\002 \001(\0132\023.lnr" +
      "pc.ChannelPoint\022\020\n\010capacity\030\003 \001(\003\022,\n\016rou" +
      "ting_policy\030\004 \001(\0132\024.lnrpc.RoutingPolicy\022" +
      "\030\n\020advertising_node\030\005 \001(\t\022\027\n\017connecting_" +
      "node\030\006 \001(\t\"x\n\023ClosedChannelUpdate\022\017\n\007cha" +
      "n_id\030\001 \001(\004\022\020\n\010capacity\030\002 \001(\003\022\025\n\rclosed_h" +
      "eight\030\003 \001(\r\022\'\n\nchan_point\030\004 \001(\0132\023.lnrpc." +
      "ChannelPoint\"\323\001\n\007HopHint\022\030\n\007node_id\030\001 \001(" +
      "\tR\007node_id\022\030\n\007chan_id\030\002 \001(\004R\007chan_id\022$\n\r" +
      "fee_base_msat\030\003 \001(\rR\rfee_base_msat\022@\n\033fe" +
      "e_proportional_millionths\030\004 \001(\rR\033fee_pro" +
      "portional_millionths\022,\n\021cltv_expiry_delt" +
      "a\030\005 \001(\rR\021cltv_expiry_delta\"9\n\tRouteHint\022" +
      ",\n\thop_hints\030\001 \003(\0132\016.lnrpc.HopHintR\thop_" +
      "hints\"\353\003\n\007Invoice\022\022\n\004memo\030\001 \001(\tR\004memo\022\030\n" +
      "\007receipt\030\002 \001(\014R\007receipt\022\036\n\nr_preimage\030\003 " +
      "\001(\014R\nr_preimage\022\026\n\006r_hash\030\004 \001(\014R\006r_hash\022" +
      "\024\n\005value\030\005 \001(\003R\005value\022\030\n\007settled\030\006 \001(\010R\007" +
      "settled\022$\n\rcreation_date\030\007 \001(\003R\rcreation" +
      "_date\022 \n\013settle_date\030\010 \001(\003R\013settle_date\022" +
      "(\n\017payment_request\030\t \001(\tR\017payment_reques" +
      "t\022*\n\020description_hash\030\n \001(\014R\020description" +
      "_hash\022\026\n\006expiry\030\013 \001(\003R\006expiry\022$\n\rfallbac" +
      "k_addr\030\014 \001(\tR\rfallback_addr\022 \n\013cltv_expi" +
      "ry\030\r \001(\004R\013cltv_expiry\0222\n\013route_hints\030\016 \003" +
      "(\0132\020.lnrpc.RouteHintR\013route_hints\022\030\n\007pri" +
      "vate\030\017 \001(\010R\007private\"V\n\022AddInvoiceRespons" +
      "e\022\026\n\006r_hash\030\001 \001(\014R\006r_hash\022(\n\017payment_req" +
      "uest\030\002 \001(\tR\017payment_request\"E\n\013PaymentHa" +
      "sh\022\036\n\nr_hash_str\030\001 \001(\tR\nr_hash_str\022\026\n\006r_" +
      "hash\030\002 \001(\014R\006r_hash\"*\n\022ListInvoiceRequest" +
      "\022\024\n\014pending_only\030\001 \001(\010\"A\n\023ListInvoiceRes" +
      "ponse\022*\n\010invoices\030\001 \003(\0132\016.lnrpc.InvoiceR" +
      "\010invoices\"\025\n\023InvoiceSubscription\"\273\001\n\007Pay" +
      "ment\022\"\n\014payment_hash\030\001 \001(\tR\014payment_hash" +
      "\022\024\n\005value\030\002 \001(\003R\005value\022$\n\rcreation_date\030" +
      "\003 \001(\003R\rcreation_date\022\022\n\004path\030\004 \003(\tR\004path" +
      "\022\020\n\003fee\030\005 \001(\003R\003fee\022*\n\020payment_preimage\030\006" +
      " \001(\tR\020payment_preimage\"\025\n\023ListPaymentsRe" +
      "quest\"B\n\024ListPaymentsResponse\022*\n\010payment" +
      "s\030\001 \003(\0132\016.lnrpc.PaymentR\010payments\"\032\n\030Del" +
      "eteAllPaymentsRequest\"\033\n\031DeleteAllPaymen" +
      "tsResponse\"5\n\021DebugLevelRequest\022\014\n\004show\030" +
      "\001 \001(\010\022\022\n\nlevel_spec\030\002 \001(\t\"6\n\022DebugLevelR" +
      "esponse\022 \n\013sub_systems\030\001 \001(\tR\013sub_system" +
      "s\"\037\n\014PayReqString\022\017\n\007pay_req\030\001 \001(\t\"\362\002\n\006P" +
      "ayReq\022 \n\013destination\030\001 \001(\tR\013destination\022" +
      "\"\n\014payment_hash\030\002 \001(\tR\014payment_hash\022\"\n\014n" +
      "um_satoshis\030\003 \001(\003R\014num_satoshis\022\034\n\ttimes" +
      "tamp\030\004 \001(\003R\ttimestamp\022\026\n\006expiry\030\005 \001(\003R\006e" +
      "xpiry\022 \n\013description\030\006 \001(\tR\013description\022" +
      "*\n\020description_hash\030\007 \001(\tR\020description_h" +
      "ash\022$\n\rfallback_addr\030\010 \001(\tR\rfallback_add" +
      "r\022 \n\013cltv_expiry\030\t \001(\003R\013cltv_expiry\0222\n\013r" +
      "oute_hints\030\n \003(\0132\020.lnrpc.RouteHintR\013rout" +
      "e_hints\"\022\n\020FeeReportRequest\"\231\001\n\020ChannelF" +
      "eeReport\022!\n\nchan_point\030\001 \001(\tR\rchannel_po" +
      "int\022$\n\rbase_fee_msat\030\002 \001(\003R\rbase_fee_msa" +
      "t\022 \n\013fee_per_mil\030\003 \001(\003R\013fee_per_mil\022\032\n\010f" +
      "ee_rate\030\004 \001(\001R\010fee_rate\"\274\001\n\021FeeReportRes" +
      "ponse\022;\n\014channel_fees\030\001 \003(\0132\027.lnrpc.Chan" +
      "nelFeeReportR\014channel_fees\022 \n\013day_fee_su" +
      "m\030\002 \001(\004R\013day_fee_sum\022\"\n\014week_fee_sum\030\003 \001" +
      "(\004R\014week_fee_sum\022$\n\rmonth_fee_sum\030\004 \001(\004R" +
      "\rmonth_fee_sum\"\333\001\n\023PolicyUpdateRequest\022\030" +
      "\n\006global\030\001 \001(\010H\000R\006global\0225\n\nchan_point\030\002" +
      " \001(\0132\023.lnrpc.ChannelPointH\000R\nchan_point\022" +
      "$\n\rbase_fee_msat\030\003 \001(\003R\rbase_fee_msat\022\032\n" +
      "\010fee_rate\030\004 \001(\001R\010fee_rate\022(\n\017time_lock_d" +
      "elta\030\005 \001(\rR\017time_lock_deltaB\007\n\005scope\"\026\n\024" +
      "PolicyUpdateResponse\"\242\001\n\030ForwardingHisto" +
      "ryRequest\022\036\n\nstart_time\030\001 \001(\004R\nstart_tim" +
      "e\022\032\n\010end_time\030\002 \001(\004R\010end_time\022\"\n\014index_o" +
      "ffset\030\003 \001(\rR\014index_offset\022&\n\016num_max_eve" +
      "nts\030\004 \001(\rR\016num_max_events\"\265\001\n\017Forwarding" +
      "Event\022\034\n\ttimestamp\030\001 \001(\004R\ttimestamp\022\036\n\nc" +
      "han_id_in\030\002 \001(\004R\nchan_id_in\022 \n\013chan_id_o" +
      "ut\030\004 \001(\004R\013chan_id_out\022\026\n\006amt_in\030\005 \001(\004R\006a" +
      "mt_in\022\030\n\007amt_out\030\006 \001(\004R\007amt_out\022\020\n\003fee\030\007" +
      " \001(\004R\003fee\"\217\001\n\031ForwardingHistoryResponse\022" +
      "D\n\021forwarding_events\030\001 \003(\0132\026.lnrpc.Forwa" +
      "rdingEventR\021forwarding_events\022,\n\021last_of" +
      "fset_index\030\002 \001(\rR\021last_offset_index2\243\002\n\016" +
      "WalletUnlocker\022M\n\007GenSeed\022\025.lnrpc.GenSee" +
      "dRequest\032\026.lnrpc.GenSeedResponse\"\023\202\323\344\223\002\r" +
      "\022\013/v1/genseed\022\\\n\nInitWallet\022\030.lnrpc.Init" +
      "WalletRequest\032\031.lnrpc.InitWalletResponse" +
      "\"\031\202\323\344\223\002\023\"\016/v1/initwallet:\001*\022d\n\014UnlockWal" +
      "let\022\032.lnrpc.UnlockWalletRequest\032\033.lnrpc." +
      "UnlockWalletResponse\"\033\202\323\344\223\002\025\"\020/v1/unlock" +
      "wallet:\001*2\342\033\n\tLightning\022j\n\rWalletBalance" +
      "\022\033.lnrpc.WalletBalanceRequest\032\034.lnrpc.Wa" +
      "lletBalanceResponse\"\036\202\323\344\223\002\030\022\026/v1/balance" +
      "/blockchain\022k\n\016ChannelBalance\022\034.lnrpc.Ch" +
      "annelBalanceRequest\032\035.lnrpc.ChannelBalan" +
      "ceResponse\"\034\202\323\344\223\002\026\022\024/v1/balance/channels" +
      "\022e\n\017GetTransactions\022\035.lnrpc.GetTransacti" +
      "onsRequest\032\031.lnrpc.TransactionDetails\"\030\202" +
      "\323\344\223\002\022\022\020/v1/transactions\022[\n\tSendCoins\022\027.l" +
      "nrpc.SendCoinsRequest\032\030.lnrpc.SendCoinsR" +
      "esponse\"\033\202\323\344\223\002\025\"\020/v1/transactions:\001*\022L\n\025" +
      "SubscribeTransactions\022\035.lnrpc.GetTransac" +
      "tionsRequest\032\022.lnrpc.Transaction0\001\022;\n\010Se" +
      "ndMany\022\026.lnrpc.SendManyRequest\032\027.lnrpc.S" +
      "endManyResponse\022A\n\nNewAddress\022\030.lnrpc.Ne" +
      "wAddressRequest\032\031.lnrpc.NewAddressRespon" +
      "se\022g\n\021NewWitnessAddress\022\037.lnrpc.NewWitne" +
      "ssAddressRequest\032\031.lnrpc.NewAddressRespo" +
      "nse\"\026\202\323\344\223\002\020\022\016/v1/newaddress\022D\n\013SignMessa" +
      "ge\022\031.lnrpc.SignMessageRequest\032\032.lnrpc.Si" +
      "gnMessageResponse\022J\n\rVerifyMessage\022\033.lnr" +
      "pc.VerifyMessageRequest\032\034.lnrpc.VerifyMe" +
      "ssageResponse\022Z\n\013ConnectPeer\022\031.lnrpc.Con" +
      "nectPeerRequest\032\032.lnrpc.ConnectPeerRespo" +
      "nse\"\024\202\323\344\223\002\016\"\t/v1/peers:\001*\022j\n\016DisconnectP" +
      "eer\022\034.lnrpc.DisconnectPeerRequest\032\035.lnrp" +
      "c.DisconnectPeerResponse\"\033\202\323\344\223\002\025*\023/v1/pe" +
      "ers/{pub_key}\022Q\n\tListPeers\022\027.lnrpc.ListP" +
      "eersRequest\032\030.lnrpc.ListPeersResponse\"\021\202" +
      "\323\344\223\002\013\022\t/v1/peers\022M\n\007GetInfo\022\025.lnrpc.GetI" +
      "nfoRequest\032\026.lnrpc.GetInfoResponse\"\023\202\323\344\223" +
      "\002\r\022\013/v1/getinfo\022n\n\017PendingChannels\022\035.lnr" +
      "pc.PendingChannelsRequest\032\036.lnrpc.Pendin" +
      "gChannelsResponse\"\034\202\323\344\223\002\026\022\024/v1/channels/" +
      "pending\022]\n\014ListChannels\022\032.lnrpc.ListChan" +
      "nelsRequest\032\033.lnrpc.ListChannelsResponse" +
      "\"\024\202\323\344\223\002\016\022\014/v1/channels\022Z\n\017OpenChannelSyn" +
      "c\022\031.lnrpc.OpenChannelRequest\032\023.lnrpc.Cha" +
      "nnelPoint\"\027\202\323\344\223\002\021\"\014/v1/channels:\001*\022C\n\013Op" +
      "enChannel\022\031.lnrpc.OpenChannelRequest\032\027.l" +
      "nrpc.OpenStatusUpdate0\001\022\232\001\n\014CloseChannel" +
      "\022\032.lnrpc.CloseChannelRequest\032\030.lnrpc.Clo" +
      "seStatusUpdate\"R\202\323\344\223\002L*J/v1/channels/{ch" +
      "annel_point.funding_txid_str}/{channel_p" +
      "oint.output_index}0\001\022:\n\013SendPayment\022\022.ln" +
      "rpc.SendRequest\032\023.lnrpc.SendResponse(\0010\001" +
      "\022`\n\017SendPaymentSync\022\022.lnrpc.SendRequest\032" +
      "\023.lnrpc.SendResponse\"$\202\323\344\223\002\036\"\031/v1/channe" +
      "ls/transactions:\001*\022P\n\nAddInvoice\022\016.lnrpc" +
      ".Invoice\032\031.lnrpc.AddInvoiceResponse\"\027\202\323\344" +
      "\223\002\021\"\014/v1/invoices:\001*\022[\n\014ListInvoices\022\031.l" +
      "nrpc.ListInvoiceRequest\032\032.lnrpc.ListInvo" +
      "iceResponse\"\024\202\323\344\223\002\016\022\014/v1/invoices\022U\n\rLoo" +
      "kupInvoice\022\022.lnrpc.PaymentHash\032\016.lnrpc.I" +
      "nvoice\" \202\323\344\223\002\032\022\030/v1/invoice/{r_hash_str}" +
      "\022a\n\021SubscribeInvoices\022\032.lnrpc.InvoiceSub" +
      "scription\032\016.lnrpc.Invoice\"\036\202\323\344\223\002\030\022\026/v1/i" +
      "nvoices/subscribe0\001\022P\n\014DecodePayReq\022\023.ln" +
      "rpc.PayReqString\032\r.lnrpc.PayReq\"\034\202\323\344\223\002\026\022" +
      "\024/v1/payreq/{pay_req}\022]\n\014ListPayments\022\032." +
      "lnrpc.ListPaymentsRequest\032\033.lnrpc.ListPa" +
      "ymentsResponse\"\024\202\323\344\223\002\016\022\014/v1/payments\022l\n\021" +
      "DeleteAllPayments\022\037.lnrpc.DeleteAllPayme" +
      "ntsRequest\032 .lnrpc.DeleteAllPaymentsResp" +
      "onse\"\024\202\323\344\223\002\016*\014/v1/payments\022S\n\rDescribeGr" +
      "aph\022\032.lnrpc.ChannelGraphRequest\032\023.lnrpc." +
      "ChannelGraph\"\021\202\323\344\223\002\013\022\t/v1/graph\022[\n\013GetCh" +
      "anInfo\022\026.lnrpc.ChanInfoRequest\032\022.lnrpc.C" +
      "hannelEdge\" \202\323\344\223\002\032\022\030/v1/graph/edge/{chan" +
      "_id}\022X\n\013GetNodeInfo\022\026.lnrpc.NodeInfoRequ",
      "est\032\017.lnrpc.NodeInfo\" \202\323\344\223\002\032\022\030/v1/graph/" +
      "node/{pub_key}\022n\n\013QueryRoutes\022\031.lnrpc.Qu" +
      "eryRoutesRequest\032\032.lnrpc.QueryRoutesResp" +
      "onse\"(\202\323\344\223\002\"\022 /v1/graph/routes/{pub_key}" +
      "/{amt}\022W\n\016GetNetworkInfo\022\031.lnrpc.Network" +
      "InfoRequest\032\022.lnrpc.NetworkInfo\"\026\202\323\344\223\002\020\022" +
      "\016/v1/graph/info\0225\n\nStopDaemon\022\022.lnrpc.St" +
      "opRequest\032\023.lnrpc.StopResponse\022W\n\025Subscr" +
      "ibeChannelGraph\022 .lnrpc.GraphTopologySub" +
      "scription\032\032.lnrpc.GraphTopologyUpdate0\001\022" +
      "A\n\nDebugLevel\022\030.lnrpc.DebugLevelRequest\032" +
      "\031.lnrpc.DebugLevelResponse\022P\n\tFeeReport\022" +
      "\027.lnrpc.FeeReportRequest\032\030.lnrpc.FeeRepo" +
      "rtResponse\"\020\202\323\344\223\002\n\022\010/v1/fees\022i\n\023UpdateCh" +
      "annelPolicy\022\032.lnrpc.PolicyUpdateRequest\032" +
      "\033.lnrpc.PolicyUpdateResponse\"\031\202\323\344\223\002\023\"\016/v" +
      "1/chanpolicy:\001*\022m\n\021ForwardingHistory\022\037.l" +
      "nrpc.ForwardingHistoryRequest\032 .lnrpc.Fo" +
      "rwardingHistoryResponse\"\025\202\323\344\223\002\017\"\n/v1/swi" +
      "tch:\001*B\025\n\021lightpay.lnd.grpcP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.api.AnnotationsProto.getDescriptor(),
        }, assigner);
    internal_static_lnrpc_GenSeedRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_lnrpc_GenSeedRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_GenSeedRequest_descriptor,
        new java.lang.String[] { "AezeedPassphrase", "SeedEntropy", });
    internal_static_lnrpc_GenSeedResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_lnrpc_GenSeedResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_GenSeedResponse_descriptor,
        new java.lang.String[] { "CipherSeedMnemonic", "EncipheredSeed", });
    internal_static_lnrpc_InitWalletRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_lnrpc_InitWalletRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_InitWalletRequest_descriptor,
        new java.lang.String[] { "WalletPassword", "CipherSeedMnemonic", "AezeedPassphrase", });
    internal_static_lnrpc_InitWalletResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_lnrpc_InitWalletResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_InitWalletResponse_descriptor,
        new java.lang.String[] { });
    internal_static_lnrpc_UnlockWalletRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_lnrpc_UnlockWalletRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_UnlockWalletRequest_descriptor,
        new java.lang.String[] { "WalletPassword", });
    internal_static_lnrpc_UnlockWalletResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_lnrpc_UnlockWalletResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_UnlockWalletResponse_descriptor,
        new java.lang.String[] { });
    internal_static_lnrpc_Transaction_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_lnrpc_Transaction_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_Transaction_descriptor,
        new java.lang.String[] { "TxHash", "Amount", "NumConfirmations", "BlockHash", "BlockHeight", "TimeStamp", "TotalFees", "DestAddresses", });
    internal_static_lnrpc_GetTransactionsRequest_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_lnrpc_GetTransactionsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_GetTransactionsRequest_descriptor,
        new java.lang.String[] { });
    internal_static_lnrpc_TransactionDetails_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_lnrpc_TransactionDetails_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_TransactionDetails_descriptor,
        new java.lang.String[] { "Transactions", });
    internal_static_lnrpc_SendRequest_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_lnrpc_SendRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_SendRequest_descriptor,
        new java.lang.String[] { "Dest", "DestString", "Amt", "PaymentHash", "PaymentHashString", "PaymentRequest", "FinalCltvDelta", });
    internal_static_lnrpc_SendResponse_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_lnrpc_SendResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_SendResponse_descriptor,
        new java.lang.String[] { "PaymentError", "PaymentPreimage", "PaymentRoute", });
    internal_static_lnrpc_ChannelPoint_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_lnrpc_ChannelPoint_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_ChannelPoint_descriptor,
        new java.lang.String[] { "FundingTxidBytes", "FundingTxidStr", "OutputIndex", "FundingTxid", });
    internal_static_lnrpc_LightningAddress_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_lnrpc_LightningAddress_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_LightningAddress_descriptor,
        new java.lang.String[] { "Pubkey", "Host", });
    internal_static_lnrpc_SendManyRequest_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_lnrpc_SendManyRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_SendManyRequest_descriptor,
        new java.lang.String[] { "AddrToAmount", "TargetConf", "SatPerByte", });
    internal_static_lnrpc_SendManyRequest_AddrToAmountEntry_descriptor =
      internal_static_lnrpc_SendManyRequest_descriptor.getNestedTypes().get(0);
    internal_static_lnrpc_SendManyRequest_AddrToAmountEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_SendManyRequest_AddrToAmountEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_lnrpc_SendManyResponse_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_lnrpc_SendManyResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_SendManyResponse_descriptor,
        new java.lang.String[] { "Txid", });
    internal_static_lnrpc_SendCoinsRequest_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_lnrpc_SendCoinsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_SendCoinsRequest_descriptor,
        new java.lang.String[] { "Addr", "Amount", "TargetConf", "SatPerByte", });
    internal_static_lnrpc_SendCoinsResponse_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_lnrpc_SendCoinsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_SendCoinsResponse_descriptor,
        new java.lang.String[] { "Txid", });
    internal_static_lnrpc_NewAddressRequest_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_lnrpc_NewAddressRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_NewAddressRequest_descriptor,
        new java.lang.String[] { "Type", });
    internal_static_lnrpc_NewWitnessAddressRequest_descriptor =
      getDescriptor().getMessageTypes().get(18);
    internal_static_lnrpc_NewWitnessAddressRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_NewWitnessAddressRequest_descriptor,
        new java.lang.String[] { });
    internal_static_lnrpc_NewAddressResponse_descriptor =
      getDescriptor().getMessageTypes().get(19);
    internal_static_lnrpc_NewAddressResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_NewAddressResponse_descriptor,
        new java.lang.String[] { "Address", });
    internal_static_lnrpc_SignMessageRequest_descriptor =
      getDescriptor().getMessageTypes().get(20);
    internal_static_lnrpc_SignMessageRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_SignMessageRequest_descriptor,
        new java.lang.String[] { "Msg", });
    internal_static_lnrpc_SignMessageResponse_descriptor =
      getDescriptor().getMessageTypes().get(21);
    internal_static_lnrpc_SignMessageResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_SignMessageResponse_descriptor,
        new java.lang.String[] { "Signature", });
    internal_static_lnrpc_VerifyMessageRequest_descriptor =
      getDescriptor().getMessageTypes().get(22);
    internal_static_lnrpc_VerifyMessageRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_VerifyMessageRequest_descriptor,
        new java.lang.String[] { "Msg", "Signature", });
    internal_static_lnrpc_VerifyMessageResponse_descriptor =
      getDescriptor().getMessageTypes().get(23);
    internal_static_lnrpc_VerifyMessageResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_VerifyMessageResponse_descriptor,
        new java.lang.String[] { "Valid", "Pubkey", });
    internal_static_lnrpc_ConnectPeerRequest_descriptor =
      getDescriptor().getMessageTypes().get(24);
    internal_static_lnrpc_ConnectPeerRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_ConnectPeerRequest_descriptor,
        new java.lang.String[] { "Addr", "Perm", });
    internal_static_lnrpc_ConnectPeerResponse_descriptor =
      getDescriptor().getMessageTypes().get(25);
    internal_static_lnrpc_ConnectPeerResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_ConnectPeerResponse_descriptor,
        new java.lang.String[] { });
    internal_static_lnrpc_DisconnectPeerRequest_descriptor =
      getDescriptor().getMessageTypes().get(26);
    internal_static_lnrpc_DisconnectPeerRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_DisconnectPeerRequest_descriptor,
        new java.lang.String[] { "PubKey", });
    internal_static_lnrpc_DisconnectPeerResponse_descriptor =
      getDescriptor().getMessageTypes().get(27);
    internal_static_lnrpc_DisconnectPeerResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_DisconnectPeerResponse_descriptor,
        new java.lang.String[] { });
    internal_static_lnrpc_HTLC_descriptor =
      getDescriptor().getMessageTypes().get(28);
    internal_static_lnrpc_HTLC_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_HTLC_descriptor,
        new java.lang.String[] { "Incoming", "Amount", "HashLock", "ExpirationHeight", });
    internal_static_lnrpc_Channel_descriptor =
      getDescriptor().getMessageTypes().get(29);
    internal_static_lnrpc_Channel_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_Channel_descriptor,
        new java.lang.String[] { "Active", "RemotePubkey", "ChannelPoint", "ChanId", "Capacity", "LocalBalance", "RemoteBalance", "CommitFee", "CommitWeight", "FeePerKw", "UnsettledBalance", "TotalSatoshisSent", "TotalSatoshisReceived", "NumUpdates", "PendingHtlcs", "CsvDelay", "Private", });
    internal_static_lnrpc_ListChannelsRequest_descriptor =
      getDescriptor().getMessageTypes().get(30);
    internal_static_lnrpc_ListChannelsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_ListChannelsRequest_descriptor,
        new java.lang.String[] { "ActiveOnly", "InactiveOnly", "PublicOnly", "PrivateOnly", });
    internal_static_lnrpc_ListChannelsResponse_descriptor =
      getDescriptor().getMessageTypes().get(31);
    internal_static_lnrpc_ListChannelsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_ListChannelsResponse_descriptor,
        new java.lang.String[] { "Channels", });
    internal_static_lnrpc_Peer_descriptor =
      getDescriptor().getMessageTypes().get(32);
    internal_static_lnrpc_Peer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_Peer_descriptor,
        new java.lang.String[] { "PubKey", "Address", "BytesSent", "BytesRecv", "SatSent", "SatRecv", "Inbound", "PingTime", });
    internal_static_lnrpc_ListPeersRequest_descriptor =
      getDescriptor().getMessageTypes().get(33);
    internal_static_lnrpc_ListPeersRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_ListPeersRequest_descriptor,
        new java.lang.String[] { });
    internal_static_lnrpc_ListPeersResponse_descriptor =
      getDescriptor().getMessageTypes().get(34);
    internal_static_lnrpc_ListPeersResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_ListPeersResponse_descriptor,
        new java.lang.String[] { "Peers", });
    internal_static_lnrpc_GetInfoRequest_descriptor =
      getDescriptor().getMessageTypes().get(35);
    internal_static_lnrpc_GetInfoRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_GetInfoRequest_descriptor,
        new java.lang.String[] { });
    internal_static_lnrpc_GetInfoResponse_descriptor =
      getDescriptor().getMessageTypes().get(36);
    internal_static_lnrpc_GetInfoResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_GetInfoResponse_descriptor,
        new java.lang.String[] { "IdentityPubkey", "Alias", "NumPendingChannels", "NumActiveChannels", "NumPeers", "BlockHeight", "BlockHash", "SyncedToChain", "Testnet", "Chains", "Uris", "BestHeaderTimestamp", "Version", });
    internal_static_lnrpc_ConfirmationUpdate_descriptor =
      getDescriptor().getMessageTypes().get(37);
    internal_static_lnrpc_ConfirmationUpdate_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_ConfirmationUpdate_descriptor,
        new java.lang.String[] { "BlockSha", "BlockHeight", "NumConfsLeft", });
    internal_static_lnrpc_ChannelOpenUpdate_descriptor =
      getDescriptor().getMessageTypes().get(38);
    internal_static_lnrpc_ChannelOpenUpdate_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_ChannelOpenUpdate_descriptor,
        new java.lang.String[] { "ChannelPoint", });
    internal_static_lnrpc_ChannelCloseUpdate_descriptor =
      getDescriptor().getMessageTypes().get(39);
    internal_static_lnrpc_ChannelCloseUpdate_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_ChannelCloseUpdate_descriptor,
        new java.lang.String[] { "ClosingTxid", "Success", });
    internal_static_lnrpc_CloseChannelRequest_descriptor =
      getDescriptor().getMessageTypes().get(40);
    internal_static_lnrpc_CloseChannelRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_CloseChannelRequest_descriptor,
        new java.lang.String[] { "ChannelPoint", "Force", "TargetConf", "SatPerByte", });
    internal_static_lnrpc_CloseStatusUpdate_descriptor =
      getDescriptor().getMessageTypes().get(41);
    internal_static_lnrpc_CloseStatusUpdate_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_CloseStatusUpdate_descriptor,
        new java.lang.String[] { "ClosePending", "Confirmation", "ChanClose", "Update", });
    internal_static_lnrpc_PendingUpdate_descriptor =
      getDescriptor().getMessageTypes().get(42);
    internal_static_lnrpc_PendingUpdate_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_PendingUpdate_descriptor,
        new java.lang.String[] { "Txid", "OutputIndex", });
    internal_static_lnrpc_OpenChannelRequest_descriptor =
      getDescriptor().getMessageTypes().get(43);
    internal_static_lnrpc_OpenChannelRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_OpenChannelRequest_descriptor,
        new java.lang.String[] { "NodePubkey", "NodePubkeyString", "LocalFundingAmount", "PushSat", "TargetConf", "SatPerByte", "Private", "MinHtlcMsat", "RemoteCsvDelay", });
    internal_static_lnrpc_OpenStatusUpdate_descriptor =
      getDescriptor().getMessageTypes().get(44);
    internal_static_lnrpc_OpenStatusUpdate_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_OpenStatusUpdate_descriptor,
        new java.lang.String[] { "ChanPending", "Confirmation", "ChanOpen", "Update", });
    internal_static_lnrpc_PendingHTLC_descriptor =
      getDescriptor().getMessageTypes().get(45);
    internal_static_lnrpc_PendingHTLC_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_PendingHTLC_descriptor,
        new java.lang.String[] { "Incoming", "Amount", "Outpoint", "MaturityHeight", "BlocksTilMaturity", "Stage", });
    internal_static_lnrpc_PendingChannelsRequest_descriptor =
      getDescriptor().getMessageTypes().get(46);
    internal_static_lnrpc_PendingChannelsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_PendingChannelsRequest_descriptor,
        new java.lang.String[] { });
    internal_static_lnrpc_PendingChannelsResponse_descriptor =
      getDescriptor().getMessageTypes().get(47);
    internal_static_lnrpc_PendingChannelsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_PendingChannelsResponse_descriptor,
        new java.lang.String[] { "TotalLimboBalance", "PendingOpenChannels", "PendingClosingChannels", "PendingForceClosingChannels", });
    internal_static_lnrpc_PendingChannelsResponse_PendingChannel_descriptor =
      internal_static_lnrpc_PendingChannelsResponse_descriptor.getNestedTypes().get(0);
    internal_static_lnrpc_PendingChannelsResponse_PendingChannel_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_PendingChannelsResponse_PendingChannel_descriptor,
        new java.lang.String[] { "RemoteNodePub", "ChannelPoint", "Capacity", "LocalBalance", "RemoteBalance", });
    internal_static_lnrpc_PendingChannelsResponse_PendingOpenChannel_descriptor =
      internal_static_lnrpc_PendingChannelsResponse_descriptor.getNestedTypes().get(1);
    internal_static_lnrpc_PendingChannelsResponse_PendingOpenChannel_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_PendingChannelsResponse_PendingOpenChannel_descriptor,
        new java.lang.String[] { "Channel", "ConfirmationHeight", "CommitFee", "CommitWeight", "FeePerKw", });
    internal_static_lnrpc_PendingChannelsResponse_ClosedChannel_descriptor =
      internal_static_lnrpc_PendingChannelsResponse_descriptor.getNestedTypes().get(2);
    internal_static_lnrpc_PendingChannelsResponse_ClosedChannel_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_PendingChannelsResponse_ClosedChannel_descriptor,
        new java.lang.String[] { "Channel", "ClosingTxid", });
    internal_static_lnrpc_PendingChannelsResponse_ForceClosedChannel_descriptor =
      internal_static_lnrpc_PendingChannelsResponse_descriptor.getNestedTypes().get(3);
    internal_static_lnrpc_PendingChannelsResponse_ForceClosedChannel_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_PendingChannelsResponse_ForceClosedChannel_descriptor,
        new java.lang.String[] { "Channel", "ClosingTxid", "LimboBalance", "MaturityHeight", "BlocksTilMaturity", "RecoveredBalance", "PendingHtlcs", });
    internal_static_lnrpc_WalletBalanceRequest_descriptor =
      getDescriptor().getMessageTypes().get(48);
    internal_static_lnrpc_WalletBalanceRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_WalletBalanceRequest_descriptor,
        new java.lang.String[] { });
    internal_static_lnrpc_WalletBalanceResponse_descriptor =
      getDescriptor().getMessageTypes().get(49);
    internal_static_lnrpc_WalletBalanceResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_WalletBalanceResponse_descriptor,
        new java.lang.String[] { "TotalBalance", "ConfirmedBalance", "UnconfirmedBalance", });
    internal_static_lnrpc_ChannelBalanceRequest_descriptor =
      getDescriptor().getMessageTypes().get(50);
    internal_static_lnrpc_ChannelBalanceRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_ChannelBalanceRequest_descriptor,
        new java.lang.String[] { });
    internal_static_lnrpc_ChannelBalanceResponse_descriptor =
      getDescriptor().getMessageTypes().get(51);
    internal_static_lnrpc_ChannelBalanceResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_ChannelBalanceResponse_descriptor,
        new java.lang.String[] { "Balance", "PendingOpenBalance", });
    internal_static_lnrpc_QueryRoutesRequest_descriptor =
      getDescriptor().getMessageTypes().get(52);
    internal_static_lnrpc_QueryRoutesRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_QueryRoutesRequest_descriptor,
        new java.lang.String[] { "PubKey", "Amt", "NumRoutes", });
    internal_static_lnrpc_QueryRoutesResponse_descriptor =
      getDescriptor().getMessageTypes().get(53);
    internal_static_lnrpc_QueryRoutesResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_QueryRoutesResponse_descriptor,
        new java.lang.String[] { "Routes", });
    internal_static_lnrpc_Hop_descriptor =
      getDescriptor().getMessageTypes().get(54);
    internal_static_lnrpc_Hop_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_Hop_descriptor,
        new java.lang.String[] { "ChanId", "ChanCapacity", "AmtToForward", "Fee", "Expiry", "AmtToForwardMsat", "FeeMsat", });
    internal_static_lnrpc_Route_descriptor =
      getDescriptor().getMessageTypes().get(55);
    internal_static_lnrpc_Route_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_Route_descriptor,
        new java.lang.String[] { "TotalTimeLock", "TotalFees", "TotalAmt", "Hops", "TotalFeesMsat", "TotalAmtMsat", });
    internal_static_lnrpc_NodeInfoRequest_descriptor =
      getDescriptor().getMessageTypes().get(56);
    internal_static_lnrpc_NodeInfoRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_NodeInfoRequest_descriptor,
        new java.lang.String[] { "PubKey", });
    internal_static_lnrpc_NodeInfo_descriptor =
      getDescriptor().getMessageTypes().get(57);
    internal_static_lnrpc_NodeInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_NodeInfo_descriptor,
        new java.lang.String[] { "Node", "NumChannels", "TotalCapacity", });
    internal_static_lnrpc_LightningNode_descriptor =
      getDescriptor().getMessageTypes().get(58);
    internal_static_lnrpc_LightningNode_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_LightningNode_descriptor,
        new java.lang.String[] { "LastUpdate", "PubKey", "Alias", "Addresses", "Color", });
    internal_static_lnrpc_NodeAddress_descriptor =
      getDescriptor().getMessageTypes().get(59);
    internal_static_lnrpc_NodeAddress_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_NodeAddress_descriptor,
        new java.lang.String[] { "Network", "Addr", });
    internal_static_lnrpc_RoutingPolicy_descriptor =
      getDescriptor().getMessageTypes().get(60);
    internal_static_lnrpc_RoutingPolicy_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_RoutingPolicy_descriptor,
        new java.lang.String[] { "TimeLockDelta", "MinHtlc", "FeeBaseMsat", "FeeRateMilliMsat", });
    internal_static_lnrpc_ChannelEdge_descriptor =
      getDescriptor().getMessageTypes().get(61);
    internal_static_lnrpc_ChannelEdge_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_ChannelEdge_descriptor,
        new java.lang.String[] { "ChannelId", "ChanPoint", "LastUpdate", "Node1Pub", "Node2Pub", "Capacity", "Node1Policy", "Node2Policy", });
    internal_static_lnrpc_ChannelGraphRequest_descriptor =
      getDescriptor().getMessageTypes().get(62);
    internal_static_lnrpc_ChannelGraphRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_ChannelGraphRequest_descriptor,
        new java.lang.String[] { });
    internal_static_lnrpc_ChannelGraph_descriptor =
      getDescriptor().getMessageTypes().get(63);
    internal_static_lnrpc_ChannelGraph_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_ChannelGraph_descriptor,
        new java.lang.String[] { "Nodes", "Edges", });
    internal_static_lnrpc_ChanInfoRequest_descriptor =
      getDescriptor().getMessageTypes().get(64);
    internal_static_lnrpc_ChanInfoRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_ChanInfoRequest_descriptor,
        new java.lang.String[] { "ChanId", });
    internal_static_lnrpc_NetworkInfoRequest_descriptor =
      getDescriptor().getMessageTypes().get(65);
    internal_static_lnrpc_NetworkInfoRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_NetworkInfoRequest_descriptor,
        new java.lang.String[] { });
    internal_static_lnrpc_NetworkInfo_descriptor =
      getDescriptor().getMessageTypes().get(66);
    internal_static_lnrpc_NetworkInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_NetworkInfo_descriptor,
        new java.lang.String[] { "GraphDiameter", "AvgOutDegree", "MaxOutDegree", "NumNodes", "NumChannels", "TotalNetworkCapacity", "AvgChannelSize", "MinChannelSize", "MaxChannelSize", });
    internal_static_lnrpc_StopRequest_descriptor =
      getDescriptor().getMessageTypes().get(67);
    internal_static_lnrpc_StopRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_StopRequest_descriptor,
        new java.lang.String[] { });
    internal_static_lnrpc_StopResponse_descriptor =
      getDescriptor().getMessageTypes().get(68);
    internal_static_lnrpc_StopResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_StopResponse_descriptor,
        new java.lang.String[] { });
    internal_static_lnrpc_GraphTopologySubscription_descriptor =
      getDescriptor().getMessageTypes().get(69);
    internal_static_lnrpc_GraphTopologySubscription_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_GraphTopologySubscription_descriptor,
        new java.lang.String[] { });
    internal_static_lnrpc_GraphTopologyUpdate_descriptor =
      getDescriptor().getMessageTypes().get(70);
    internal_static_lnrpc_GraphTopologyUpdate_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_GraphTopologyUpdate_descriptor,
        new java.lang.String[] { "NodeUpdates", "ChannelUpdates", "ClosedChans", });
    internal_static_lnrpc_NodeUpdate_descriptor =
      getDescriptor().getMessageTypes().get(71);
    internal_static_lnrpc_NodeUpdate_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_NodeUpdate_descriptor,
        new java.lang.String[] { "Addresses", "IdentityKey", "GlobalFeatures", "Alias", });
    internal_static_lnrpc_ChannelEdgeUpdate_descriptor =
      getDescriptor().getMessageTypes().get(72);
    internal_static_lnrpc_ChannelEdgeUpdate_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_ChannelEdgeUpdate_descriptor,
        new java.lang.String[] { "ChanId", "ChanPoint", "Capacity", "RoutingPolicy", "AdvertisingNode", "ConnectingNode", });
    internal_static_lnrpc_ClosedChannelUpdate_descriptor =
      getDescriptor().getMessageTypes().get(73);
    internal_static_lnrpc_ClosedChannelUpdate_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_ClosedChannelUpdate_descriptor,
        new java.lang.String[] { "ChanId", "Capacity", "ClosedHeight", "ChanPoint", });
    internal_static_lnrpc_HopHint_descriptor =
      getDescriptor().getMessageTypes().get(74);
    internal_static_lnrpc_HopHint_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_HopHint_descriptor,
        new java.lang.String[] { "NodeId", "ChanId", "FeeBaseMsat", "FeeProportionalMillionths", "CltvExpiryDelta", });
    internal_static_lnrpc_RouteHint_descriptor =
      getDescriptor().getMessageTypes().get(75);
    internal_static_lnrpc_RouteHint_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_RouteHint_descriptor,
        new java.lang.String[] { "HopHints", });
    internal_static_lnrpc_Invoice_descriptor =
      getDescriptor().getMessageTypes().get(76);
    internal_static_lnrpc_Invoice_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_Invoice_descriptor,
        new java.lang.String[] { "Memo", "Receipt", "RPreimage", "RHash", "Value", "Settled", "CreationDate", "SettleDate", "PaymentRequest", "DescriptionHash", "Expiry", "FallbackAddr", "CltvExpiry", "RouteHints", "Private", });
    internal_static_lnrpc_AddInvoiceResponse_descriptor =
      getDescriptor().getMessageTypes().get(77);
    internal_static_lnrpc_AddInvoiceResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_AddInvoiceResponse_descriptor,
        new java.lang.String[] { "RHash", "PaymentRequest", });
    internal_static_lnrpc_PaymentHash_descriptor =
      getDescriptor().getMessageTypes().get(78);
    internal_static_lnrpc_PaymentHash_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_PaymentHash_descriptor,
        new java.lang.String[] { "RHashStr", "RHash", });
    internal_static_lnrpc_ListInvoiceRequest_descriptor =
      getDescriptor().getMessageTypes().get(79);
    internal_static_lnrpc_ListInvoiceRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_ListInvoiceRequest_descriptor,
        new java.lang.String[] { "PendingOnly", });
    internal_static_lnrpc_ListInvoiceResponse_descriptor =
      getDescriptor().getMessageTypes().get(80);
    internal_static_lnrpc_ListInvoiceResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_ListInvoiceResponse_descriptor,
        new java.lang.String[] { "Invoices", });
    internal_static_lnrpc_InvoiceSubscription_descriptor =
      getDescriptor().getMessageTypes().get(81);
    internal_static_lnrpc_InvoiceSubscription_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_InvoiceSubscription_descriptor,
        new java.lang.String[] { });
    internal_static_lnrpc_Payment_descriptor =
      getDescriptor().getMessageTypes().get(82);
    internal_static_lnrpc_Payment_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_Payment_descriptor,
        new java.lang.String[] { "PaymentHash", "Value", "CreationDate", "Path", "Fee", "PaymentPreimage", });
    internal_static_lnrpc_ListPaymentsRequest_descriptor =
      getDescriptor().getMessageTypes().get(83);
    internal_static_lnrpc_ListPaymentsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_ListPaymentsRequest_descriptor,
        new java.lang.String[] { });
    internal_static_lnrpc_ListPaymentsResponse_descriptor =
      getDescriptor().getMessageTypes().get(84);
    internal_static_lnrpc_ListPaymentsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_ListPaymentsResponse_descriptor,
        new java.lang.String[] { "Payments", });
    internal_static_lnrpc_DeleteAllPaymentsRequest_descriptor =
      getDescriptor().getMessageTypes().get(85);
    internal_static_lnrpc_DeleteAllPaymentsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_DeleteAllPaymentsRequest_descriptor,
        new java.lang.String[] { });
    internal_static_lnrpc_DeleteAllPaymentsResponse_descriptor =
      getDescriptor().getMessageTypes().get(86);
    internal_static_lnrpc_DeleteAllPaymentsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_DeleteAllPaymentsResponse_descriptor,
        new java.lang.String[] { });
    internal_static_lnrpc_DebugLevelRequest_descriptor =
      getDescriptor().getMessageTypes().get(87);
    internal_static_lnrpc_DebugLevelRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_DebugLevelRequest_descriptor,
        new java.lang.String[] { "Show", "LevelSpec", });
    internal_static_lnrpc_DebugLevelResponse_descriptor =
      getDescriptor().getMessageTypes().get(88);
    internal_static_lnrpc_DebugLevelResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_DebugLevelResponse_descriptor,
        new java.lang.String[] { "SubSystems", });
    internal_static_lnrpc_PayReqString_descriptor =
      getDescriptor().getMessageTypes().get(89);
    internal_static_lnrpc_PayReqString_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_PayReqString_descriptor,
        new java.lang.String[] { "PayReq", });
    internal_static_lnrpc_PayReq_descriptor =
      getDescriptor().getMessageTypes().get(90);
    internal_static_lnrpc_PayReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_PayReq_descriptor,
        new java.lang.String[] { "Destination", "PaymentHash", "NumSatoshis", "Timestamp", "Expiry", "Description", "DescriptionHash", "FallbackAddr", "CltvExpiry", "RouteHints", });
    internal_static_lnrpc_FeeReportRequest_descriptor =
      getDescriptor().getMessageTypes().get(91);
    internal_static_lnrpc_FeeReportRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_FeeReportRequest_descriptor,
        new java.lang.String[] { });
    internal_static_lnrpc_ChannelFeeReport_descriptor =
      getDescriptor().getMessageTypes().get(92);
    internal_static_lnrpc_ChannelFeeReport_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_ChannelFeeReport_descriptor,
        new java.lang.String[] { "ChanPoint", "BaseFeeMsat", "FeePerMil", "FeeRate", });
    internal_static_lnrpc_FeeReportResponse_descriptor =
      getDescriptor().getMessageTypes().get(93);
    internal_static_lnrpc_FeeReportResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_FeeReportResponse_descriptor,
        new java.lang.String[] { "ChannelFees", "DayFeeSum", "WeekFeeSum", "MonthFeeSum", });
    internal_static_lnrpc_PolicyUpdateRequest_descriptor =
      getDescriptor().getMessageTypes().get(94);
    internal_static_lnrpc_PolicyUpdateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_PolicyUpdateRequest_descriptor,
        new java.lang.String[] { "Global", "ChanPoint", "BaseFeeMsat", "FeeRate", "TimeLockDelta", "Scope", });
    internal_static_lnrpc_PolicyUpdateResponse_descriptor =
      getDescriptor().getMessageTypes().get(95);
    internal_static_lnrpc_PolicyUpdateResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_PolicyUpdateResponse_descriptor,
        new java.lang.String[] { });
    internal_static_lnrpc_ForwardingHistoryRequest_descriptor =
      getDescriptor().getMessageTypes().get(96);
    internal_static_lnrpc_ForwardingHistoryRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_ForwardingHistoryRequest_descriptor,
        new java.lang.String[] { "StartTime", "EndTime", "IndexOffset", "NumMaxEvents", });
    internal_static_lnrpc_ForwardingEvent_descriptor =
      getDescriptor().getMessageTypes().get(97);
    internal_static_lnrpc_ForwardingEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_ForwardingEvent_descriptor,
        new java.lang.String[] { "Timestamp", "ChanIdIn", "ChanIdOut", "AmtIn", "AmtOut", "Fee", });
    internal_static_lnrpc_ForwardingHistoryResponse_descriptor =
      getDescriptor().getMessageTypes().get(98);
    internal_static_lnrpc_ForwardingHistoryResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_ForwardingHistoryResponse_descriptor,
        new java.lang.String[] { "ForwardingEvents", "LastOffsetIndex", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.api.AnnotationsProto.http);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.api.AnnotationsProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
