// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc.proto

package lightpay.lnd.grpc;

public final class Rpc {
  private Rpc() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_CreateWalletRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_CreateWalletRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_CreateWalletResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_CreateWalletResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_UnlockWalletRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_UnlockWalletRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_UnlockWalletResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_UnlockWalletResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_Transaction_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_Transaction_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_GetTransactionsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_GetTransactionsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_TransactionDetails_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_TransactionDetails_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_SendRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_SendRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_SendResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_SendResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_ChannelPoint_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_ChannelPoint_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_LightningAddress_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_LightningAddress_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_SendManyRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_SendManyRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_SendManyRequest_AddrToAmountEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_SendManyRequest_AddrToAmountEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_SendManyResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_SendManyResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_SendCoinsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_SendCoinsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_SendCoinsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_SendCoinsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_NewAddressRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_NewAddressRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_NewWitnessAddressRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_NewWitnessAddressRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_NewAddressResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_NewAddressResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_SignMessageRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_SignMessageRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_SignMessageResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_SignMessageResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_VerifyMessageRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_VerifyMessageRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_VerifyMessageResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_VerifyMessageResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_ConnectPeerRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_ConnectPeerRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_ConnectPeerResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_ConnectPeerResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_DisconnectPeerRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_DisconnectPeerRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_DisconnectPeerResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_DisconnectPeerResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_HTLC_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_HTLC_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_ActiveChannel_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_ActiveChannel_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_ListChannelsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_ListChannelsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_ListChannelsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_ListChannelsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_Peer_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_Peer_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_ListPeersRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_ListPeersRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_ListPeersResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_ListPeersResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_GetInfoRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_GetInfoRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_GetInfoResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_GetInfoResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_ConfirmationUpdate_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_ConfirmationUpdate_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_ChannelOpenUpdate_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_ChannelOpenUpdate_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_ChannelCloseUpdate_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_ChannelCloseUpdate_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_CloseChannelRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_CloseChannelRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_CloseStatusUpdate_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_CloseStatusUpdate_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_PendingUpdate_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_PendingUpdate_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_OpenChannelRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_OpenChannelRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_OpenStatusUpdate_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_OpenStatusUpdate_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_PendingHTLC_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_PendingHTLC_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_PendingChannelsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_PendingChannelsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_PendingChannelsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_PendingChannelsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_PendingChannelsResponse_PendingChannel_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_PendingChannelsResponse_PendingChannel_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_PendingChannelsResponse_PendingOpenChannel_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_PendingChannelsResponse_PendingOpenChannel_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_PendingChannelsResponse_ClosedChannel_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_PendingChannelsResponse_ClosedChannel_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_PendingChannelsResponse_ForceClosedChannel_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_PendingChannelsResponse_ForceClosedChannel_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_WalletBalanceRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_WalletBalanceRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_WalletBalanceResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_WalletBalanceResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_ChannelBalanceRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_ChannelBalanceRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_ChannelBalanceResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_ChannelBalanceResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_QueryRoutesRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_QueryRoutesRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_QueryRoutesResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_QueryRoutesResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_Hop_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_Hop_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_Route_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_Route_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_NodeInfoRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_NodeInfoRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_NodeInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_NodeInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_LightningNode_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_LightningNode_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_NodeAddress_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_NodeAddress_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_RoutingPolicy_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_RoutingPolicy_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_ChannelEdge_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_ChannelEdge_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_ChannelGraphRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_ChannelGraphRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_ChannelGraph_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_ChannelGraph_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_ChanInfoRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_ChanInfoRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_NetworkInfoRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_NetworkInfoRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_NetworkInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_NetworkInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_StopRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_StopRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_StopResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_StopResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_GraphTopologySubscription_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_GraphTopologySubscription_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_GraphTopologyUpdate_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_GraphTopologyUpdate_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_NodeUpdate_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_NodeUpdate_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_ChannelEdgeUpdate_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_ChannelEdgeUpdate_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_ClosedChannelUpdate_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_ClosedChannelUpdate_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_Invoice_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_Invoice_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_AddInvoiceResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_AddInvoiceResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_PaymentHash_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_PaymentHash_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_ListInvoiceRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_ListInvoiceRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_ListInvoiceResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_ListInvoiceResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_InvoiceSubscription_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_InvoiceSubscription_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_Payment_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_Payment_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_ListPaymentsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_ListPaymentsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_ListPaymentsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_ListPaymentsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_DeleteAllPaymentsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_DeleteAllPaymentsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_DeleteAllPaymentsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_DeleteAllPaymentsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_DebugLevelRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_DebugLevelRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_DebugLevelResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_DebugLevelResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_PayReqString_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_PayReqString_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_PayReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_PayReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_FeeReportRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_FeeReportRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_ChannelFeeReport_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_ChannelFeeReport_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_FeeReportResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_FeeReportResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_PolicyUpdateRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_PolicyUpdateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lnrpc_PolicyUpdateResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lnrpc_PolicyUpdateResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\trpc.proto\022\005lnrpc\032\034google/api/annotatio" +
      "ns.proto\"\'\n\023CreateWalletRequest\022\020\n\010passw" +
      "ord\030\001 \001(\014\"\026\n\024CreateWalletResponse\"\'\n\023Unl" +
      "ockWalletRequest\022\020\n\010password\030\001 \001(\014\"\026\n\024Un" +
      "lockWalletResponse\"\231\002\n\013Transaction\022\030\n\007tx" +
      "_hash\030\001 \001(\tR\007tx_hash\022\026\n\006amount\030\002 \001(\003R\006am" +
      "ount\022,\n\021num_confirmations\030\003 \001(\005R\021num_con" +
      "firmations\022\036\n\nblock_hash\030\004 \001(\tR\nblock_ha" +
      "sh\022\"\n\014block_height\030\005 \001(\005R\014block_height\022\036" +
      "\n\ntime_stamp\030\006 \001(\003R\ntime_stamp\022\036\n\ntotal_" +
      "fees\030\007 \001(\003R\ntotal_fees\022&\n\016dest_addresses" +
      "\030\010 \003(\tR\016dest_addresses\"\030\n\026GetTransaction" +
      "sRequest\"L\n\022TransactionDetails\0226\n\014transa" +
      "ctions\030\001 \003(\0132\022.lnrpc.TransactionR\014transa" +
      "ctions\"\243\001\n\013SendRequest\022\014\n\004dest\030\001 \001(\014\022\023\n\013" +
      "dest_string\030\002 \001(\t\022\013\n\003amt\030\003 \001(\003\022\024\n\014paymen" +
      "t_hash\030\004 \001(\014\022\033\n\023payment_hash_string\030\005 \001(" +
      "\t\022\027\n\017payment_request\030\006 \001(\t\022\030\n\020final_cltv" +
      "_delta\030\007 \001(\005\"\224\001\n\014SendResponse\022$\n\rpayment" +
      "_error\030\001 \001(\tR\rpayment_error\022*\n\020payment_p" +
      "reimage\030\002 \001(\014R\020payment_preimage\0222\n\rpayme" +
      "nt_route\030\003 \001(\0132\014.lnrpc.RouteR\rpayment_ro" +
      "ute\"\242\001\n\014ChannelPoint\0220\n\022funding_txid_byt" +
      "es\030\001 \001(\014H\000R\022funding_txid_bytes\022,\n\020fundin" +
      "g_txid_str\030\002 \001(\tH\000R\020funding_txid_str\022\"\n\014" +
      "output_index\030\003 \001(\rR\014output_indexB\016\n\014fund" +
      "ing_txid\">\n\020LightningAddress\022\026\n\006pubkey\030\001" +
      " \001(\tR\006pubkey\022\022\n\004host\030\002 \001(\tR\004host\"\261\001\n\017Sen" +
      "dManyRequest\022>\n\014AddrToAmount\030\001 \003(\0132(.lnr" +
      "pc.SendManyRequest.AddrToAmountEntry\022\023\n\013" +
      "target_conf\030\003 \001(\005\022\024\n\014sat_per_byte\030\005 \001(\003\032" +
      "3\n\021AddrToAmountEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005val" +
      "ue\030\002 \001(\003:\0028\001\"&\n\020SendManyResponse\022\022\n\004txid" +
      "\030\001 \001(\tR\004txid\"[\n\020SendCoinsRequest\022\014\n\004addr" +
      "\030\001 \001(\t\022\016\n\006amount\030\002 \001(\003\022\023\n\013target_conf\030\003 " +
      "\001(\005\022\024\n\014sat_per_byte\030\005 \001(\003\"\'\n\021SendCoinsRe" +
      "sponse\022\022\n\004txid\030\001 \001(\tR\004txid\"\230\001\n\021NewAddres" +
      "sRequest\0222\n\004type\030\001 \001(\0162$.lnrpc.NewAddres" +
      "sRequest.AddressType\"O\n\013AddressType\022\027\n\023W" +
      "ITNESS_PUBKEY_HASH\020\000\022\026\n\022NESTED_PUBKEY_HA" +
      "SH\020\001\022\017\n\013PUBKEY_HASH\020\002\"\032\n\030NewWitnessAddre" +
      "ssRequest\".\n\022NewAddressResponse\022\030\n\007addre" +
      "ss\030\001 \001(\tR\007address\"&\n\022SignMessageRequest\022" +
      "\020\n\003msg\030\001 \001(\014R\003msg\"3\n\023SignMessageResponse" +
      "\022\034\n\tsignature\030\001 \001(\tR\tsignature\"F\n\024Verify" +
      "MessageRequest\022\020\n\003msg\030\001 \001(\014R\003msg\022\034\n\tsign" +
      "ature\030\002 \001(\tR\tsignature\"E\n\025VerifyMessageR" +
      "esponse\022\024\n\005valid\030\001 \001(\010R\005valid\022\026\n\006pubkey\030" +
      "\002 \001(\tR\006pubkey\"I\n\022ConnectPeerRequest\022%\n\004a" +
      "ddr\030\001 \001(\0132\027.lnrpc.LightningAddress\022\014\n\004pe" +
      "rm\030\002 \001(\010\"\025\n\023ConnectPeerResponse\"1\n\025Disco" +
      "nnectPeerRequest\022\030\n\007pub_key\030\001 \001(\tR\007pub_k" +
      "ey\"\030\n\026DisconnectPeerResponse\"\206\001\n\004HTLC\022\032\n" +
      "\010incoming\030\001 \001(\010R\010incoming\022\026\n\006amount\030\002 \001(" +
      "\003R\006amount\022\034\n\thash_lock\030\003 \001(\014R\thash_lock\022" +
      ",\n\021expiration_height\030\004 \001(\rR\021expiration_h" +
      "eight\"\352\004\n\rActiveChannel\022\026\n\006active\030\001 \001(\010R" +
      "\006active\022$\n\rremote_pubkey\030\002 \001(\tR\rremote_p" +
      "ubkey\022$\n\rchannel_point\030\003 \001(\tR\rchannel_po" +
      "int\022\030\n\007chan_id\030\004 \001(\004R\007chan_id\022\032\n\010capacit" +
      "y\030\005 \001(\003R\010capacity\022$\n\rlocal_balance\030\006 \001(\003" +
      "R\rlocal_balance\022&\n\016remote_balance\030\007 \001(\003R" +
      "\016remote_balance\022\036\n\ncommit_fee\030\010 \001(\003R\ncom" +
      "mit_fee\022$\n\rcommit_weight\030\t \001(\003R\rcommit_w" +
      "eight\022\036\n\nfee_per_kw\030\n \001(\003R\nfee_per_kw\022,\n" +
      "\021unsettled_balance\030\013 \001(\003R\021unsettled_bala" +
      "nce\0220\n\023total_satoshis_sent\030\014 \001(\003R\023total_" +
      "satoshis_sent\0228\n\027total_satoshis_received" +
      "\030\r \001(\003R\027total_satoshis_received\022 \n\013num_u" +
      "pdates\030\016 \001(\004R\013num_updates\0221\n\rpending_htl" +
      "cs\030\017 \003(\0132\013.lnrpc.HTLCR\rpending_htlcs\022\034\n\t" +
      "csv_delay\030\020 \001(\rR\tcsv_delay\"\025\n\023ListChanne" +
      "lsRequest\"H\n\024ListChannelsResponse\0220\n\010cha" +
      "nnels\030\013 \003(\0132\024.lnrpc.ActiveChannelR\010chann" +
      "els\"\352\001\n\004Peer\022\030\n\007pub_key\030\001 \001(\tR\007pub_key\022\030" +
      "\n\007address\030\003 \001(\tR\007address\022\036\n\nbytes_sent\030\004" +
      " \001(\004R\nbytes_sent\022\036\n\nbytes_recv\030\005 \001(\004R\nby" +
      "tes_recv\022\032\n\010sat_sent\030\006 \001(\003R\010sat_sent\022\032\n\010" +
      "sat_recv\030\007 \001(\003R\010sat_recv\022\030\n\007inbound\030\010 \001(" +
      "\010R\007inbound\022\034\n\tping_time\030\t \001(\003R\tping_time" +
      "\"\022\n\020ListPeersRequest\"6\n\021ListPeersRespons" +
      "e\022!\n\005peers\030\001 \003(\0132\013.lnrpc.PeerR\005peers\"\020\n\016" +
      "GetInfoRequest\"\211\003\n\017GetInfoResponse\022(\n\017id" +
      "entity_pubkey\030\001 \001(\tR\017identity_pubkey\022\024\n\005" +
      "alias\030\002 \001(\tR\005alias\0222\n\024num_pending_channe" +
      "ls\030\003 \001(\rR\024num_pending_channels\0220\n\023num_ac" +
      "tive_channels\030\004 \001(\rR\023num_active_channels" +
      "\022\034\n\tnum_peers\030\005 \001(\rR\tnum_peers\022\"\n\014block_" +
      "height\030\006 \001(\rR\014block_height\022\036\n\nblock_hash" +
      "\030\010 \001(\tR\nblock_hash\022(\n\017synced_to_chain\030\t " +
      "\001(\010R\017synced_to_chain\022\030\n\007testnet\030\n \001(\010R\007t" +
      "estnet\022\026\n\006chains\030\013 \003(\tR\006chains\022\022\n\004uris\030\014" +
      " \003(\tR\004uris\"U\n\022ConfirmationUpdate\022\021\n\tbloc" +
      "k_sha\030\001 \001(\014\022\024\n\014block_height\030\002 \001(\005\022\026\n\016num" +
      "_confs_left\030\003 \001(\r\"N\n\021ChannelOpenUpdate\0229" +
      "\n\rchannel_point\030\001 \001(\0132\023.lnrpc.ChannelPoi" +
      "ntR\rchannel_point\"R\n\022ChannelCloseUpdate\022" +
      "\"\n\014closing_txid\030\001 \001(\014R\014closing_txid\022\030\n\007s" +
      "uccess\030\002 \001(\010R\007success\"{\n\023CloseChannelReq" +
      "uest\022*\n\rchannel_point\030\001 \001(\0132\023.lnrpc.Chan" +
      "nelPoint\022\r\n\005force\030\002 \001(\010\022\023\n\013target_conf\030\003" +
      " \001(\005\022\024\n\014sat_per_byte\030\004 \001(\003\"\331\001\n\021CloseStat" +
      "usUpdate\022<\n\rclose_pending\030\001 \001(\0132\024.lnrpc." +
      "PendingUpdateH\000R\rclose_pending\022?\n\014confir" +
      "mation\030\002 \001(\0132\031.lnrpc.ConfirmationUpdateH" +
      "\000R\014confirmation\022;\n\nchan_close\030\003 \001(\0132\031.ln" +
      "rpc.ChannelCloseUpdateH\000R\nchan_closeB\010\n\006" +
      "update\"G\n\rPendingUpdate\022\022\n\004txid\030\001 \001(\014R\004t" +
      "xid\022\"\n\014output_index\030\002 \001(\rR\014output_index\"" +
      "\241\002\n\022OpenChannelRequest\022 \n\013node_pubkey\030\002 " +
      "\001(\014R\013node_pubkey\022.\n\022node_pubkey_string\030\003" +
      " \001(\tR\022node_pubkey_string\0222\n\024local_fundin" +
      "g_amount\030\004 \001(\003R\024local_funding_amount\022\032\n\010" +
      "push_sat\030\005 \001(\003R\010push_sat\022\023\n\013target_conf\030" +
      "\006 \001(\005\022\024\n\014sat_per_byte\030\007 \001(\003\022\030\n\007private\030\010" +
      " \001(\010R\007private\022$\n\rmin_htlc_msat\030\t \001(\003R\rmi" +
      "n_htlc_msat\"\323\001\n\020OpenStatusUpdate\022:\n\014chan" +
      "_pending\030\001 \001(\0132\024.lnrpc.PendingUpdateH\000R\014" +
      "chan_pending\022?\n\014confirmation\030\002 \001(\0132\031.lnr" +
      "pc.ConfirmationUpdateH\000R\014confirmation\0228\n" +
      "\tchan_open\030\003 \001(\0132\030.lnrpc.ChannelOpenUpda" +
      "teH\000R\tchan_openB\010\n\006update\"\317\001\n\013PendingHTL" +
      "C\022\032\n\010incoming\030\001 \001(\010R\010incoming\022\026\n\006amount\030" +
      "\002 \001(\003R\006amount\022\032\n\010outpoint\030\003 \001(\tR\010outpoin" +
      "t\022(\n\017maturity_height\030\004 \001(\rR\017maturity_hei" +
      "ght\0220\n\023blocks_til_maturity\030\005 \001(\005R\023blocks" +
      "_til_maturity\022\024\n\005stage\030\006 \001(\rR\005stage\"\030\n\026P" +
      "endingChannelsRequest\"\301\n\n\027PendingChannel" +
      "sResponse\0220\n\023total_limbo_balance\030\001 \001(\003R\023" +
      "total_limbo_balance\022g\n\025pending_open_chan" +
      "nels\030\002 \003(\01321.lnrpc.PendingChannelsRespon" +
      "se.PendingOpenChannelR\025pending_open_chan" +
      "nels\022h\n\030pending_closing_channels\030\003 \003(\0132," +
      ".lnrpc.PendingChannelsResponse.ClosedCha" +
      "nnelR\030pending_closing_channels\022y\n\036pendin" +
      "g_force_closing_channels\030\004 \003(\01321.lnrpc.P" +
      "endingChannelsResponse.ForceClosedChanne" +
      "lR\036pending_force_closing_channels\032\312\001\n\016Pe" +
      "ndingChannel\022(\n\017remote_node_pub\030\001 \001(\tR\017r" +
      "emote_node_pub\022$\n\rchannel_point\030\002 \001(\tR\rc" +
      "hannel_point\022\032\n\010capacity\030\003 \001(\003R\010capacity" +
      "\022$\n\rlocal_balance\030\004 \001(\003R\rlocal_balance\022&" +
      "\n\016remote_balance\030\005 \001(\003R\016remote_balance\032\365" +
      "\001\n\022PendingOpenChannel\022G\n\007channel\030\001 \001(\0132-" +
      ".lnrpc.PendingChannelsResponse.PendingCh" +
      "annelR\007channel\0220\n\023confirmation_height\030\002 " +
      "\001(\rR\023confirmation_height\022\036\n\ncommit_fee\030\004" +
      " \001(\003R\ncommit_fee\022$\n\rcommit_weight\030\005 \001(\003R" +
      "\rcommit_weight\022\036\n\nfee_per_kw\030\006 \001(\003R\nfee_" +
      "per_kw\032s\n\rClosedChannel\022>\n\007channel\030\001 \001(\013" +
      "2-.lnrpc.PendingChannelsResponse.Pending" +
      "Channel\022\"\n\014closing_txid\030\002 \001(\tR\014closing_t" +
      "xid\032\353\002\n\022ForceClosedChannel\022G\n\007channel\030\001 " +
      "\001(\0132-.lnrpc.PendingChannelsResponse.Pend" +
      "ingChannelR\007channel\022\"\n\014closing_txid\030\002 \001(" +
      "\tR\014closing_txid\022$\n\rlimbo_balance\030\003 \001(\003R\r" +
      "limbo_balance\022(\n\017maturity_height\030\004 \001(\rR\017" +
      "maturity_height\0220\n\023blocks_til_maturity\030\005" +
      " \001(\005R\023blocks_til_maturity\022,\n\021recovered_b" +
      "alance\030\006 \001(\003R\021recovered_balance\0228\n\rpendi" +
      "ng_htlcs\030\010 \003(\0132\022.lnrpc.PendingHTLCR\rpend" +
      "ing_htlcs\",\n\024WalletBalanceRequest\022\024\n\014wit" +
      "ness_only\030\001 \001(\010\"\235\001\n\025WalletBalanceRespons" +
      "e\022$\n\rtotal_balance\030\001 \001(\003R\rtotal_balance\022" +
      ",\n\021confirmed_balance\030\002 \001(\003R\021confirmed_ba" +
      "lance\0220\n\023unconfirmed_balance\030\003 \001(\003R\023unco" +
      "nfirmed_balance\"\027\n\025ChannelBalanceRequest" +
      "\"2\n\026ChannelBalanceResponse\022\030\n\007balance\030\001 " +
      "\001(\003R\007balance\"F\n\022QueryRoutesRequest\022\017\n\007pu" +
      "b_key\030\001 \001(\t\022\013\n\003amt\030\002 \001(\003\022\022\n\nnum_routes\030\003" +
      " \001(\005\";\n\023QueryRoutesResponse\022$\n\006routes\030\001 " +
      "\003(\0132\014.lnrpc.RouteR\006routes\"\227\001\n\003Hop\022\030\n\007cha" +
      "n_id\030\001 \001(\004R\007chan_id\022$\n\rchan_capacity\030\002 \001" +
      "(\003R\rchan_capacity\022&\n\016amt_to_forward\030\003 \001(" +
      "\003R\016amt_to_forward\022\020\n\003fee\030\004 \001(\003R\003fee\022\026\n\006e" +
      "xpiry\030\005 \001(\rR\006expiry\"\217\001\n\005Route\022(\n\017total_t" +
      "ime_lock\030\001 \001(\rR\017total_time_lock\022\036\n\ntotal" +
      "_fees\030\002 \001(\003R\ntotal_fees\022\034\n\ttotal_amt\030\003 \001" +
      "(\003R\ttotal_amt\022\036\n\004hops\030\004 \003(\0132\n.lnrpc.HopR" +
      "\004hops\"\"\n\017NodeInfoRequest\022\017\n\007pub_key\030\001 \001(" +
      "\t\"\200\001\n\010NodeInfo\022(\n\004node\030\001 \001(\0132\024.lnrpc.Lig" +
      "htningNodeR\004node\022\"\n\014num_channels\030\002 \001(\rR\014" +
      "num_channels\022&\n\016total_capacity\030\003 \001(\003R\016to" +
      "tal_capacity\"\251\001\n\rLightningNode\022 \n\013last_u" +
      "pdate\030\001 \001(\rR\013last_update\022\030\n\007pub_key\030\002 \001(" +
      "\tR\007pub_key\022\024\n\005alias\030\003 \001(\tR\005alias\0220\n\taddr" +
      "esses\030\004 \003(\0132\022.lnrpc.NodeAddressR\taddress" +
      "es\022\024\n\005color\030\005 \001(\tR\005color\";\n\013NodeAddress\022" +
      "\030\n\007network\030\001 \001(\tR\007network\022\022\n\004addr\030\002 \001(\tR" +
      "\004addr\"\255\001\n\rRoutingPolicy\022(\n\017time_lock_del" +
      "ta\030\001 \001(\rR\017time_lock_delta\022\032\n\010min_htlc\030\002 " +
      "\001(\003R\010min_htlc\022$\n\rfee_base_msat\030\003 \001(\003R\rfe" +
      "e_base_msat\0220\n\023fee_rate_milli_msat\030\004 \001(\003" +
      "R\023fee_rate_milli_msat\"\273\002\n\013ChannelEdge\022\036\n" +
      "\nchannel_id\030\001 \001(\004R\nchannel_id\022\036\n\nchan_po" +
      "int\030\002 \001(\tR\nchan_point\022 \n\013last_update\030\003 \001" +
      "(\rR\013last_update\022\034\n\tnode1_pub\030\004 \001(\tR\tnode" +
      "1_pub\022\034\n\tnode2_pub\030\005 \001(\tR\tnode2_pub\022\032\n\010c" +
      "apacity\030\006 \001(\003R\010capacity\0228\n\014node1_policy\030" +
      "\007 \001(\0132\024.lnrpc.RoutingPolicyR\014node1_polic" +
      "y\0228\n\014node2_policy\030\010 \001(\0132\024.lnrpc.RoutingP" +
      "olicyR\014node2_policy\"\025\n\023ChannelGraphReque" +
      "st\"d\n\014ChannelGraph\022*\n\005nodes\030\001 \003(\0132\024.lnrp" +
      "c.LightningNodeR\005nodes\022(\n\005edges\030\002 \003(\0132\022." +
      "lnrpc.ChannelEdgeR\005edges\"\"\n\017ChanInfoRequ" +
      "est\022\017\n\007chan_id\030\001 \001(\004\"\024\n\022NetworkInfoReque" +
      "st\"\203\003\n\013NetworkInfo\022&\n\016graph_diameter\030\001 \001" +
      "(\rR\016graph_diameter\022&\n\016avg_out_degree\030\002 \001" +
      "(\001R\016avg_out_degree\022&\n\016max_out_degree\030\003 \001" +
      "(\rR\016max_out_degree\022\034\n\tnum_nodes\030\004 \001(\rR\tn" +
      "um_nodes\022\"\n\014num_channels\030\005 \001(\rR\014num_chan" +
      "nels\0226\n\026total_network_capacity\030\006 \001(\003R\026to" +
      "tal_network_capacity\022*\n\020avg_channel_size" +
      "\030\007 \001(\001R\020avg_channel_size\022*\n\020min_channel_" +
      "size\030\010 \001(\003R\020min_channel_size\022*\n\020max_chan" +
      "nel_size\030\t \001(\003R\020max_channel_size\"\r\n\013Stop" +
      "Request\"\016\n\014StopResponse\"\033\n\031GraphTopology" +
      "Subscription\"\243\001\n\023GraphTopologyUpdate\022\'\n\014" +
      "node_updates\030\001 \003(\0132\021.lnrpc.NodeUpdate\0221\n" +
      "\017channel_updates\030\002 \003(\0132\030.lnrpc.ChannelEd" +
      "geUpdate\0220\n\014closed_chans\030\003 \003(\0132\032.lnrpc.C" +
      "losedChannelUpdate\"]\n\nNodeUpdate\022\021\n\taddr" +
      "esses\030\001 \003(\t\022\024\n\014identity_key\030\002 \001(\t\022\027\n\017glo" +
      "bal_features\030\003 \001(\014\022\r\n\005alias\030\004 \001(\t\"\300\001\n\021Ch" +
      "annelEdgeUpdate\022\017\n\007chan_id\030\001 \001(\004\022\'\n\nchan" +
      "_point\030\002 \001(\0132\023.lnrpc.ChannelPoint\022\020\n\010cap" +
      "acity\030\003 \001(\003\022,\n\016routing_policy\030\004 \001(\0132\024.ln" +
      "rpc.RoutingPolicy\022\030\n\020advertising_node\030\005 " +
      "\001(\t\022\027\n\017connecting_node\030\006 \001(\t\"x\n\023ClosedCh" +
      "annelUpdate\022\017\n\007chan_id\030\001 \001(\004\022\020\n\010capacity" +
      "\030\002 \001(\003\022\025\n\rclosed_height\030\003 \001(\r\022\'\n\nchan_po" +
      "int\030\004 \001(\0132\023.lnrpc.ChannelPoint\"\235\003\n\007Invoi" +
      "ce\022\022\n\004memo\030\001 \001(\tR\004memo\022\030\n\007receipt\030\002 \001(\014R" +
      "\007receipt\022\036\n\nr_preimage\030\003 \001(\014R\nr_preimage" +
      "\022\026\n\006r_hash\030\004 \001(\014R\006r_hash\022\024\n\005value\030\005 \001(\003R" +
      "\005value\022\030\n\007settled\030\006 \001(\010R\007settled\022$\n\rcrea" +
      "tion_date\030\007 \001(\003R\rcreation_date\022 \n\013settle" +
      "_date\030\010 \001(\003R\013settle_date\022(\n\017payment_requ" +
      "est\030\t \001(\tR\017payment_request\022*\n\020descriptio" +
      "n_hash\030\n \001(\014R\020description_hash\022\026\n\006expiry" +
      "\030\013 \001(\003R\006expiry\022$\n\rfallback_addr\030\014 \001(\tR\rf" +
      "allback_addr\022 \n\013cltv_expiry\030\r \001(\004R\013cltv_" +
      "expiry\"V\n\022AddInvoiceResponse\022\026\n\006r_hash\030\001" +
      " \001(\014R\006r_hash\022(\n\017payment_request\030\002 \001(\tR\017p" +
      "ayment_request\"E\n\013PaymentHash\022\036\n\nr_hash_" +
      "str\030\001 \001(\tR\nr_hash_str\022\026\n\006r_hash\030\002 \001(\014R\006r" +
      "_hash\"*\n\022ListInvoiceRequest\022\024\n\014pending_o" +
      "nly\030\001 \001(\010\"A\n\023ListInvoiceResponse\022*\n\010invo" +
      "ices\030\001 \003(\0132\016.lnrpc.InvoiceR\010invoices\"\025\n\023" +
      "InvoiceSubscription\"\273\001\n\007Payment\022\"\n\014payme" +
      "nt_hash\030\001 \001(\tR\014payment_hash\022\024\n\005value\030\002 \001" +
      "(\003R\005value\022$\n\rcreation_date\030\003 \001(\003R\rcreati" +
      "on_date\022\022\n\004path\030\004 \003(\tR\004path\022\020\n\003fee\030\005 \001(\003" +
      "R\003fee\022*\n\020payment_preimage\030\006 \001(\tR\020payment" +
      "_preimage\"\025\n\023ListPaymentsRequest\"B\n\024List" +
      "PaymentsResponse\022*\n\010payments\030\001 \003(\0132\016.lnr" +
      "pc.PaymentR\010payments\"\032\n\030DeleteAllPayment" +
      "sRequest\"\033\n\031DeleteAllPaymentsResponse\"5\n" +
      "\021DebugLevelRequest\022\014\n\004show\030\001 \001(\010\022\022\n\nleve" +
      "l_spec\030\002 \001(\t\"6\n\022DebugLevelResponse\022 \n\013su" +
      "b_systems\030\001 \001(\tR\013sub_systems\"\037\n\014PayReqSt" +
      "ring\022\017\n\007pay_req\030\001 \001(\t\"\276\002\n\006PayReq\022 \n\013dest" +
      "ination\030\001 \001(\tR\013destination\022\"\n\014payment_ha" +
      "sh\030\002 \001(\tR\014payment_hash\022\"\n\014num_satoshis\030\003" +
      " \001(\003R\014num_satoshis\022\034\n\ttimestamp\030\004 \001(\003R\tt" +
      "imestamp\022\026\n\006expiry\030\005 \001(\003R\006expiry\022 \n\013desc" +
      "ription\030\006 \001(\tR\013description\022*\n\020descriptio" +
      "n_hash\030\007 \001(\tR\020description_hash\022$\n\rfallba" +
      "ck_addr\030\010 \001(\tR\rfallback_addr\022 \n\013cltv_exp" +
      "iry\030\t \001(\003R\013cltv_expiry\"\022\n\020FeeReportReque" +
      "st\"\231\001\n\020ChannelFeeReport\022!\n\nchan_point\030\001 " +
      "\001(\tR\rchannel_point\022$\n\rbase_fee_msat\030\002 \001(" +
      "\003R\rbase_fee_msat\022 \n\013fee_per_mil\030\003 \001(\003R\013f" +
      "ee_per_mil\022\032\n\010fee_rate\030\004 \001(\001R\010fee_rate\"P" +
      "\n\021FeeReportResponse\022;\n\014channel_fees\030\001 \003(" +
      "\0132\027.lnrpc.ChannelFeeReportR\014channel_fees" +
      "\"\333\001\n\023PolicyUpdateRequest\022\030\n\006global\030\001 \001(\010" +
      "H\000R\006global\0225\n\nchan_point\030\002 \001(\0132\023.lnrpc.C" +
      "hannelPointH\000R\nchan_point\022$\n\rbase_fee_ms" +
      "at\030\003 \001(\003R\rbase_fee_msat\022\032\n\010fee_rate\030\004 \001(" +
      "\001R\010fee_rate\022(\n\017time_lock_delta\030\005 \001(\rR\017ti" +
      "me_lock_deltaB\007\n\005scope\"\026\n\024PolicyUpdateRe" +
      "sponse2\334\001\n\016WalletUnlocker\022d\n\014CreateWalle" +
      "t\022\032.lnrpc.CreateWalletRequest\032\033.lnrpc.Cr" +
      "eateWalletResponse\"\033\202\323\344\223\002\025\"\020/v1/createwa" +
      "llet:\001*\022d\n\014UnlockWallet\022\032.lnrpc.UnlockWa" +
      "lletRequest\032\033.lnrpc.UnlockWalletResponse" +
      "\"\033\202\323\344\223\002\025\"\020/v1/unlockwallet:\001*2\363\032\n\tLightn" +
      "ing\022j\n\rWalletBalance\022\033.lnrpc.WalletBalan" +
      "ceRequest\032\034.lnrpc.WalletBalanceResponse\"" +
      "\036\202\323\344\223\002\030\022\026/v1/balance/blockchain\022k\n\016Chann" +
      "elBalance\022\034.lnrpc.ChannelBalanceRequest\032" +
      "\035.lnrpc.ChannelBalanceResponse\"\034\202\323\344\223\002\026\022\024" +
      "/v1/balance/channels\022e\n\017GetTransactions\022" +
      "\035.lnrpc.GetTransactionsRequest\032\031.lnrpc.T" +
      "ransactionDetails\"\030\202\323\344\223\002\022\022\020/v1/transacti" +
      "ons\022[\n\tSendCoins\022\027.lnrpc.SendCoinsReques" +
      "t\032\030.lnrpc.SendCoinsResponse\"\033\202\323\344\223\002\025\"\020/v1" +
      "/transactions:\001*\022L\n\025SubscribeTransaction" +
      "s\022\035.lnrpc.GetTransactionsRequest\032\022.lnrpc" +
      ".Transaction0\001\022;\n\010SendMany\022\026.lnrpc.SendM" +
      "anyRequest\032\027.lnrpc.SendManyResponse\022A\n\nN" +
      "ewAddress\022\030.lnrpc.NewAddressRequest\032\031.ln" +
      "rpc.NewAddressResponse\022g\n\021NewWitnessAddr" +
      "ess\022\037.lnrpc.NewWitnessAddressRequest\032\031.l" +
      "nrpc.NewAddressResponse\"\026\202\323\344\223\002\020\022\016/v1/new" +
      "address\022D\n\013SignMessage\022\031.lnrpc.SignMessa" +
      "geRequest\032\032.lnrpc.SignMessageResponse\022J\n" +
      "\rVerifyMessage\022\033.lnrpc.VerifyMessageRequ" +
      "est\032\034.lnrpc.VerifyMessageResponse\022Z\n\013Con" +
      "nectPeer\022\031.lnrpc.ConnectPeerRequest\032\032.ln" +
      "rpc.ConnectPeerResponse\"\024\202\323\344\223\002\016\"\t/v1/pee" +
      "rs:\001*\022j\n\016DisconnectPeer\022\034.lnrpc.Disconne" +
      "ctPeerRequest\032\035.lnrpc.DisconnectPeerResp" +
      "onse\"\033\202\323\344\223\002\025*\023/v1/peers/{pub_key}\022Q\n\tLis" +
      "tPeers\022\027.lnrpc.ListPeersRequest\032\030.lnrpc." +
      "ListPeersResponse\"\021\202\323\344\223\002\013\022\t/v1/peers\022M\n\007" +
      "GetInfo\022\025.lnrpc.GetInfoRequest\032\026.lnrpc.G" +
      "etInfoResponse\"\023\202\323\344\223\002\r\022\013/v1/getinfo\022n\n\017P" +
      "endingChannels\022\035.lnrpc.PendingChannelsRe" +
      "quest\032\036.lnrpc.PendingChannelsResponse\"\034\202" +
      "\323\344\223\002\026\022\024/v1/channels/pending\022]\n\014ListChann" +
      "els\022\032.lnrpc.ListChannelsRequest\032\033.lnrpc." +
      "ListChannelsResponse\"\024\202\323\344\223\002\016\022\014/v1/channe" +
      "ls\022Z\n\017OpenChannelSync\022\031.lnrpc.OpenChanne" +
      "lRequest\032\023.lnrpc.ChannelPoint\"\027\202\323\344\223\002\021\"\014/" +
      "v1/channels:\001*\022C\n\013OpenChannel\022\031.lnrpc.Op" +
      "enChannelRequest\032\027.lnrpc.OpenStatusUpdat" +
      "e0\001\022\232\001\n\014CloseChannel\022\032.lnrpc.CloseChanne" +
      "lRequest\032\030.lnrpc.CloseStatusUpdate\"R\202\323\344\223" +
      "\002L*J/v1/channels/{channel_point.funding_" +
      "txid_str}/{channel_point.output_index}0\001" +
      "\022:\n\013SendPayment\022\022.lnrpc.SendRequest\032\023.ln" +
      "rpc.SendResponse(\0010\001\022`\n\017SendPaymentSync\022" +
      "\022.lnrpc.SendRequest\032\023.lnrpc.SendResponse" +
      "\"$\202\323\344\223\002\036\"\031/v1/channels/transactions:\001*\022P" +
      "\n\nAddInvoice\022\016.lnrpc.Invoice\032\031.lnrpc.Add" +
      "InvoiceResponse\"\027\202\323\344\223\002\021\"\014/v1/invoices:\001*" +
      "\022[\n\014ListInvoices\022\031.lnrpc.ListInvoiceRequ" +
      "est\032\032.lnrpc.ListInvoiceResponse\"\024\202\323\344\223\002\016\022" +
      "\014/v1/invoices\022U\n\rLookupInvoice\022\022.lnrpc.P" +
      "aymentHash\032\016.lnrpc.Invoice\" \202\323\344\223\002\032\022\030/v1/" +
      "invoice/{r_hash_str}\022a\n\021SubscribeInvoice" +
      "s\022\032.lnrpc.InvoiceSubscription\032\016.lnrpc.In" +
      "voice\"\036\202\323\344\223\002\030\022\026/v1/invoices/subscribe0\001\022" +
      "P\n\014DecodePayReq\022\023.lnrpc.PayReqString\032\r.l" +
      "nrpc.PayReq\"\034\202\323\344\223\002\026\022\024/v1/payreq/{pay_req" +
      "}\022]\n\014ListPayments\022\032.lnrpc.ListPaymentsRe" +
      "quest\032\033.lnrpc.ListPaymentsResponse\"\024\202\323\344\223" +
      "\002\016\022\014/v1/payments\022l\n\021DeleteAllPayments\022\037." +
      "lnrpc.DeleteAllPaymentsRequest\032 .lnrpc.D" +
      "eleteAllPaymentsResponse\"\024\202\323\344\223\002\016*\014/v1/pa" +
      "yments\022S\n\rDescribeGraph\022\032.lnrpc.ChannelG" +
      "raphRequest\032\023.lnrpc.ChannelGraph\"\021\202\323\344\223\002\013" +
      "\022\t/v1/graph\022[\n\013GetChanInfo\022\026.lnrpc.ChanI" +
      "nfoRequest\032\022.lnrpc.ChannelEdge\" \202\323\344\223\002\032\022\030" +
      "/v1/graph/edge/{chan_id}\022X\n\013GetNodeInfo\022" +
      "\026.lnrpc.NodeInfoRequest\032\017.lnrpc.NodeInfo" +
      "\" \202\323\344\223\002\032\022\030/v1/graph/node/{pub_key}\022n\n\013Qu" +
      "eryRoutes\022\031.lnrpc.QueryRoutesRequest\032\032.l" +
      "nrpc.QueryRoutesResponse\"(\202\323\344\223\002\"\022 /v1/gr" +
      "aph/routes/{pub_key}/{amt}\022W\n\016GetNetwork" +
      "Info\022\031.lnrpc.NetworkInfoRequest\032\022.lnrpc." +
      "NetworkInfo\"\026\202\323\344\223\002\020\022\016/v1/graph/info\0225\n\nS" +
      "topDaemon\022\022.lnrpc.StopRequest\032\023.lnrpc.St" +
      "opResponse\022W\n\025SubscribeChannelGraph\022 .ln" +
      "rpc.GraphTopologySubscription\032\032.lnrpc.Gr" +
      "aphTopologyUpdate0\001\022A\n\nDebugLevel\022\030.lnrp" +
      "c.DebugLevelRequest\032\031.lnrpc.DebugLevelRe" +
      "sponse\022P\n\tFeeReport\022\027.lnrpc.FeeReportReq" +
      "uest\032\030.lnrpc.FeeReportResponse\"\020\202\323\344\223\002\n\022\010" +
      "/v1/fees\022i\n\023UpdateChannelPolicy\022\032.lnrpc." +
      "PolicyUpdateRequest\032\033.lnrpc.PolicyUpdate" +
      "Response\"\031\202\323\344\223\002\023\"\016/v1/chanpolicy:\001*B\025\n\021l" +
      "ightpay.lnd.grpcP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.api.AnnotationsProto.getDescriptor(),
        }, assigner);
    internal_static_lnrpc_CreateWalletRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_lnrpc_CreateWalletRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_CreateWalletRequest_descriptor,
        new java.lang.String[] { "Password", });
    internal_static_lnrpc_CreateWalletResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_lnrpc_CreateWalletResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_CreateWalletResponse_descriptor,
        new java.lang.String[] { });
    internal_static_lnrpc_UnlockWalletRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_lnrpc_UnlockWalletRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_UnlockWalletRequest_descriptor,
        new java.lang.String[] { "Password", });
    internal_static_lnrpc_UnlockWalletResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_lnrpc_UnlockWalletResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_UnlockWalletResponse_descriptor,
        new java.lang.String[] { });
    internal_static_lnrpc_Transaction_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_lnrpc_Transaction_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_Transaction_descriptor,
        new java.lang.String[] { "TxHash", "Amount", "NumConfirmations", "BlockHash", "BlockHeight", "TimeStamp", "TotalFees", "DestAddresses", });
    internal_static_lnrpc_GetTransactionsRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_lnrpc_GetTransactionsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_GetTransactionsRequest_descriptor,
        new java.lang.String[] { });
    internal_static_lnrpc_TransactionDetails_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_lnrpc_TransactionDetails_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_TransactionDetails_descriptor,
        new java.lang.String[] { "Transactions", });
    internal_static_lnrpc_SendRequest_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_lnrpc_SendRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_SendRequest_descriptor,
        new java.lang.String[] { "Dest", "DestString", "Amt", "PaymentHash", "PaymentHashString", "PaymentRequest", "FinalCltvDelta", });
    internal_static_lnrpc_SendResponse_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_lnrpc_SendResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_SendResponse_descriptor,
        new java.lang.String[] { "PaymentError", "PaymentPreimage", "PaymentRoute", });
    internal_static_lnrpc_ChannelPoint_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_lnrpc_ChannelPoint_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_ChannelPoint_descriptor,
        new java.lang.String[] { "FundingTxidBytes", "FundingTxidStr", "OutputIndex", "FundingTxid", });
    internal_static_lnrpc_LightningAddress_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_lnrpc_LightningAddress_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_LightningAddress_descriptor,
        new java.lang.String[] { "Pubkey", "Host", });
    internal_static_lnrpc_SendManyRequest_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_lnrpc_SendManyRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_SendManyRequest_descriptor,
        new java.lang.String[] { "AddrToAmount", "TargetConf", "SatPerByte", });
    internal_static_lnrpc_SendManyRequest_AddrToAmountEntry_descriptor =
      internal_static_lnrpc_SendManyRequest_descriptor.getNestedTypes().get(0);
    internal_static_lnrpc_SendManyRequest_AddrToAmountEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_SendManyRequest_AddrToAmountEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_lnrpc_SendManyResponse_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_lnrpc_SendManyResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_SendManyResponse_descriptor,
        new java.lang.String[] { "Txid", });
    internal_static_lnrpc_SendCoinsRequest_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_lnrpc_SendCoinsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_SendCoinsRequest_descriptor,
        new java.lang.String[] { "Addr", "Amount", "TargetConf", "SatPerByte", });
    internal_static_lnrpc_SendCoinsResponse_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_lnrpc_SendCoinsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_SendCoinsResponse_descriptor,
        new java.lang.String[] { "Txid", });
    internal_static_lnrpc_NewAddressRequest_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_lnrpc_NewAddressRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_NewAddressRequest_descriptor,
        new java.lang.String[] { "Type", });
    internal_static_lnrpc_NewWitnessAddressRequest_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_lnrpc_NewWitnessAddressRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_NewWitnessAddressRequest_descriptor,
        new java.lang.String[] { });
    internal_static_lnrpc_NewAddressResponse_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_lnrpc_NewAddressResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_NewAddressResponse_descriptor,
        new java.lang.String[] { "Address", });
    internal_static_lnrpc_SignMessageRequest_descriptor =
      getDescriptor().getMessageTypes().get(18);
    internal_static_lnrpc_SignMessageRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_SignMessageRequest_descriptor,
        new java.lang.String[] { "Msg", });
    internal_static_lnrpc_SignMessageResponse_descriptor =
      getDescriptor().getMessageTypes().get(19);
    internal_static_lnrpc_SignMessageResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_SignMessageResponse_descriptor,
        new java.lang.String[] { "Signature", });
    internal_static_lnrpc_VerifyMessageRequest_descriptor =
      getDescriptor().getMessageTypes().get(20);
    internal_static_lnrpc_VerifyMessageRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_VerifyMessageRequest_descriptor,
        new java.lang.String[] { "Msg", "Signature", });
    internal_static_lnrpc_VerifyMessageResponse_descriptor =
      getDescriptor().getMessageTypes().get(21);
    internal_static_lnrpc_VerifyMessageResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_VerifyMessageResponse_descriptor,
        new java.lang.String[] { "Valid", "Pubkey", });
    internal_static_lnrpc_ConnectPeerRequest_descriptor =
      getDescriptor().getMessageTypes().get(22);
    internal_static_lnrpc_ConnectPeerRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_ConnectPeerRequest_descriptor,
        new java.lang.String[] { "Addr", "Perm", });
    internal_static_lnrpc_ConnectPeerResponse_descriptor =
      getDescriptor().getMessageTypes().get(23);
    internal_static_lnrpc_ConnectPeerResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_ConnectPeerResponse_descriptor,
        new java.lang.String[] { });
    internal_static_lnrpc_DisconnectPeerRequest_descriptor =
      getDescriptor().getMessageTypes().get(24);
    internal_static_lnrpc_DisconnectPeerRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_DisconnectPeerRequest_descriptor,
        new java.lang.String[] { "PubKey", });
    internal_static_lnrpc_DisconnectPeerResponse_descriptor =
      getDescriptor().getMessageTypes().get(25);
    internal_static_lnrpc_DisconnectPeerResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_DisconnectPeerResponse_descriptor,
        new java.lang.String[] { });
    internal_static_lnrpc_HTLC_descriptor =
      getDescriptor().getMessageTypes().get(26);
    internal_static_lnrpc_HTLC_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_HTLC_descriptor,
        new java.lang.String[] { "Incoming", "Amount", "HashLock", "ExpirationHeight", });
    internal_static_lnrpc_ActiveChannel_descriptor =
      getDescriptor().getMessageTypes().get(27);
    internal_static_lnrpc_ActiveChannel_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_ActiveChannel_descriptor,
        new java.lang.String[] { "Active", "RemotePubkey", "ChannelPoint", "ChanId", "Capacity", "LocalBalance", "RemoteBalance", "CommitFee", "CommitWeight", "FeePerKw", "UnsettledBalance", "TotalSatoshisSent", "TotalSatoshisReceived", "NumUpdates", "PendingHtlcs", "CsvDelay", });
    internal_static_lnrpc_ListChannelsRequest_descriptor =
      getDescriptor().getMessageTypes().get(28);
    internal_static_lnrpc_ListChannelsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_ListChannelsRequest_descriptor,
        new java.lang.String[] { });
    internal_static_lnrpc_ListChannelsResponse_descriptor =
      getDescriptor().getMessageTypes().get(29);
    internal_static_lnrpc_ListChannelsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_ListChannelsResponse_descriptor,
        new java.lang.String[] { "Channels", });
    internal_static_lnrpc_Peer_descriptor =
      getDescriptor().getMessageTypes().get(30);
    internal_static_lnrpc_Peer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_Peer_descriptor,
        new java.lang.String[] { "PubKey", "Address", "BytesSent", "BytesRecv", "SatSent", "SatRecv", "Inbound", "PingTime", });
    internal_static_lnrpc_ListPeersRequest_descriptor =
      getDescriptor().getMessageTypes().get(31);
    internal_static_lnrpc_ListPeersRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_ListPeersRequest_descriptor,
        new java.lang.String[] { });
    internal_static_lnrpc_ListPeersResponse_descriptor =
      getDescriptor().getMessageTypes().get(32);
    internal_static_lnrpc_ListPeersResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_ListPeersResponse_descriptor,
        new java.lang.String[] { "Peers", });
    internal_static_lnrpc_GetInfoRequest_descriptor =
      getDescriptor().getMessageTypes().get(33);
    internal_static_lnrpc_GetInfoRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_GetInfoRequest_descriptor,
        new java.lang.String[] { });
    internal_static_lnrpc_GetInfoResponse_descriptor =
      getDescriptor().getMessageTypes().get(34);
    internal_static_lnrpc_GetInfoResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_GetInfoResponse_descriptor,
        new java.lang.String[] { "IdentityPubkey", "Alias", "NumPendingChannels", "NumActiveChannels", "NumPeers", "BlockHeight", "BlockHash", "SyncedToChain", "Testnet", "Chains", "Uris", });
    internal_static_lnrpc_ConfirmationUpdate_descriptor =
      getDescriptor().getMessageTypes().get(35);
    internal_static_lnrpc_ConfirmationUpdate_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_ConfirmationUpdate_descriptor,
        new java.lang.String[] { "BlockSha", "BlockHeight", "NumConfsLeft", });
    internal_static_lnrpc_ChannelOpenUpdate_descriptor =
      getDescriptor().getMessageTypes().get(36);
    internal_static_lnrpc_ChannelOpenUpdate_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_ChannelOpenUpdate_descriptor,
        new java.lang.String[] { "ChannelPoint", });
    internal_static_lnrpc_ChannelCloseUpdate_descriptor =
      getDescriptor().getMessageTypes().get(37);
    internal_static_lnrpc_ChannelCloseUpdate_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_ChannelCloseUpdate_descriptor,
        new java.lang.String[] { "ClosingTxid", "Success", });
    internal_static_lnrpc_CloseChannelRequest_descriptor =
      getDescriptor().getMessageTypes().get(38);
    internal_static_lnrpc_CloseChannelRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_CloseChannelRequest_descriptor,
        new java.lang.String[] { "ChannelPoint", "Force", "TargetConf", "SatPerByte", });
    internal_static_lnrpc_CloseStatusUpdate_descriptor =
      getDescriptor().getMessageTypes().get(39);
    internal_static_lnrpc_CloseStatusUpdate_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_CloseStatusUpdate_descriptor,
        new java.lang.String[] { "ClosePending", "Confirmation", "ChanClose", "Update", });
    internal_static_lnrpc_PendingUpdate_descriptor =
      getDescriptor().getMessageTypes().get(40);
    internal_static_lnrpc_PendingUpdate_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_PendingUpdate_descriptor,
        new java.lang.String[] { "Txid", "OutputIndex", });
    internal_static_lnrpc_OpenChannelRequest_descriptor =
      getDescriptor().getMessageTypes().get(41);
    internal_static_lnrpc_OpenChannelRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_OpenChannelRequest_descriptor,
        new java.lang.String[] { "NodePubkey", "NodePubkeyString", "LocalFundingAmount", "PushSat", "TargetConf", "SatPerByte", "Private", "MinHtlcMsat", });
    internal_static_lnrpc_OpenStatusUpdate_descriptor =
      getDescriptor().getMessageTypes().get(42);
    internal_static_lnrpc_OpenStatusUpdate_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_OpenStatusUpdate_descriptor,
        new java.lang.String[] { "ChanPending", "Confirmation", "ChanOpen", "Update", });
    internal_static_lnrpc_PendingHTLC_descriptor =
      getDescriptor().getMessageTypes().get(43);
    internal_static_lnrpc_PendingHTLC_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_PendingHTLC_descriptor,
        new java.lang.String[] { "Incoming", "Amount", "Outpoint", "MaturityHeight", "BlocksTilMaturity", "Stage", });
    internal_static_lnrpc_PendingChannelsRequest_descriptor =
      getDescriptor().getMessageTypes().get(44);
    internal_static_lnrpc_PendingChannelsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_PendingChannelsRequest_descriptor,
        new java.lang.String[] { });
    internal_static_lnrpc_PendingChannelsResponse_descriptor =
      getDescriptor().getMessageTypes().get(45);
    internal_static_lnrpc_PendingChannelsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_PendingChannelsResponse_descriptor,
        new java.lang.String[] { "TotalLimboBalance", "PendingOpenChannels", "PendingClosingChannels", "PendingForceClosingChannels", });
    internal_static_lnrpc_PendingChannelsResponse_PendingChannel_descriptor =
      internal_static_lnrpc_PendingChannelsResponse_descriptor.getNestedTypes().get(0);
    internal_static_lnrpc_PendingChannelsResponse_PendingChannel_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_PendingChannelsResponse_PendingChannel_descriptor,
        new java.lang.String[] { "RemoteNodePub", "ChannelPoint", "Capacity", "LocalBalance", "RemoteBalance", });
    internal_static_lnrpc_PendingChannelsResponse_PendingOpenChannel_descriptor =
      internal_static_lnrpc_PendingChannelsResponse_descriptor.getNestedTypes().get(1);
    internal_static_lnrpc_PendingChannelsResponse_PendingOpenChannel_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_PendingChannelsResponse_PendingOpenChannel_descriptor,
        new java.lang.String[] { "Channel", "ConfirmationHeight", "CommitFee", "CommitWeight", "FeePerKw", });
    internal_static_lnrpc_PendingChannelsResponse_ClosedChannel_descriptor =
      internal_static_lnrpc_PendingChannelsResponse_descriptor.getNestedTypes().get(2);
    internal_static_lnrpc_PendingChannelsResponse_ClosedChannel_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_PendingChannelsResponse_ClosedChannel_descriptor,
        new java.lang.String[] { "Channel", "ClosingTxid", });
    internal_static_lnrpc_PendingChannelsResponse_ForceClosedChannel_descriptor =
      internal_static_lnrpc_PendingChannelsResponse_descriptor.getNestedTypes().get(3);
    internal_static_lnrpc_PendingChannelsResponse_ForceClosedChannel_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_PendingChannelsResponse_ForceClosedChannel_descriptor,
        new java.lang.String[] { "Channel", "ClosingTxid", "LimboBalance", "MaturityHeight", "BlocksTilMaturity", "RecoveredBalance", "PendingHtlcs", });
    internal_static_lnrpc_WalletBalanceRequest_descriptor =
      getDescriptor().getMessageTypes().get(46);
    internal_static_lnrpc_WalletBalanceRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_WalletBalanceRequest_descriptor,
        new java.lang.String[] { "WitnessOnly", });
    internal_static_lnrpc_WalletBalanceResponse_descriptor =
      getDescriptor().getMessageTypes().get(47);
    internal_static_lnrpc_WalletBalanceResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_WalletBalanceResponse_descriptor,
        new java.lang.String[] { "TotalBalance", "ConfirmedBalance", "UnconfirmedBalance", });
    internal_static_lnrpc_ChannelBalanceRequest_descriptor =
      getDescriptor().getMessageTypes().get(48);
    internal_static_lnrpc_ChannelBalanceRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_ChannelBalanceRequest_descriptor,
        new java.lang.String[] { });
    internal_static_lnrpc_ChannelBalanceResponse_descriptor =
      getDescriptor().getMessageTypes().get(49);
    internal_static_lnrpc_ChannelBalanceResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_ChannelBalanceResponse_descriptor,
        new java.lang.String[] { "Balance", });
    internal_static_lnrpc_QueryRoutesRequest_descriptor =
      getDescriptor().getMessageTypes().get(50);
    internal_static_lnrpc_QueryRoutesRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_QueryRoutesRequest_descriptor,
        new java.lang.String[] { "PubKey", "Amt", "NumRoutes", });
    internal_static_lnrpc_QueryRoutesResponse_descriptor =
      getDescriptor().getMessageTypes().get(51);
    internal_static_lnrpc_QueryRoutesResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_QueryRoutesResponse_descriptor,
        new java.lang.String[] { "Routes", });
    internal_static_lnrpc_Hop_descriptor =
      getDescriptor().getMessageTypes().get(52);
    internal_static_lnrpc_Hop_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_Hop_descriptor,
        new java.lang.String[] { "ChanId", "ChanCapacity", "AmtToForward", "Fee", "Expiry", });
    internal_static_lnrpc_Route_descriptor =
      getDescriptor().getMessageTypes().get(53);
    internal_static_lnrpc_Route_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_Route_descriptor,
        new java.lang.String[] { "TotalTimeLock", "TotalFees", "TotalAmt", "Hops", });
    internal_static_lnrpc_NodeInfoRequest_descriptor =
      getDescriptor().getMessageTypes().get(54);
    internal_static_lnrpc_NodeInfoRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_NodeInfoRequest_descriptor,
        new java.lang.String[] { "PubKey", });
    internal_static_lnrpc_NodeInfo_descriptor =
      getDescriptor().getMessageTypes().get(55);
    internal_static_lnrpc_NodeInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_NodeInfo_descriptor,
        new java.lang.String[] { "Node", "NumChannels", "TotalCapacity", });
    internal_static_lnrpc_LightningNode_descriptor =
      getDescriptor().getMessageTypes().get(56);
    internal_static_lnrpc_LightningNode_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_LightningNode_descriptor,
        new java.lang.String[] { "LastUpdate", "PubKey", "Alias", "Addresses", "Color", });
    internal_static_lnrpc_NodeAddress_descriptor =
      getDescriptor().getMessageTypes().get(57);
    internal_static_lnrpc_NodeAddress_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_NodeAddress_descriptor,
        new java.lang.String[] { "Network", "Addr", });
    internal_static_lnrpc_RoutingPolicy_descriptor =
      getDescriptor().getMessageTypes().get(58);
    internal_static_lnrpc_RoutingPolicy_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_RoutingPolicy_descriptor,
        new java.lang.String[] { "TimeLockDelta", "MinHtlc", "FeeBaseMsat", "FeeRateMilliMsat", });
    internal_static_lnrpc_ChannelEdge_descriptor =
      getDescriptor().getMessageTypes().get(59);
    internal_static_lnrpc_ChannelEdge_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_ChannelEdge_descriptor,
        new java.lang.String[] { "ChannelId", "ChanPoint", "LastUpdate", "Node1Pub", "Node2Pub", "Capacity", "Node1Policy", "Node2Policy", });
    internal_static_lnrpc_ChannelGraphRequest_descriptor =
      getDescriptor().getMessageTypes().get(60);
    internal_static_lnrpc_ChannelGraphRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_ChannelGraphRequest_descriptor,
        new java.lang.String[] { });
    internal_static_lnrpc_ChannelGraph_descriptor =
      getDescriptor().getMessageTypes().get(61);
    internal_static_lnrpc_ChannelGraph_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_ChannelGraph_descriptor,
        new java.lang.String[] { "Nodes", "Edges", });
    internal_static_lnrpc_ChanInfoRequest_descriptor =
      getDescriptor().getMessageTypes().get(62);
    internal_static_lnrpc_ChanInfoRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_ChanInfoRequest_descriptor,
        new java.lang.String[] { "ChanId", });
    internal_static_lnrpc_NetworkInfoRequest_descriptor =
      getDescriptor().getMessageTypes().get(63);
    internal_static_lnrpc_NetworkInfoRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_NetworkInfoRequest_descriptor,
        new java.lang.String[] { });
    internal_static_lnrpc_NetworkInfo_descriptor =
      getDescriptor().getMessageTypes().get(64);
    internal_static_lnrpc_NetworkInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_NetworkInfo_descriptor,
        new java.lang.String[] { "GraphDiameter", "AvgOutDegree", "MaxOutDegree", "NumNodes", "NumChannels", "TotalNetworkCapacity", "AvgChannelSize", "MinChannelSize", "MaxChannelSize", });
    internal_static_lnrpc_StopRequest_descriptor =
      getDescriptor().getMessageTypes().get(65);
    internal_static_lnrpc_StopRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_StopRequest_descriptor,
        new java.lang.String[] { });
    internal_static_lnrpc_StopResponse_descriptor =
      getDescriptor().getMessageTypes().get(66);
    internal_static_lnrpc_StopResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_StopResponse_descriptor,
        new java.lang.String[] { });
    internal_static_lnrpc_GraphTopologySubscription_descriptor =
      getDescriptor().getMessageTypes().get(67);
    internal_static_lnrpc_GraphTopologySubscription_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_GraphTopologySubscription_descriptor,
        new java.lang.String[] { });
    internal_static_lnrpc_GraphTopologyUpdate_descriptor =
      getDescriptor().getMessageTypes().get(68);
    internal_static_lnrpc_GraphTopologyUpdate_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_GraphTopologyUpdate_descriptor,
        new java.lang.String[] { "NodeUpdates", "ChannelUpdates", "ClosedChans", });
    internal_static_lnrpc_NodeUpdate_descriptor =
      getDescriptor().getMessageTypes().get(69);
    internal_static_lnrpc_NodeUpdate_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_NodeUpdate_descriptor,
        new java.lang.String[] { "Addresses", "IdentityKey", "GlobalFeatures", "Alias", });
    internal_static_lnrpc_ChannelEdgeUpdate_descriptor =
      getDescriptor().getMessageTypes().get(70);
    internal_static_lnrpc_ChannelEdgeUpdate_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_ChannelEdgeUpdate_descriptor,
        new java.lang.String[] { "ChanId", "ChanPoint", "Capacity", "RoutingPolicy", "AdvertisingNode", "ConnectingNode", });
    internal_static_lnrpc_ClosedChannelUpdate_descriptor =
      getDescriptor().getMessageTypes().get(71);
    internal_static_lnrpc_ClosedChannelUpdate_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_ClosedChannelUpdate_descriptor,
        new java.lang.String[] { "ChanId", "Capacity", "ClosedHeight", "ChanPoint", });
    internal_static_lnrpc_Invoice_descriptor =
      getDescriptor().getMessageTypes().get(72);
    internal_static_lnrpc_Invoice_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_Invoice_descriptor,
        new java.lang.String[] { "Memo", "Receipt", "RPreimage", "RHash", "Value", "Settled", "CreationDate", "SettleDate", "PaymentRequest", "DescriptionHash", "Expiry", "FallbackAddr", "CltvExpiry", });
    internal_static_lnrpc_AddInvoiceResponse_descriptor =
      getDescriptor().getMessageTypes().get(73);
    internal_static_lnrpc_AddInvoiceResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_AddInvoiceResponse_descriptor,
        new java.lang.String[] { "RHash", "PaymentRequest", });
    internal_static_lnrpc_PaymentHash_descriptor =
      getDescriptor().getMessageTypes().get(74);
    internal_static_lnrpc_PaymentHash_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_PaymentHash_descriptor,
        new java.lang.String[] { "RHashStr", "RHash", });
    internal_static_lnrpc_ListInvoiceRequest_descriptor =
      getDescriptor().getMessageTypes().get(75);
    internal_static_lnrpc_ListInvoiceRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_ListInvoiceRequest_descriptor,
        new java.lang.String[] { "PendingOnly", });
    internal_static_lnrpc_ListInvoiceResponse_descriptor =
      getDescriptor().getMessageTypes().get(76);
    internal_static_lnrpc_ListInvoiceResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_ListInvoiceResponse_descriptor,
        new java.lang.String[] { "Invoices", });
    internal_static_lnrpc_InvoiceSubscription_descriptor =
      getDescriptor().getMessageTypes().get(77);
    internal_static_lnrpc_InvoiceSubscription_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_InvoiceSubscription_descriptor,
        new java.lang.String[] { });
    internal_static_lnrpc_Payment_descriptor =
      getDescriptor().getMessageTypes().get(78);
    internal_static_lnrpc_Payment_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_Payment_descriptor,
        new java.lang.String[] { "PaymentHash", "Value", "CreationDate", "Path", "Fee", "PaymentPreimage", });
    internal_static_lnrpc_ListPaymentsRequest_descriptor =
      getDescriptor().getMessageTypes().get(79);
    internal_static_lnrpc_ListPaymentsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_ListPaymentsRequest_descriptor,
        new java.lang.String[] { });
    internal_static_lnrpc_ListPaymentsResponse_descriptor =
      getDescriptor().getMessageTypes().get(80);
    internal_static_lnrpc_ListPaymentsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_ListPaymentsResponse_descriptor,
        new java.lang.String[] { "Payments", });
    internal_static_lnrpc_DeleteAllPaymentsRequest_descriptor =
      getDescriptor().getMessageTypes().get(81);
    internal_static_lnrpc_DeleteAllPaymentsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_DeleteAllPaymentsRequest_descriptor,
        new java.lang.String[] { });
    internal_static_lnrpc_DeleteAllPaymentsResponse_descriptor =
      getDescriptor().getMessageTypes().get(82);
    internal_static_lnrpc_DeleteAllPaymentsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_DeleteAllPaymentsResponse_descriptor,
        new java.lang.String[] { });
    internal_static_lnrpc_DebugLevelRequest_descriptor =
      getDescriptor().getMessageTypes().get(83);
    internal_static_lnrpc_DebugLevelRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_DebugLevelRequest_descriptor,
        new java.lang.String[] { "Show", "LevelSpec", });
    internal_static_lnrpc_DebugLevelResponse_descriptor =
      getDescriptor().getMessageTypes().get(84);
    internal_static_lnrpc_DebugLevelResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_DebugLevelResponse_descriptor,
        new java.lang.String[] { "SubSystems", });
    internal_static_lnrpc_PayReqString_descriptor =
      getDescriptor().getMessageTypes().get(85);
    internal_static_lnrpc_PayReqString_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_PayReqString_descriptor,
        new java.lang.String[] { "PayReq", });
    internal_static_lnrpc_PayReq_descriptor =
      getDescriptor().getMessageTypes().get(86);
    internal_static_lnrpc_PayReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_PayReq_descriptor,
        new java.lang.String[] { "Destination", "PaymentHash", "NumSatoshis", "Timestamp", "Expiry", "Description", "DescriptionHash", "FallbackAddr", "CltvExpiry", });
    internal_static_lnrpc_FeeReportRequest_descriptor =
      getDescriptor().getMessageTypes().get(87);
    internal_static_lnrpc_FeeReportRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_FeeReportRequest_descriptor,
        new java.lang.String[] { });
    internal_static_lnrpc_ChannelFeeReport_descriptor =
      getDescriptor().getMessageTypes().get(88);
    internal_static_lnrpc_ChannelFeeReport_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_ChannelFeeReport_descriptor,
        new java.lang.String[] { "ChanPoint", "BaseFeeMsat", "FeePerMil", "FeeRate", });
    internal_static_lnrpc_FeeReportResponse_descriptor =
      getDescriptor().getMessageTypes().get(89);
    internal_static_lnrpc_FeeReportResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_FeeReportResponse_descriptor,
        new java.lang.String[] { "ChannelFees", });
    internal_static_lnrpc_PolicyUpdateRequest_descriptor =
      getDescriptor().getMessageTypes().get(90);
    internal_static_lnrpc_PolicyUpdateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_PolicyUpdateRequest_descriptor,
        new java.lang.String[] { "Global", "ChanPoint", "BaseFeeMsat", "FeeRate", "TimeLockDelta", "Scope", });
    internal_static_lnrpc_PolicyUpdateResponse_descriptor =
      getDescriptor().getMessageTypes().get(91);
    internal_static_lnrpc_PolicyUpdateResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lnrpc_PolicyUpdateResponse_descriptor,
        new java.lang.String[] { });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.api.AnnotationsProto.http);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.api.AnnotationsProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
