// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc.proto

package lightpay.lnd.grpc;

public interface WalletBalanceResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:lnrpc.WalletBalanceResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *&#47; The balance of the wallet
   * </pre>
   *
   * <code>int64 total_balance = 1[json_name = "total_balance"];</code>
   */
  long getTotalBalance();

  /**
   * <pre>
   *&#47; The confirmed balance of a wallet(with &gt;= 1 confirmations)
   * </pre>
   *
   * <code>int64 confirmed_balance = 2[json_name = "confirmed_balance"];</code>
   */
  long getConfirmedBalance();

  /**
   * <pre>
   *&#47; The unconfirmed balance of a wallet(with 0 confirmations)
   * </pre>
   *
   * <code>int64 unconfirmed_balance = 3[json_name = "unconfirmed_balance"];</code>
   */
  long getUnconfirmedBalance();
}
